### ISSUE TITLE
Addin support for video streaming in VC and DM

### ISSUE THREAD

**Issue by Kirill-iceland** [discordjs/discord.js#5356] opened 2021-02-27 01:00 UTC
The current **API** only has support for audio streaming. 

**Why?**
It would open many new possibilities to interact with bots like playing **videos** from youtube and creating new types of games.

**Comment by advaith1** [comment] 2021-02-27 01:01
Discord intentionally doesn't support video streaming for bots due to its complexity, nothing d.js can do about that

**Comment by vBread** [comment] 2021-02-27 01:01
Bots can't stream videos.

**Comment by TheRamann** [comment] 2021-02-27 15:49
There would be many movie streaming bots which would be pretty much illegal and discord could be in some trouble because of that.

**Comment by kyranet** [comment] 2021-02-27 16:54
Duplicate of #4116.

**Closed by kyranet** 2021-02-27 16:54 UTC
Labels: type: enhancement
