### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'onmessage')

### ISSUE THREAD

**Issue by l1v0n1** [discordjs/discord.js#8980] opened 2022-12-26 14:33 UTC
### Which package is this bug report for?

discord.js

### Issue description

Bot catch error

### Code sample

```typescript
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 163ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 11087ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 5203ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 9131ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 23495ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 17746ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 40558ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 15899ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 23288ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 228ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Heartbeat acknowledged, latency of 179ms.
[WS => Shard 1] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 1] Tried to send packet '{"op":1,"d":1549}' but no WebSocket is available!
[WS => Shard 1] [DESTROY]
    Close Code    : 4000
    Reset         : false
    Emit DESTROYED: true
[WS => Shard 1] Clearing the heartbeat interval.
[WS => Shard 1] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSING
[WS => Shard 1] WS State: CLOSING
[WS => Shard 1] Shard was destroyed but no WebSocket connection was present! Reconnecting...
[WS => Shard 1] A connection object was found. Cleaning up before continuing.
    State: CLOSING
[WS => Shard 1] [DESTROY]
    Close Code    : 1000
    Reset         : false
    Emit DESTROYED: false
[WS => Shard 1] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSING
[WS => Shard 1] WS State: CLOSING
[WS => Shard 1] [WebSocket] Adding a WebSocket close timeout to ensure a correct WS reconnect.
        Timeout: 5000ms
[WS => Shard 1] [CONNECT]
    Gateway    : wss://gateway-us-east1-b.discord.gg
    Version    : 10
    Encoding   : json
    Compression: none
[WS => Shard 1] Setting a HELLO timeout for 20s.
[WS => Shard 1] [WebSocket] Clearing the close timeout.
[WS => Shard 1] [WebSocket] Close Emitted: false
[WS => Shard 1] [WebSocket] did not close properly, assuming a zombie connection.
Emitting close and reconnecting again.
C:\Users\Admin\Desktop\neurobalbes discord js\node_modules\discord.js\src\client\websocket\WebSocketShard.js:883
    this.connection.onopen = this.connection.onclose = this.connection.onmessage = null;
                                                                                 ^

TypeError: Cannot set properties of null (setting 'onmessage')
    at WebSocketShard._cleanupConnection (C:\Users\Admin\Desktop\neurobalbes discord js\node_modules\discord.js\src\client\websocket\WebSocketShard.js:883:82)
    at Timeout.<anonymous> (C:\Users\Admin\Desktop\neurobalbes discord js\node_modules\discord.js\src\client\websocket\WebSocketShard.js:606:12)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

### Package version

dev discord.js@14.7.2

### Node.js version

v18.12.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by Qjuh** [comment] 2022-12-27 07:51
Could you double-check the version of discord.js you're using, because that stacktrace doesn't match 14.7.1 but looks more like it might come from a dev build.

**Comment by l1v0n1** [comment] 2022-12-27 08:20
> Could you double-check the version of discord.js you're using, because that stacktrace doesn't match 14.7.1 but looks more like it might come from a dev build.

i'm using zombie connection fix

https://github.com/discordjs/discord.js/pull/8927

**Comment by Qjuh** [comment] 2022-12-27 10:01
> > Could you double-check the version of discord.js you're using, because that stacktrace doesn't match 14.7.1 but looks more like it might come from a dev build.
> 
> i'm using zombie connection fix version is 14.7.1 edited
> 
> #8927

Version is **not** 14.7.1 in that case, if you use #8927 you use a dev version of 14.7.2 so please state the exact version you're using else it's hard to track your issue down (since there's been three seperate PRs handling WebSocketShard in it yet).

**Comment by Jiralite** [comment] 2023-02-16 23:00
Is this issue still reproducible in our development versions now?

**Comment by l1v0n1** [comment] 2023-02-21 05:58
yea> Is this issue still reproducible in our development versions now?

**Comment by l1v0n1** [comment] 2023-02-21 05:59
> Is this issue still reproducible in our development versions now?

yea

**Comment by Qjuh** [comment] 2023-02-21 06:24
State the exact version you‘re using then. Else this **still** can’t be tracked down by us.

**Comment by l1v0n1** [comment] 2023-02-21 06:29
> State the exact version you‘re using then. Else this still can’t be tracked down by us.

it's happening in 14.7.1, 14.7.0 and beyond

**Comment by Qjuh** [comment] 2023-02-21 06:37
You said it was reproducible in the development version, those have exact version identifiers themselves. Calling them *beyond* is not helping in figuring out where the error comes from. Unless you‘re able to send the exact output of `npm ls discord.js` for the development release version that still has this issue there’s nothing I can do.

**Comment by l1v0n1** [comment] 2023-02-21 06:40
> You said it was reproducible in the development version, those have exact version identifiers themselves. Calling them *beyond* is not helping in figuring out where the error comes from. Unless you‘re able to send the exact output of `npm ls discord.js` for the development release version that still has this issue there’s nothing I can do.

I'm trying to say, that this issue exists in few versions and I think it's discord's problem, I tested only in 14.7.1 and 14.7.0.
In dev version this problem may solbed, cause fix from legendhimself added reconnecting to shard everytime when shard disconnect

**Comment by Qjuh** [comment] 2023-02-21 08:30
> > Is this issue still reproducible in our development versions now?
> 
> yea

So this was a lie, you didn’t reproduce it in development versions… either try if it‘s reproducible or this issue can be closed.

**Comment by l1v0n1** [comment] 2023-02-21 09:47
> So this was a lie, you didn’t reproduce it in development versions… either try if it‘s reproducible or this issue can be closed.

on the dev branch, this problem occurs less frequently, but occurs

**Comment by Qjuh** [comment] 2023-02-21 12:41
Until you finally mention an actual dev version that this bug occurs on this is fixed in my eyes.

**Closed** 2023-04-01 09:28 UTC
Labels: bug, gateway, need repro, packages:discord.js
