### ISSUE TITLE
client.destroy() isn't doing it's intended function in certain circumstances

### ISSUE THREAD

**Issue by dfault-user** [discordjs/discord.js#2557] opened 2018-05-17 17:21 UTC
**Please describe the problem you are having in as much detail as possible:**
The only issue I am having is this bit of error stack.
`/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/rest/RESTManager.js:19
    for (const handler of Object.values(this.handlers)) {
                                 ^

TypeError: Object.values is not a function
    at RESTManager.destroy (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/rest/RESTManager.js:19:34)
    at ClientManager.destroy (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/ClientManager.js:60:22)
    at Client.destroy (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/Client.js:289:25)
    at sd (/home/ubuntu/workspace/Random-Cat/bot.js:45:9)
    at Client.client.on.err (/home/ubuntu/workspace/Random-Cat/bot.js:37:3)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/ubuntu/workspace/Random-Cat/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)`

**Include a reproducible code sample here, if possible:**
```js
if(command=="shutdown" && msg.author.id == 113610951059570692) {
		msg.reply("I don't feel so good..");
		sd();
	} // the command function
function sd() {
	client.destroy()
} // the function to destroy client (which i tried as a workaround)
```

**Further details:**

- discord.js version: 3.10.10
- node.js version: v6.11.2
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: Somewhere in the middle of urgent and common.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment] 2018-05-17 17:46
Please give us an accurate version of Discord.js with 

```
npm ls discord.js
```

**Comment by dfault-user** [comment] 2018-05-17 18:47
@kyranet comes back with
`├── UNMET PEER DEPENDENCY bufferutil@^3.0.3
├── discord.js@11.3.2 
├── UNMET PEER DEPENDENCY erlpack@discordapp/erlpack
├── UNMET PEER DEPENDENCY libsodium-wrappers@^0.7.3
├── UNMET PEER DEPENDENCY node-opus@^0.2.7
├── UNMET PEER DEPENDENCY opusscript@^0.0.6
├── UNMET PEER DEPENDENCY sodium@^2.0.3
└── UNMET PEER DEPENDENCY uws@^9.14.0

npm ERR! peer dep missing: bufferutil@^3.0.3, required by discord.js@11.3.2
npm ERR! peer dep missing: erlpack@discordapp/erlpack, required by discord.js@11.3.2
npm ERR! peer dep missing: node-opus@^0.2.7, required by discord.js@11.3.2
npm ERR! peer dep missing: opusscript@^0.0.6, required by discord.js@11.3.2
npm ERR! peer dep missing: sodium@^2.0.3, required by discord.js@11.3.2
npm ERR! peer dep missing: libsodium-wrappers@^0.7.3, required by discord.js@11.3.2
npm ERR! peer dep missing: uws@^9.14.0, required by discord.js@11.3.2
brandan000124:~/workspace/Random-Cat (master) $ npm ls discord.js
Random-Cat@0.0.1 /home/ubuntu/workspace/Random-Cat
├── UNMET PEER DEPENDENCY bufferutil@^3.0.3
├── discord.js@11.3.2 
├── UNMET PEER DEPENDENCY erlpack@discordapp/erlpack
├── UNMET PEER DEPENDENCY libsodium-wrappers@^0.7.3
├── UNMET PEER DEPENDENCY node-opus@^0.2.7
├── UNMET PEER DEPENDENCY opusscript@^0.0.6
├── UNMET PEER DEPENDENCY sodium@^2.0.3
└── UNMET PEER DEPENDENCY uws@^9.14.0

npm ERR! peer dep missing: bufferutil@^3.0.3, required by discord.js@11.3.2
npm ERR! peer dep missing: erlpack@discordapp/erlpack, required by discord.js@11.3.2
npm ERR! peer dep missing: node-opus@^0.2.7, required by discord.js@11.3.2
npm ERR! peer dep missing: opusscript@^0.0.6, required by discord.js@11.3.2
npm ERR! peer dep missing: sodium@^2.0.3, required by discord.js@11.3.2
npm ERR! peer dep missing: libsodium-wrappers@^0.7.3, required by discord.js@11.3.2
npm ERR! peer dep missing: uws@^9.14.0, required by discord.js@11.3.2`

**Comment by dfault-user** [comment] 2018-05-17 18:48
i see the issue :eyes:

**Comment by iCrawl** [comment] 2018-05-18 01:25
Duplicate of #2486

**Closed by iCrawl** 2018-05-18 01:25 UTC
