### ISSUE TITLE
rateLimit event not fired for ratelimit received during login

### ISSUE THREAD

**Issue by MattIPv4** [discordjs/discord.js#3891] opened 2020-03-03 22:17 UTC
**Please describe the problem you are having in as much detail as possible:**

Related to the issue I encountered in #3890, it seems that not only does the client not back off when it gets a ratelimited response during login, but it also doesn't fire the documented rateLimit event.

**Include a reproducible code sample here, if possible:**

```js
// This requires you be ratelimited
const client = new Client();
client.on('debug', (...args) => console.log('debug', ...args));
client.on('rateLimit', (...args) => console.log('rateLimit', ...args));
await client.login(token);
// Observe continual 'debug' logs
// Observe no 'rateLimit' logs
```

Logs from a slightly more fleshed out bot script:

```
 MNGR | 20/3/3 22:13:38  INFO  Launched shard 0
 S0 | 20/3/3 22:13:39  INFO  Logging in...
 S0 | 20/3/3 22:13:39  DEBUG  Provided token: [SNIP]
 S0 | 20/3/3 22:13:39  DEBUG  Preparing to connect to the gateway...
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
 S0 | 20/3/3 22:13:39  DEBUG  429 hit on route /gateway/bot
^C
```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: 12.15.0
- Operating system: Windows server 2016
- Priority this issue should have – please be realistic and elaborate if possible: P2 - Less important than the client actually ignoring the ratelimits, but if you have a documented ratelimit event, it really should fire on ratelimits.

**Comment by Koyamie** [comment] 2020-03-16 18:52
Hello, can this issue take a real priority ? Been few months now and today I can not even start my bot without being ratelimited every single time.

**Comment by TheMonsters29** [comment] 2020-05-02 22:43
i have same problem 130k guilds

**Comment by cal3432** [comment] 2020-05-26 19:53
I can verify this is true, debugged and got a 429 error on /gateway/bot

Ratelimited, no error, nothing.

**Comment by mwalden2004** [comment] 2020-06-26 18:12
I'm having this same problem.

**Comment by Cyanic76** [comment] 2020-07-02 07:45
I'm also having the same problem. It has been doing that since yesterday.

**Comment by aya1337** [comment] 2020-08-05 21:11
im having this as well

**Comment by DjDeveloperr** [comment] 2020-08-27 08:39
Same here. It's happening like _every_ day.

**Comment by xXLoloGameplayXx** [comment] 2020-10-09 13:35
I get the same error every day

**Comment by DjDeveloperr** [comment] 2020-10-10 03:46
Since this is solved for me already - I would love to tell what was happening. I was using a many webhooks as logging methods and not all the hooks weren't coordinating the rate limits, when bot was getting *more* actively used, logs increased and it hit Cloudflare ban. I have now switched to LogDNA for logging and didn't hit that since months. 
There can be more reasons for this like your host might be sharing the same IP with other clients (Glitch for example), or you have multiple bots hosted on same VPS. 
The reason for this ratelimit's spam is that retry-after given in the headers needs to be multiplied by 1000 ONLY when a Cloudflare ban is hit for it to be accurate (yes, I've tried it, doesn't spam).
Issue: https://github.com/discordjs/discord.js/issues/3560

**Comment by Acituanbus** [comment] 2020-10-21 11:06
I have the same issue. I created and instantly deleted ~40 webhooks in the span of 2 minutes and got no error about a ratelimit, but couldn't create another webhook for ~10 minutes.

**Comment by cherryblossom000** [comment] 2020-11-29 01:30
I'm having the same issue. Even though my bot is only in 2 guilds it would be nice if the `rateLimit` event fired for the `/gateway/bot` endpoint so I would have noticed this issue earlier.

Interestingly enough, fetching that endpoint on my machine works:

```
$ curl 'https://discord.com/api/v8/gateway/bot' -H "Authorization: Bot $DISCORD_TOKEN" -i
HTTP/2 200 
date: Sun, 29 Nov 2020 01:26:03 GMT
content-type: application/json
set-cookie: __cfduid=dc0d9e8a81f7d9281b6d6388624d8327a1606613163; expires=Tue, 29-Dec-20 01:26:03 GMT; path=/; domain=.discord.com; HttpOnly; SameSite=Lax; Secure
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-ratelimit-bucket: 41f9cd5d28af77da04563bcb1d67fdfd
x-ratelimit-limit: 2
x-ratelimit-remaining: 1
x-ratelimit-reset: 1606613168.588
x-ratelimit-reset-after: 5.000
x-envoy-upstream-service-time: 33
via: 1.1 google
cf-cache-status: DYNAMIC
cf-request-id: 06b33475b70000fea5bb9d3000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=z1YNxfWCm51pzEYAcr99W7lpQAaiTkLTz2tRfHZ0webHmiEbPrrSlDzIzkbh2TYjAzBKZsBe%2BRNnN9SyopIlBqR5IjOxP97CTtZ0RA%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
x-content-type-options: nosniff
server: cloudflare
cf-ray: 5f9889cf8eb5fea5-MEL

{"url": "wss://gateway.discord.gg", "shards": 1, "session_start_limit": {"total": 1000, "remaining": 1000, "reset_after": 0, "max_concurrency": 1}}
```

However, doing the same in production (on [Repl.it](https://repl.it)) causes the rate limit:

```
$ curl 'https://discord.com/api/v8/gateway/bot' -H "Authorization: Bot $DISCORD_TOKEN" -i       
HTTP/2 429 
date: Sun, 29 Nov 2020 01:26:00 GMT
content-type: text/plain; charset=UTF-8
content-length: 16
retry-after: 54116
x-frame-options: SAMEORIGIN
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
set-cookie: __cfduid=d9b16993c3486958a1e5bee275b64f6fe1606613160; expires=Tue, 29-Dec-20 01:26:00 GMT; path=/; domain=.discord.com; HttpOnly; SameSite=Lax; Secure
cf-request-id: 06b3346930000071e357140000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=43kfKbugiK2XryZhq8de2544Kg0rXrbt68jt%2B9m%2BaHBkCKVkfSGQZ6pNkuuIpVJ02K2qFyIExoAt%2BwG1UOAKJ%2BmMhE2OyiiYdcU7kw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 5f9889bb88f171e3-ORD

error code: 1015
```

I made these requests within a minute, so this makes me think that Discord has different rate limits for different IP addresses, or something like that.

**Comment by advaith1** [comment] 2020-11-29 02:34
The `rateLimit` event only fires when discord.js delays a request to avoid a 429, not when it actually hits a 429.

**Comment by aya1337** [comment] 2020-11-30 10:18
How come the library is not considering cloudflare ratelimits?

**Comment by PxlLoewe** [comment] 2021-02-02 08:25
same problem here

Event not triggered on rateLimit

![image](https://user-images.githubusercontent.com/72106766/106572225-7591de80-6538-11eb-9850-078abeaee87e.png)

![image](https://user-images.githubusercontent.com/72106766/106572262-804c7380-6538-11eb-973d-a8d7c652b2f2.png)

**Comment by advaith1** [comment] 2021-02-02 17:59
that's the daily identify limit, not a http ratelimit, but it's fixed by #5283

**Comment by strange-idiot** [comment] 2021-04-23 04:02
Uninstall Discordjs then reinstall it.

That should work
(I tried it and it worked)

**Comment by Poly-Pixel** [comment] 2021-07-22 19:40
> that's the daily identify limit, not a http ratelimit, but it's fixed by #5283

So, is this still an issue on master branch?

**Comment by FernandoTBarros** [comment] 2022-01-13 02:06
I'm having this issue on a simple operation like changing the name of a Channel.
In my tests I got that I can only change a channel name 3 times in 10 minutes, but when doing this in discord.js nothing happens, I'v discovered what the problem is when doing tests with Postman. 
I think that an error should be thrown if the operation didn't return 200. Or at least return some message. But nothing happens.

**Comment by ckohen** [comment] 2022-01-13 02:43
Your issue is completely unrelated to this issue and has to do with sublimits (you can actually only change channel name 2 times in 10 minutes), discord.js stalls the third request (after hitting 429 once) and any further request to the endpoint until the ratelimit expires. Usually you do not even hit 429s, but discord doesn't return sublimit data in the headers so we do in that one case.

Additionally there is already a client option to reject the promise upon hitting that ratelimit, appropriately named rejectOnRateLimit

**Comment by Jiralite** [comment] 2022-11-02 11:18
For a while now, we've been using a new REST implementation. If this still exists, feel free to open a new issue.

**Closed by Jiralite** 2022-11-02 11:18 UTC
Labels: bug, ratelimits, REST, sharding, packages:discord.js
