### ISSUE TITLE
channel.setPosition returns guild object instead of channel object

### ISSUE THREAD

**Issue by RedSparr0w** [discordjs/discord.js#3413] opened 2019-07-29 23:37 UTC
***Please describe the problem you are having in as much detail as possible:***
[Channel.setPosition(position)](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=setPosition) returns a guild object instead of a channel object

***Include a reproducible code sample here, if possible:***
```js
const new_channel = await guild.createChannel('mychannel', { type: 'text' });
// returns guild instead of channel object
const guild = await new_channel.setPosition(2);
```

***Further details:***
- discord.js version: `v11.5.1`
- Node.js version: `v10.7.0`
- Operating system: `Windows server 2008 R2`
- Priority this issue should have – please be realistic and elaborate if possible: low

---------------

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment] 2019-07-30 00:08
Confirmed bug exists on 11.5.1
Fixed on master

**Comment by Fyk0** [comment] 2019-07-30 03:22
This occurs because [`Channel#setPosition`](https://github.com/discordjs/discord.js/blob/stable/src/structures/GuildChannel.js#L334) just returns [`Guild#setChannelPosition`](https://github.com/discordjs/discord.js/blob/5dd9181497f3d3b443a6ab5bfda1930eac278304/src/structures/Guild.js#L1386) which returns [`Guild`](https://github.com/discordjs/discord.js/blob/5dd9181497f3d3b443a6ab5bfda1930eac278304/src/structures/Guild.js#L1384).

**Comment by SpaceEEC** [comment] 2019-07-30 15:54
Fixed with the referenced commit ^

Thank you for reporting!

**Closed by SpaceEEC** 2019-07-30 15:54 UTC
Labels: p: low, t: REST, type: bug
