### ISSUE TITLE
Bot crash due to TypeError: Cannot read properties of undefined (reading 'get') handing THREAD_MEMBERS_UPDATE packet

### ISSUE THREAD

**Issue by kevinlul** [discordjs/discord.js#10401] opened 2024-07-21 17:32 UTC
### Which package is this bug report for?

discord.js

### Issue description

Our bot crashed at around 2024-07-21 17:18 UTC with this stack trace
```
/app/node_modules/discord.js/src/client/actions/Action.js:27
    return this.client.options.partials.includes(partialType) ? manager._add(data, cache) : manager.cache.get(id);
                                                                                                          ^
TypeError: Cannot read properties of undefined (reading 'get')
    at ThreadMembersUpdateAction.getPayload (/app/node_modules/discord.js/src/client/actions/Action.js:27:107)
    at ThreadMembersUpdateAction.getThreadMember (/app/node_modules/discord.js/src/client/actions/Action.js:112:17)
    at /app/node_modules/discord.js/src/client/actions/ThreadMembersUpdate.js:22:35
    at Array.reduce (<anonymous>)
    at ThreadMembersUpdateAction.handle (/app/node_modules/discord.js/src/client/actions/ThreadMembersUpdate.js:21:32)
    at module.exports [as THREAD_MEMBERS_UPDATE] (/app/node_modules/discord.js/src/client/websocket/handlers/THREAD_MEMBERS_UPDATE.js:4:38)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/app/node_modules/@vladfrangu/async_event_emitter/src/index.ts:459:28)
    at WebSocketShard.<anonymous> (/app/node_modules/@discordjs/ws/src/strategies/sharding/SimpleShardingStrategy.ts:32:47)
Node.js v20.15.0
```

### Versions

- discord.js 14.15.3
- TypeScript 5.5.3
- Node.js 20.15.0 (Docker node:20-bullseye base image)
- Docker version 20.10.2, build 2291f61
- Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-169-generic x86_64)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions, MessageContent

**Comment by RedGuy12** [comment] 2024-07-23 12:10
Is this a duplicate of #1039

**Comment by JMTK** [comment] 2024-07-23 13:58
> Is this a duplicate of #10393?

Yeah it is, same issue. Can read more here: https://discord.com/channels/222078108977594368/1248260322163294238

**Closed** 2024-07-23 14:06 UTC
Labels: duplicate
