### ISSUE TITLE
Audio playing gets stuck when playing from URL after playing from readable causing FFMPEG memory leak

### ISSUE THREAD

**Issue by dzlandis** [discordjs/discord.js#9665] opened 2023-06-24 02:47 UTC
### Which package is this bug report for?

voice

### Issue description

- Have bot join a voice channel
- Have bot play something in a voice channel making sure the audio resource is a Readable Stream
- Wait for it to finish playing
- Have bot play something in a voice channel now having the audio resource be a URL
- Observe that nothing plays, no error is omitted from the player, and the ffmpeg instance is stuck (you can check via task manager if running with PM2) increasing the memory (and causing a memory leak) every time you try to play via the URL audio resource.

Workaround:
- Use either only Readable streams or only URL's for audio resources across your whole bot.

Memory leak can look like this:
![r0yEDZIe85](https://github.com/discordjs/discord.js/assets/49926644/12d6ca3e-eb7f-4e5f-8f4f-61519f03c858)
![4czHSjeC5E](https://github.com/discordjs/discord.js/assets/49926644/f56d65f9-94c0-40b5-86ac-2d2c39947a7f)

This should be a high priority issue for the following reasons:
- It causes a memory leak
- It breaks core parts of the voice package making certain features unusable

### Code sample

```typescript
const isReadable = true; // set to true or false for testing
const voiceChannel = interaction.member.voice?.channel;
const connection = joinVoiceChannel({
      channelId: voiceChannel.id,
      guildId: interaction.guild.id,
      adapterCreator: interaction.guild.voiceAdapterCreator,
      selfDeaf: false
    });
    await entersState(connection, VoiceConnectionStatus.Ready, 30e3);

const res = await fetch(
      'https://cdn.discordapp.com/attachments/846596253244456960/1121989684768296990/mixkit-cartoon-clarinet-suspense-742.wav'
    );
    if (res.ok && isReadable) {
      const player = createAudioPlayer();
      player.on('error', error => {
        console.log(error);
      });
      connection.subscribe(player);
      const audio = Readable.fromWeb(res.body as ReadableStream<any>); // remove types if not using TS
      const resource = createAudioResource(audio);
      player.play(resource);
    } else if (!isReadable) {
       const player = createAudioPlayer();
      player.on('error', error => {
        console.log(error);
      });
      connection.subscribe(player);
      const resource = createAudioResource('https://cdn.discordapp.com/attachments/846596253244456960/1121989684768296990/mixkit-cartoon-clarinet-suspense-742.wav');
      player.play(resource);
    }
```

### Versions

discord.js v14.11.0
nodejs v18.15.0

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment] 2023-08-11 18:50
Duplicate of #7232.

**Closed by Jiralite** 2023-08-11 18:50 UTC
Labels: bug, need repro, packages:voice
