### ISSUE TITLE
Problem with channel name change promise

### ISSUE THREAD

**Issue by keybraker** [discordjs/discord.js#4331] opened 2020-06-01 16:29 UTC
https://github.com/discordjs/discord.js/blob/b441469044d46cee0c0d77a0303931bc88f6fee9/src/structures/GuildChannel.js#L342

I am updating the name of the channel on presence change and the promise is only returned when the setName or edit({ name... is the same as the previous name.

Recreation:
I create a channel, with lets say name **something** ->
than I play music on spotify so my state changes -> 
the bot that renames the channel to **something, spotify** -> 
and than I stop the musci from spotify so my state changes again->
the bot executes setName command to rename the channel to **something** ->
_but the promise is never returned_ ->
**If I repeate the process the promise is only returned when the new and old name match.**

**Comment by anandre** [comment] 2020-06-01 16:41
Duplicate of #4327 #4330  please see the comments there for more information.

**Closed** 2020-06-01 16:47 UTC
