### ISSUE TITLE
Missing data from broadcastEval result

### ISSUE THREAD

**Issue by aziznatour** [discordjs/discord.js#3144] opened 2019-03-12 23:01 UTC
**Please describe the problem you are having in as much detail as possible:**

I'm trying to retrieve the cached data of a specific guild which is on an unknown/different shard

**Include a reproducible code sample here, if possible:**
```js

message.client.shard.broadcastEval(`this.guilds.has('${message.guild.id}') ? this.guilds.get('${message.guild.id}') : false`).then(console.log).catch(console.error);

```

**Expected result:** data identical to what `message.guild` would give (with full channels, roles, members etc)

**Result:** I'm getting a basic guild object with minimal information, roles and channels are empty objects

![screenshot](https://user-images.githubusercontent.com/8480865/54241926-5a281f80-452b-11e9-97c5-5f4936a92ae7.png)

**Further details:**
- discord.js version: 11.4.2 (stable)
- Node.js version: v8.9.4
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by tipakA** [comment] 2019-03-13 01:32
You cannot retrieve objects using broadcastEval.
Returned data is JSON.parse'd and then JSON.stringify'ed, so all circular references are gone. This is mentioned in official guide on that topic [here](https://discordjs.guide/sharding/)

**Comment by aziznatour** [comment] 2019-03-13 09:00
I see. In that case I'd have to create a custom converter that produces a simple decycled object

**Comment by appellation** [comment] 2019-03-13 16:10
On the development branch, all Discord.js objects are JSON serializable. Unfortunately, that change won't land until v12.

**Comment by SpaceEEC** [comment] 2019-04-17 19:35
This is a duplicate of #3100 
A bit further explanation, if interested, can be found there too: https://github.com/discordjs/discord.js/issues/3100#issuecomment-465129465
(Essentially the solution is, as already concluded, to create your own "serializer")

**Closed by SpaceEEC** 2019-04-17 19:35 UTC
Labels: s: duplicate
