### ISSUE TITLE
createMessageComponentCollector does not work for type InteractionResponse

### ISSUE THREAD

**Issue by Gusarovv** [discordjs/discord.js#8851] opened 2022-11-21 12:28 UTC
### Which package is this bug report for?

discord.js

### Issue description

`.createMessageComponentCollector` does not work for type `InteractionResponse`

Is this a bug, or an error in the documentation?
https://discord.js.org/#/docs/discord.js/main/class/InteractionResponse?scrollTo=createMessageComponentCollector

### Code sample

```typescript
// type InteractionResponse
    const infoMsg = await interaction.reply({
        embeds: [await getMainEmbed()],
        components: [getButtons()],
        ephemeral: true,
    });
        // not work
    const collectorBtn = infoMsg.createMessageComponentCollector({
        time: COLLECTOR_TIME,
        componentType: ComponentType.Button,
    });

---

    // type Message
    const infoMsg = await interaction.editReply({
        embeds: [await getMainEmbed()],
        components: [getButtons()],
        ephemeral: true,
    });
        // Works
    const collectorBtn = infoMsg.createMessageComponentCollector({
        time: COLLECTOR_TIME,
        componentType: ComponentType.Button,
    });
```

### Package version

14.6.0

### Node.js version

18.12.1

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by imranbarbhuiya** [comment] 2022-11-21 12:30
Duplicate of #7992

**Closed** 2022-11-21 12:32 UTC
Labels: duplicate, packages:discord.js
