### ISSUE TITLE
PermissionOverwites stays the same in Client#channelUpdate

### ISSUE THREAD

**Issue by Jarco-dev** [discordjs/discord.js#6091] opened 2021-07-10 13:55 UTC
**Please describe the problem you are having in as much detail as possible:**
When listening to the channelUpdate event and  comparing the permissionOverwrites.cache from the old and new channel
they're exactly the same when editing permission overwrites in a guild channel
adding or removing a role/member is the most obvious way to see this with the code included below

**Include a reproducible code sample here, if possible:**

```js
const Discord = require("discord.js");
const client = new Discord.Client({
    intents: [
        Discord.Intents.FLAGS.GUILDS
    ]
});

client.on("ready", () => {
    console.log(`${client.user.tag} logged in`);
});

client.on("channelUpdate", (oldChannel, newChannel) => {
    console.log("\n", oldChannel.permissionOverwrites.cache, newChannel.permissionOverwrites.cache, "\n");
});

console.log("Logging in...");
client.login("BOT TOKEN HERE");
```

**Further details:**

- discord.js version: v13
- Node.js version: v14.16.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
medium, not many people use it but it's still rather annoying for the ones who do

**Relevant client options:**

- partials: none
- gateway intents: GUILDS
- other: none

- I have also tested the issue on latest master, commit hash: `discord.js@13.0.0-dev.d6c43a5.1625918569`

**Comment by almostSouji** [comment] 2021-07-10 14:26
duplicate of https://github.com/discordjs/discord.js/issues/6082 fixed in https://github.com/discordjs/discord.js/commit/f72ce7c136cf2dfe31a67b190c00e30ba7d70bfa

**Closed by almostSouji** 2021-07-10 14:26 UTC
Labels: s: already fixed, s: duplicate, type: bug
