### ISSUE TITLE
Discord making too many long-lasting TCP connections

### ISSUE THREAD

**Issue by nzhammer** [discordjs/discord.js#2449] opened 2018-04-05 20:58 UTC
**Please describe the problem you are having in as much detail as possible:**

When using channels.get(CHANNEL_ID).send(), I am noticing that my program makes a new TCP connection each time and that the TCP connection stays open for a very long time (maybe 3-5 minutes?).  The first .send() makes three TCP connections, and each subsequent .send() creates one additional TCP connection. This means that if I were to hypothetically send 47 messages to a channel in 3 minutes, I will have 50 TCP connections open.

My theory is that this is causing ESOCKETTIMEDOUT and ETIMEDOUT errors due to far too many TCP connections being opened, which is blocking I/O for my entire program and causing many issues. I am testing with a script that runs netstat every 5 seconds while my program runs and filtering on my node program's PID. At times when I have a higher number of .sends() being called, the TCP connections jump up and I often see ESOCKETTIMEDOUT errors.

I do not understand why there is a new TCP connection for each .send() to the same channel and why they hang around for so long. Is there some way to kill the connection once the message has been acknowledged as delivered or can I use just one TCP connections for all sends to the same channel? Should I be doing this in a different way?

**Include a reproducible code sample here, if possible:**

An example of my code to reproduce the issue:
```js

var client = new Discord.Client();
channels = client.channels;
client.login(Config.LOGIN_TOKEN)
	.then(result => {
		var channel = channels.get(CHANNEL_ID);
                setInterval(function() {
                   channel.send('some message');
                }, 2000);
	})

```

**Further details:**

- discord.js version: 11.3.0
- node.js version: v8.9.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: It's preventing me from being able to use Discord in my application. Often causes errors to be thrown if I do use Discord.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment] 2018-04-05 23:18
we try to use the same tcp connection for multiple requests, its quite interesting that you're coming across this issue. the request library we use is snekfetch, see if you can reproduce the issue with bare snekfetch and then post an issue on its repo at https://github.com/devsnek/snekfetch

**Comment by nzhammer** [comment] 2018-04-06 18:31
@devsnek Thanks for the response. Using the code below, there was a TCP connection being created per request.

```js
const snekfetch = require('snekfetch');

const getRequest = snekfetch['get']('https://discordapp.com/api/v7/gateway');
getRequest.set('Authorization', <key>);
getRequest.set('User-Agent', '<name> (https://github.com/hydrabolt/discord.js, 11.3.0) Node.js/v8.9.2');

var x = 0;
setInterval(function() {

	const postRequest = snekfetch['post']('https://discordapp.com/api/v7/channels/<id>/messages');
	postRequest.set('Authorization', '<auth name> <key>');
	postRequest.set('User-Agent', '<name> (https://github.com/hydrabolt/discord.js, 11.3.0) Node.js/v8.9.2');

	x += 1;
	getRequest.send()
		.then(function() {
			var message = "hi " + x;
			postRequest.send({
				"content": message
			})
			.then(res => {
				console.log(res);
				console.log('post done');
			})
			.catch(err => {
				console.log(err);
			});
		});

}, 3000);

```
What I don't understand is that I was required to recreate my postRequest in the setInterval so that a new postRequest would be created every 3 seconds.  If i took the chunk of code that builds up the postRequest and moved it before the interval, only one message would be displayed on my Discord client and for each subsequent attempt res would be undefined. I am brand new to the Discord library and snekfetch, but could this be the cause of multiple TCP connections being created? I would think that if I was able to re-use the postRequest, it might use the same TCP connection, but because I am building a new postRequest over and over, it may be using a different TCP connection?

I am assuming that it is the Discord servers that are sending 'undefined' as the response when re-using the same postRequest and that it has nothing to do with snekfetch, but maybe I am wrong there.

**Comment by devsnek** [comment] 2018-04-06 18:39
@nzhammer try uh
```js
const request = require('snekfetch');
const { Agent } = require('https');

const agent = new Agent({ keepAlive: true });

setInterval(() => {
  request.get('https://discordapp.com/api/v7/gateway', { agent }).end();
}, 300)

**Comment by nzhammer** [comment] 2018-04-06 18:48
Ah, in that case it's just one TCP connection open the whole time.

**Comment by nzhammer** [comment] 2018-04-06 19:11
@devsnek 
Ok, I get what you're saying. I reformatted my POST in the following way in setInterval and there's only 1 TCP connection for all requests!

```js

snekfetch.post('https://discordapp.com/api/v7/channels/<channel>/messages', {
        agent: agent,
	data: {
	    content: 'hello'
	},
	headers: {
		'Authorization': 'Bot <key>',
		'User-Agent': 'DiscordBot (https://github.com/hydrabolt/discord.js, 11.3.0) Node.js/v8.9.2'
	}

})

```

The problem is, this doesn't seem to be how the Discord code is formatting it, which may be the root of the issue. If you check APIRequest.js, it's more how I structured it above and it makes a new request for each .send() call.

**Comment by nzhammer** [comment] 2018-04-12 20:42
Hate to bump, but are there any updates on this issue? I'm using raw snekfetch for now, but it's not ideal to have to implement my own discord node library with rate limiting etc when one already exists. It seems like a pretty severe issue that anyone who is making 50 requests to discord in 5 minutes will have 50 TCP connections open.

**Comment by iCrawl** [comment] 2018-04-27 08:09
Snekfetch v4 was blocked due to nodes v10 release.

If you still want to go ahead and test this out, you can install the v4 branch here:
`npm i discordjs/discord.js#dependabot/npm_and_yarn/snekfetch-tw-4.0.0`

**Comment by amishshah** [comment] 2018-08-10 10:03
Now that we use `node-fetch` this should be fixed on the master branch

**Closed** 2018-08-26 18:34 UTC
Labels: meta: dependencies, s: fixed on master
