### ISSUE TITLE
 websocket issue

### ISSUE THREAD

**Issue by pasindu20** [discordjs/discord.js#8160] opened 2022-06-23 10:06 UTC
### Which package is this bug report for?

discord.js

### Issue description

currently my bot having websocket issue some shard not reconnecting i test commands in another server it working fine but some shard not reconnecting 

### Package version

13.8

### Node.js version

16.15.1

### Operating system

debian 11

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Zeptar1069** [comment] 2022-06-23 21:48
The 'Code sample' label is not given, could you try to find which part of the bot is not working?

**Comment by almeidx** [comment] 2022-06-23 21:50
Most likely fixed in #8082. Try updating to 13.8.1

**Comment by iCrawl** [comment] 2022-07-03 13:45
Duplicate of #8199

**Closed by iCrawl** 2022-07-03 13:45 UTC
Labels: bug, need repro, packages:discord.js
