### ISSUE TITLE
Only messages are allowed to create polls

### ISSUE THREAD

**Issue by JuanPablo2655** [discordjs/discord.js#10288] opened 2024-05-20 04:48 UTC
### Which package is this bug report for?

discord.js

### Issue description

I tried to create a poll through interactions but I found out that I can only do it through a message object
<img width="608" alt="Screenshot 2024-05-20 at 12 43 41 AM" src="https://github.com/discordjs/discord.js/assets/34992574/75f7571a-c5af-4cfe-90f6-72c9047f2b36">

### Code sample

```typescript
await interaction.followUp({
			poll: {
				question: { text: "some text here" },
				answers: [{ text: 'Aye' }, { text: 'Nay' }],
				duration: 1,
				allowMultiselect: false,
			},
		});
```
This should error out

### Versions

- discord.js 14.15.2
- nodejs 20.13.1
- typescript 5.4.5
- macOS 14.5

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment] 2024-05-20 06:24
Duplicate of #10258.

**Closed by Jiralite** 2024-05-20 06:24 UTC
Labels: bug, need repro, packages:discord.js
