### ISSUE TITLE
"Setting up ESLint rules" is outdated

### ISSUE THREAD

**Issue by ikelax** [discordjs/discord.js#10494] opened 2024-09-08 09:31 UTC
### Which application is this bug report for?

Guide

### Issue description

The flat config file format has been the default configuration file format since ESLint v9.0.0. In the guide, which is really helpful and well-written by the way, the configuration is still described for the deprecated eslintrc format.

Therefore, this section should be updated or at least it should be mentioned that the eslintrc format has to be enabled since v9.0.0 by setting `ESLINT_USE_FLAT_CONFIG` environment variable to `false` [(see here)](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated).

### Steps to Reproduce

1. Visit [Setting up ESLInt rules](https://discordjs.guide/preparations/setting-up-a-linter.html#setting-up-eslint-rules) in the guide.
2. Read the section.

### Versions

- Mozilla Firefox 129.0.2
- macOS Sonoma 14.6.1

### Issue priority

Low (slightly annoying)

**Comment by ikelax** [comment] 2024-09-08 09:32
I would like to work on this.

**Comment by Jiralite** [comment] 2024-09-08 09:40
Duplicate of https://github.com/discordjs/guide/issues/1568.

**Closed by Jiralite** 2024-09-08 09:40 UTC
Labels: bug, need repro, apps:guide
