### ISSUE TITLE
Users are reseting to 0 | presence status bug

### ISSUE THREAD

**Issue by iiCrIzPy** [discordjs/discord.js#4951] opened 2020-10-28 22:01 UTC
Hello,
i'm using discord.js version 12
So my bot was at 40k users,
today it just came back to 10 and it was happening to me before this

Also My bot see all users presence status as offline.
i wish u find a solution for that

All hopes, Regards.

**Comment by monbrey** [comment] 2020-10-28 22:02
Events for privileged intents are not sent if not enabled:
• Discords FAQ on this change: https://dis.gd/gwupdate
• your bot is verified? https://dis.gd/contact (and tell them which privileged intents you need and why)
• your bot is not verified? toggle the switches in https://discord.com/developers/applications (image)
• you do not need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: update to v12, we no longer support v11.

**Comment by iiCrIzPy** [comment] 2020-10-28 22:04
> Events for privileged intents are not sent if not enabled:
> • Discords FAQ on this change: https://dis.gd/gwupdate
> • your bot is verified? https://dis.gd/contact (and tell them which privileged intents you need and why)
> • your bot is not verified? toggle the switches in https://discord.com/developers/applications (image)
> • you do not need to provide intents in client options, discord sends all events if no intents are provided.
> • If you are on v11 and experience issues: update to v12, we no longer support v11.

What do you mean?
i have a verified bot and an unverified bot, both of them are having same issues

**Comment by SpaceEEC** [comment] 2020-10-28 22:04
Duplicate of #4950, #4949, #4948, #4946, #4941, and #4940.

**Closed by SpaceEEC** 2020-10-28 22:04 UTC
Labels: s: duplicate
