### ISSUE TITLE
DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by KitsuneCode** [discordjs/discord.js#5875] opened 2021-06-18 18:08 UTC
Hello, today I had a problem, and it is that I am using the `discord.js-menu` library, but the problem arose in that it had never happened to me before using this library, what happens is that this library creates a menu using reactions , and well it always worked for me until today when I went to test it and the message was not updated because it threw me this error:

```
(node:2122) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/runner/KitsunityApp/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/KitsunityApp/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:2122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 0)
```
I already checked and the problem is not the library since it has always worked for me and the code never be mdified before this error appears, so I think it is a problem of the `discord.js`, the point is that I need help since the library that I use does not work well because of this error.

**Further details:**

- discord.js version: Lastest
- Node.js version: 12.16.1
- Operating system: Linux (on repl.it workspace)
- Priority this issue should have - please be realistic and elaborate if possible: Very high, the library I use depends on that function

**Comment by SpaceEEC** [comment] 2021-06-18 18:15
This is probably caused by #5758 and needs to be addressed by [`discord.js-menu`](https://github.com/jowsey/discord.js-menu), which is not maintained by us.

**Closed by SpaceEEC** 2021-06-18 18:15 UTC
Labels: s: unverified, type: bug
