### ISSUE TITLE
Missing encryption package even if packages are correctly installed

### ISSUE THREAD

**Issue by Fuzzy2319** [discordjs/discord.js#8745] opened 2022-10-13 12:55 UTC
### Which package is this bug report for?

voice

### Issue description

1. open a voice connection
2. try to play an audio ressource
3. see the error 

Error: Cannot play audio as no valid encryption package is installed.
- Install sodium, libsodium-wrappers, or tweetnacl.
- Use the generateDependencyReport() function for more information.

    at Object.fallbackError (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:166:9)
    at Networking.encryptOpusPacket (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:663:17)
    at Networking.createAudioPacket (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:653:50)
    at Networking.prepareAudioPacket (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:599:33)
    at VoiceConnection.prepareAudioPacket (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:1412:29)
    at AudioPlayer._preparePacket (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:981:18)
    at AudioPlayer._stepPrepare (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:962:14)
    at prepareNextAudioFrame (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:87:29)
    at audioCycleStep (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:76:3)
    at Timeout._onTimeout (file:///D:/Users/user/Documents/Bot/node_modules/@discordjs/voice/dist/index.mjs:83:45)

### Package version

discord.js@14.6.0 @discordjs/opus@0.8.0 ffmpeg-static@5.1.0 libsodium-wrappers@0.7.10 @discordjs/voice@0.13.0

### Node.js version

v16.17.1

### Operating system

windows 10 and ubuntu 22.04 server

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by InfiniteMarcus** [comment] 2022-10-17 03:05
I'm facing the same issue, even with Node V17 in Heroku

**Comment by abaza738** [comment] 2022-10-17 16:34
I can confirm the same issue is present with 2 of the suggested 3 packages installed already (`libsodium-wrappers` and `tweetnacl`).

**Comment by InfiniteMarcus** [comment] 2022-10-18 20:47
> Have you tried https://github.com/sodium-friends/sodium-native as that seems to work for me. It is listed in the README: https://github.com/discordjs/discord.js/blob/main/packages/voice/README.md

Tried but not worked :(

**Comment by abaza738** [comment] 2022-10-18 20:51
It did not work for either.

**Comment by MrGcGamer** [comment] 2022-10-27 18:12
Same issue here (on MacOS)

**Comment by PapiOphidian** [comment] 2022-10-31 08:29
For clarification, all of the packages cannot be found except for the main library (obviously) and ffmpeg. All of the others display as not found regardless of installation status

**Comment by Jiralite** [comment] 2022-10-31 12:21
Duplicate of #8740.

**Closed by Jiralite** 2022-10-31 12:21 UTC
Labels: bug, packages:voice
