### ISSUE TITLE
Bot is crashing on button click interaction

### ISSUE THREAD

**Issue by kodenamekrak** [discordjs/discord.js#9324] opened 2023-04-03 18:26 UTC
### Which package is this bug report for?

discord.js

### Issue description

When interacting with a button, the bot is crashing immediately with the error below

```
/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/actions/InteractionCreate.js:50
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
    at module.exports [as INTERACTION_CREATE] (/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/kodenamekrak/node/discord/krakbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/kodenamekrak/node/discord/krakbot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/kodenamekrak/node/discord/krakbot/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/kodenamekrak/node/discord/krakbot/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)```

### Code sample

```typescript
const { SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('test')
		.setDescription('test'),
	async execute(interaction) {
        const row = new ActionRowBuilder()
            .addComponents(
                new ButtonBuilder()
                .setLabel('Info')
                .setStyle(ButtonStyle.Success)
                .setCustomId(`testbutton`)
            );
		await interaction.reply({ components: [row]});
	}
};
```

### Package version

14.7.1

### Node.js version

18.7.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages

**Comment by Jiralite** [comment] 2023-04-03 18:28
Duplicate of #9295.

**Closed by Jiralite** 2023-04-03 18:28 UTC
Labels: bug, need repro, packages:discord.js
