### ISSUE TITLE
RequestAbortedError [AbortError]: Request aborted

### ISSUE THREAD

**Issue by qiaokeli111** [discordjs/discord.js#9484] opened 2023-05-01 04:03 UTC
### Which package is this bug report for?

discord.js

### Issue description

D:\czj\web3\learn\node_modules_undici@[5.21.2@undici](mailto:5.21.2@undici)\lib\api\abort-signal.js:10
self.onError(new RequestAbortedError())
^

RequestAbortedError [AbortError]: Request aborted
at abort (D:\czj\web3\learn\node_modules_undici@[5.21.2@undici](mailto:5.21.2@undici)\lib\api\abort-signal.js:10:18)
at AbortSignal.self. (D:\czj\web3\learn\node_modules_undici@[5.21.2@undici](mailto:5.21.2@undici)\lib\api\abort-signal.js:29:5)
at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
at abortSignal (node:internal/abort_controller:292:10)
at AbortController.abort (node:internal/abort_controller:323:5)
at Timeout. (D:\czj\web3\learn\node_modules_https://github.com/discordjs_rest@1.7.0@@discordjs\rest\dist\index.js:589:71)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7) {
code: 'UND_ERR_ABORTED'
}

### Code sample

```typescript
const { Client, Events, GatewayIntentBits,REST, Routes } = require('discord.js');

const client = new Client({ intents: [
GatewayIntentBits.Guilds,
GatewayIntentBits.MessageContent,
GatewayIntentBits.GuildMessages
]
});

client.on('ready', () => {
console.log(Logged in as ${client.user.tag}!);
});

client.login('MTEwMjE2OTQ4OTI5MTg3MDI0MA.Gs-eiH.Gim7ZM2ConA9q7X-0G6UbwXqtFIFdTszFgYIJY');
```

### Versions

node v16.18.0 "discord.io": "^2.5.3",  win10

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by kyranet** [comment] 2023-05-01 08:26
1. You're not using [`discord.io`](https://www.npmjs.com/package/discord.io), you're using Discord.js.
1. You shouldn't post your token online.
1. `AbortError` means that your request is taking more than 15 seconds (by [default](https://discord.js.org/docs/packages/rest/main/RESTOptions:Interface#timeout)) to go through, this can be because your connection is too slow.
1. This is a duplicate of many other issues, please check existing issues before creating a new one!

**Closed by kyranet** 2023-05-01 08:26 UTC
Labels: bug, need repro, packages:discord.js
