### ISSUE TITLE
Voice: connection timeout after 15 seconds.

### ISSUE THREAD

**Issue by Texlo-Dev** [discordjs/discord.js#2979] opened 2018-12-01 17:34 UTC
**Please describe the problem you are having in as much detail as possible:**
When attempting to play a YTDL stream in a voice channel, there seems to an issue with the connection timeout.

```
 { Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
0|mrFox  |     at VoiceConnection.authenticateFailed (/home/rich/Fox/node_modules/discord.js/src/client/voice/VoiceConnection.js:268:27)
0|mrFox  |     at connectTimeout.client.setTimeout (/home/rich/Fox/node_modules/discord.js/src/client/voice/VoiceConnection.js:297:18)
0|mrFox  |     at Timeout.setTimeout (/home/rich/Fox/node_modules/discord.js/src/client/BaseClient.js:81:7)
0|mrFox  |     at ontimeout (timers.js:436:11)
0|mrFox  |     at tryOnTimeout (timers.js:300:5)
0|mrFox  |     at listOnTimeout (timers.js:263:5)
0|mrFox  |     at Timer.processTimers (timers.js:223:10) [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT' }
```

I am not sure why this is happening, as music worked server weeks ago, with no code change, only an upgrade in discord.js version.

**Include a reproducible code sample here, if possible:**
```js
const dispatcher: StreamDispatcher = serverQueue.connection.play(
      ytdl(song.url, { filter: "audioonly" }),
      { bitrate: "auto" }
    );

```

The bot can join, but will error here.

**Further details:**
- discord.js version: 12..0.0-dev lastest commit
- Node.js version: 10.14.1
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium, as I cannot serve streams at all.

- [ x] I have also tested the issue on latest master, commit hash:

**Comment by makos** [comment] 2018-12-04 12:51
I will try to work on this issue as a volunteer.

**Comment by makos** [comment] 2018-12-05 08:35
[Gist with test bot code I used to try to reproduce the error](https://gist.github.com/makos/de827e410cc53ac0ad5ee5965c3b2c79)

I am unable to reproduce your error with above code. Are you doing something differently? Is it maybe an issue with the server you're running your bot from?

**Comment by RTK99** [comment] 2018-12-05 15:15
I originally thought so. However, after trying many different servers, the
issue still persists.

**Comment by DougTy** [comment] 2018-12-12 04:47
Been getting this a lot the past couple days. Doesn't always happen, only about half the time for me.
On latest commit, node 10.14.1, Debian Stretch.

**Comment by makos** [comment] 2018-12-12 12:34
I would try running your bot with the `DEBUG=*` option, like so:
````shell
DEBUG=* node bot.js
````
and posting the related output when it crashes again.

**Comment by DougTy** [comment] 2018-12-16 05:00
I'll give it a look out for when it happens next, but it's not a crash -- it's a promise rejection from `VoiceChannel.join()` with the error `"Connection not established within 15 seconds."` I'm pretty sure the call stack in the OP is the best output we'll get for this.

**Comment by Xzandro** [comment] 2019-01-24 16:49
I also have this issue occasionally.
Ubuntu 18.04.1 LTS
Discord.js version: master branch

I made a small custom soundboard and it seems like that it happens if no one was active in voice for a few hours. After a few tries / restarting the bot it fixes itself at some point. I know, not the best description to reproduce all of this, but I try to give more information if this issue persist.

**Comment by amishshah** [comment] 2019-02-10 20:24
Could you update to the latest commit (https://github.com/discordjs/discord.js/commit/aab3523fb5b60d21d20cbf2be01c32bdf21aa8ae) and try the following to produce some more debug information:

```js
client.on('debug', console.log);
```

You should see output something like this:
![image](https://user-images.githubusercontent.com/10330923/52539029-83f5f700-2d71-11e9-8381-939bf812de35.png)

If you could try this again and send me the full output from this log -- this will contain sensitive information so I'd recommend messaging me on Discord at hydrabolt#0001. However, you should still be ok to post the details here on GitHub if you remove your IP address from the logs and partially redact any IDs.

**Comment by amishshah** [comment] 2019-02-11 21:07
Ok, I've spoken to 2 users about the issue. After some restructuring of voice internals we were manage to fix one of the issues (see commit 375706beac3219ae20885681112289bb2e0c6604) relating to event listeners being cleared that prevented Discord.js from connecting to the voice servers.

The other issue was that a user was hosting on Hetzner, which still seems to be blacklisted by Discord so we're unable to do anything about that ourselves - please bear this in mind if you're looking for servers to host your bot on!

After the work done, I'm pretty confident that the issue is fixed as much as it could be, if it still occurs it must be a network issue. If the issue does occur, please gather debug logs by listening to the `debug` event, e.g. `client.on('debug', console.log)` and then ask about it in the Discord.js server (**make sure to redact any private information from the logs**) or post an issue here. However, I'm closing this issue for now as if the issue still continues I'm pretty sure it's just a problem with your network.

**Closed by amishshah** 2019-02-11 21:07 UTC
Labels: p: medium, t: voice, type: bug

**Comment by IF64** [comment] 2020-04-25 21:42
I now have this issue. I host using Heroku but  I test locally before pushing any commits

**Comment by PoProstuMieciek** [comment] 2020-09-12 21:41
Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
Error:
```
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
```
Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
And sometimes EVEN ` msg.member.voice.channel == null `

I tried regenerating bot token and everything... please help

**Comment by PoProstuMieciek** [comment] 2020-09-13 09:39
> Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
> Error:
> 
> ```
> Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> ```
> 
> Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
> And sometimes EVEN `msg.member.voice.channel == null`
> 
> I tried regenerating bot token and everything... please help
> 
> Discord.js v.12.3.1

Here are logs after adding ` client.on('debug', console.debug); ` line:
```
[VOICE ({{here was guild id}}:2)]: Sending voice state update: {"guild_id":"{{here was guild id}}","channel_id":"{{here was channel id}}","self_mute":false,"self_deaf":false}
[VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"{{here was token}}","guild_id":"{{here was guild id}}","endpoint":"eu-central5499.discord.media:80"}}
[VOICE] voiceServer guild: {{here was guild id}} token: {{here was token}} endpoint: eu-central5499.discord.media:80
[VOICE ({{here was guild id}}:2)]: Token "{{here was token}}" and endpoint "eu-central5499.discord.media:80"
[VOICE ({{here was guild id}}:2)]: Endpoint resolved as eu-central5499.discord.media
[VOICE ({{here was guild id}}:2)]: Authenticated with sessionID undefined
[VOICE ({{here was guild id}}:2)]: Authenticate failed - VOICE_CONNECTION_TIMEOUT
[ERROR] (node:3779) UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
    at /home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
    at Timeout.<anonymous> (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[ERROR] (node:3779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[ERROR] (node:3779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I replaced all informations that I am not comfortable sharing with.

**Comment by Dyl3105** [comment] 2021-01-12 14:45
> > Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
> > Error:
> > ```
> > Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > ```
> > 
> > 
> > Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
> > And sometimes EVEN `msg.member.voice.channel == null`
> > I tried regenerating bot token and everything... please help
> > Discord.js v.12.3.1
> 
> Here are logs after adding `client.on('debug', console.debug);` line:
> 
> ```
> [VOICE ({{here was guild id}}:2)]: Sending voice state update: {"guild_id":"{{here was guild id}}","channel_id":"{{here was channel id}}","self_mute":false,"self_deaf":false}
> [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"{{here was token}}","guild_id":"{{here was guild id}}","endpoint":"eu-central5499.discord.media:80"}}
> [VOICE] voiceServer guild: {{here was guild id}} token: {{here was token}} endpoint: eu-central5499.discord.media:80
> [VOICE ({{here was guild id}}:2)]: Token "{{here was token}}" and endpoint "eu-central5499.discord.media:80"
> [VOICE ({{here was guild id}}:2)]: Endpoint resolved as eu-central5499.discord.media
> [VOICE ({{here was guild id}}:2)]: Authenticated with sessionID undefined
> [VOICE ({{here was guild id}}:2)]: Authenticate failed - VOICE_CONNECTION_TIMEOUT
> [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
>     at VoiceConnection.authenticateFailed (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
>     at /home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
>     at Timeout.<anonymous> (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [ERROR] (node:3779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> I replaced all informations that I am not comfortable sharing with.

I have the exact same issue as the above code, anyone find a fix for this?

**Comment by maybepiffpuffas** [comment] 2021-01-20 11:17
> 
> 
> > > Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
> > > Error:
> > > ```
> > > Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > > ```
> > > 
> > > 
> > > Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
> > > And sometimes EVEN `msg.member.voice.channel == null`
> > > I tried regenerating bot token and everything... please help
> > > Discord.js v.12.3.1
> > 
> > 
> > Here are logs after adding `client.on('debug', console.debug);` line:
> > ```
> > [VOICE ({{here was guild id}}:2)]: Sending voice state update: {"guild_id":"{{here was guild id}}","channel_id":"{{here was channel id}}","self_mute":false,"self_deaf":false}
> > [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"{{here was token}}","guild_id":"{{here was guild id}}","endpoint":"eu-central5499.discord.media:80"}}
> > [VOICE] voiceServer guild: {{here was guild id}} token: {{here was token}} endpoint: eu-central5499.discord.media:80
> > [VOICE ({{here was guild id}}:2)]: Token "{{here was token}}" and endpoint "eu-central5499.discord.media:80"
> > [VOICE ({{here was guild id}}:2)]: Endpoint resolved as eu-central5499.discord.media
> > [VOICE ({{here was guild id}}:2)]: Authenticated with sessionID undefined
> > [VOICE ({{here was guild id}}:2)]: Authenticate failed - VOICE_CONNECTION_TIMEOUT
> > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> >     at VoiceConnection.authenticateFailed (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
> >     at /home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
> >     at Timeout.<anonymous> (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
> >     at listOnTimeout (internal/timers.js:549:17)
> >     at processTimers (internal/timers.js:492:7)
> > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > [ERROR] (node:3779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> > 
> > 
> > I replaced all informations that I am not comfortable sharing with.
> 
> I have the exact same issue as the above code, anyone find a fix for this?

Same, but for me it works on most of the servers, but on some it doesn't.

**Comment by DrewScatterday** [comment] 2021-01-22 05:36
Hello all, I don't have a fix but I'm also getting this same error. I wanted to add my code to this thread so someone can maybe point out a dumb error I've made in this code or if there are no errors then hopefully this code will help someone out there investigating fixing this issue. 

Here is the error message I receive, its the same error message `VOICE_CONNECTION_TIMEOUT` that others have described in this thread:
![image](https://user-images.githubusercontent.com/28267620/105449206-e0443f80-5c45-11eb-9d81-00e8e966f6dd.png)

This error occurs in multiple servers and consistently occurs every time. I'm currently running Node.js=14.15.3
Discord.js=12.5.1
Here is a small snippet of my code. This is a bot that does TTS using AWS sdk polly. I'm trying to write the bot so that if a user is a different voice channel than the bot, the bot will leave the current voice channel and join the user's current voice channel to speak/play audio. The discord music bot groovy is able to do this so I'm trying to have this feature in my code as well: 

```
function getTTS(msg, text) {
    var params = {
        OutputFormat: "mp3",
        Text: text,
        TextType: "text", 
        VoiceId: "Brian"
    };

    console.log("processing command:" + text);

    Polly.synthesizeSpeech(params, (err, data) => {
        if (err) {
            return err;
        }
        if (data.AudioStream instanceof Buffer) {
            // convert audiostream to buffer 
            var bufferStream = new Stream.PassThrough();
            bufferStream.end(data.AudioStream)
            playSound(msg, bufferStream);
        }
    });
}

function playSound(msg, buf) {
    var voiceChannel = msg.member.voice.channel;

    if (!voiceChannel) { // user not in a voice channel
        msg.reply("Please join a voice channel first!");
        return;
    }
    else if(msg.member.voice.channel != msg.guild.me.voice.channel) { // bot not in the same voice channel 
        msg.guild.me.voice.channel.leave();
        
        voiceChannel.join()
        .then(connection => {
            const dispatcher = connection.play(buf);

            dispatcher.on("finish", end => {
                console.log("Bot joined voice channel");

                // Leave voice channel after 5 minutes
                timeoutID = setTimeout(() => {
                    voiceChannel.leave();
                  }, 5 * 60 * 1000) 
            });

        }).catch(e => { 
            console.log("Error joining voice channel");
            console.log(e);
            msg.reply("Error joining voice channel. Please make sure I have the correct role permissions to join your voice channel.")
        });
    }
```

The error occurs everytime on this line here `const dispatcher = connection.play(buf);`
I confirmed that this not an issue with AWS sdk but changing this line to be a mp3 from a url: 
`const dispatcher = connection.play("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3");` 
and still the same error persists. 

The full repo can be seen here if you want to see the full source code of my bot. https://github.com/DrewScatterday/DiscordTTSBot/blob/master/main.js

Again maybe I'm just missing something in my code but if not hopefully this helps someone out investigating this issue 👍

**Comment by PoProstuMieciek** [comment] 2021-01-25 13:52
According to my experience with discord.js it happens only sometimes and goes away after a while. At this moment issue is not persisting. I did not change any code.

**Comment by Dyl3105** [comment] 2021-01-25 13:55
> According to my experience with discord.js it happens only sometimes and goes away after a while. At this moment issue is not persisting. I did not change any code.

I've seen this said a few times, however for myself the code never worked. My bot has always refused to join a Voice Channel, and I've done everything. Tried on different machines, different code, and waited weeks now. No change, and no solid solution either :/

**Comment by PoProstuMieciek** [comment] 2021-01-25 19:12
> > According to my experience with discord.js it happens only sometimes and goes away after a while. At this moment issue is not persisting. I did not change any code.
> 
> I've seen this said a few times, however for myself the code never worked. My bot has always refused to join a Voice Channel, and I've done everything. Tried on different machines, different code, and waited weeks now. No change, and no solid solution either :/

If there would be a solid solution then this issue thread wouldn't be open.
This error forced me to take a break from discord bots. When I came back, the issue was gone and no longer persists for me. I hope that solution would be found soon.

**Comment by Dyl3105** [comment] 2021-01-27 20:22
> > > According to my experience with discord.js it happens only sometimes and goes away after a while. At this moment issue is not persisting. I did not change any code.
> > 
> > 
> > I've seen this said a few times, however for myself the code never worked. My bot has always refused to join a Voice Channel, and I've done everything. Tried on different machines, different code, and waited weeks now. No change, and no solid solution either :/
> 
> If there is a solid solution then this issue thread wouldn't be open.
> This error forced me to take a break from discord bots. When I came back, the issue was gone and no longer persists for me. I hope that solution would be found soon.



> > > > Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
> > > > Error:
> > > > ```
> > > > Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > > > ```
> > > > 
> > > > 
> > > > Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
> > > > And sometimes EVEN `msg.member.voice.channel == null`
> > > > I tried regenerating bot token and everything... please help
> > > > Discord.js v.12.3.1
> > > 
> > > 
> > > Here are logs after adding `client.on('debug', console.debug);` line:
> > > ```
> > > [VOICE ({{here was guild id}}:2)]: Sending voice state update: {"guild_id":"{{here was guild id}}","channel_id":"{{here was channel id}}","self_mute":false,"self_deaf":false}
> > > [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"{{here was token}}","guild_id":"{{here was guild id}}","endpoint":"eu-central5499.discord.media:80"}}
> > > [VOICE] voiceServer guild: {{here was guild id}} token: {{here was token}} endpoint: eu-central5499.discord.media:80
> > > [VOICE ({{here was guild id}}:2)]: Token "{{here was token}}" and endpoint "eu-central5499.discord.media:80"
> > > [VOICE ({{here was guild id}}:2)]: Endpoint resolved as eu-central5499.discord.media
> > > [VOICE ({{here was guild id}}:2)]: Authenticated with sessionID undefined
> > > [VOICE ({{here was guild id}}:2)]: Authenticate failed - VOICE_CONNECTION_TIMEOUT
> > > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > >     at VoiceConnection.authenticateFailed (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
> > >     at /home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
> > >     at Timeout.<anonymous> (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
> > >     at listOnTimeout (internal/timers.js:549:17)
> > >     at processTimers (internal/timers.js:492:7)
> > > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > > [ERROR] (node:3779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > ```
> > > 
> > > 
> > > I replaced all informations that I am not comfortable sharing with.
> > 
> > 
> > I have the exact same issue as the above code, anyone find a fix for this?
> 
> Same, but for me it works on most of the servers, but on some it doesn't.

I actually found a solution that fixed the error completely for my circumstance. In my index.js file I have a list of gateway intents, and it was missing **GUILD_VOICE_STATES**. Once I added it in, the bot worked flawlessly for it's intended purpose.

Took me some time to realise this, and not too sure how I missed it the first few times over.

**Comment by TapsHTS** [comment] 2021-03-23 18:32
> > > > According to my experience with discord.js it happens only sometimes and goes away after a while. At this moment issue is not persisting. I did not change any code.
> > > 
> > > 
> > > I've seen this said a few times, however for myself the code never worked. My bot has always refused to join a Voice Channel, and I've done everything. Tried on different machines, different code, and waited weeks now. No change, and no solid solution either :/
> > 
> > 
> > If there is a solid solution then this issue thread wouldn't be open.
> > This error forced me to take a break from discord bots. When I came back, the issue was gone and no longer persists for me. I hope that solution would be found soon.
> 
> > > > > Hi, I have the same error every time I try to join the voice channel. Error occurs in every server. Once I was able to play music but only once. I don't know why it worked that one time.
> > > > > Error:
> > > > > ```
> > > > > Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > > > > ```
> > > > > 
> > > > > 
> > > > > Sometimes client is connecting to the voice and throwing error, sometimes does not even join.
> > > > > And sometimes EVEN `msg.member.voice.channel == null`
> > > > > I tried regenerating bot token and everything... please help
> > > > > Discord.js v.12.3.1
> > > > 
> > > > 
> > > > Here are logs after adding `client.on('debug', console.debug);` line:
> > > > ```
> > > > [VOICE ({{here was guild id}}:2)]: Sending voice state update: {"guild_id":"{{here was guild id}}","channel_id":"{{here was channel id}}","self_mute":false,"self_deaf":false}
> > > > [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"{{here was token}}","guild_id":"{{here was guild id}}","endpoint":"eu-central5499.discord.media:80"}}
> > > > [VOICE] voiceServer guild: {{here was guild id}} token: {{here was token}} endpoint: eu-central5499.discord.media:80
> > > > [VOICE ({{here was guild id}}:2)]: Token "{{here was token}}" and endpoint "eu-central5499.discord.media:80"
> > > > [VOICE ({{here was guild id}}:2)]: Endpoint resolved as eu-central5499.discord.media
> > > > [VOICE ({{here was guild id}}:2)]: Authenticated with sessionID undefined
> > > > [VOICE ({{here was guild id}}:2)]: Authenticate failed - VOICE_CONNECTION_TIMEOUT
> > > > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
> > > >     at VoiceConnection.authenticateFailed (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
> > > >     at /home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
> > > >     at Timeout.<anonymous> (/home/poprostumieciek/MieciekBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
> > > >     at listOnTimeout (internal/timers.js:549:17)
> > > >     at processTimers (internal/timers.js:492:7)
> > > > [ERROR] (node:3779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > > > [ERROR] (node:3779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > > ```
> > > > 
> > > > 
> > > > I replaced all informations that I am not comfortable sharing with.
> > > 
> > > 
> > > I have the exact same issue as the above code, anyone find a fix for this?
> > 
> > 
> > Same, but for me it works on most of the servers, but on some it doesn't.
> 
> I actually found a solution that fixed the error completely for my circumstance. In my index.js file I have a list of gateway intents, and it was missing **GUILD_VOICE_STATES**. Once I added it in, the bot worked flawlessly for it's intended purpose.
> 
> Took me some time to realise this, and not too sure how I missed it the first few times over.

For me that don't work ;( Help !

**Comment by hellomrjones** [comment] 2021-05-01 15:42
Same error. I have other bots running without a problem. There seems to be no fix sadly. Is this broken for good?

**Comment by Mxnuuel** [comment] 2021-05-31 13:22
I got the fix for you guys. Since Discord introduced Intents (can be read [here](https://discordjs.guide/popular-topics/intents.html#problems-in-version-12)

You need to add those intents to make the bot connect to the voice channel. After a lot of reading and pain i finally managed to make it work. If there are any question i'm here to help! :)

Example code can be found [here](https://github.com/Mxnuuel/helper/blob/main/discordmusic.js)

**Comment by BaziForYou** [comment] 2022-01-18 18:02
> I got the fix for you guys. Since Discord introduced Intents (can be read [here](https://discordjs.guide/popular-topics/intents.html#problems-in-version-12))
> 
> You need to add those intents to make the bot connect to the voice channel. After a lot of reading and pain i finally managed to make it work. If there are any question i'm here to help! :)
> 
> Example code can be found [here](https://github.com/Mxnuuel/helper/blob/main/discordmusic.js)

Example code is gone can you show me again?

**Comment by deadrepo** [comment] 2022-07-15 13:17
any answer to this?

**Comment by NotSoEvilDead** [comment] 2023-03-20 17:13
This error is occurring again as of the last 12 hours. No code changes. Was working perfectly 12 hours ago.

Bot has been getting the same bogus authentication error upon trying to join VC. Bot will correctly enter the voice room, but authentication timeout after 15 seconds because discord broke something on their end.

Please fix this immediately and stop pushing backend changes with no notification. Thanks.
