### ISSUE TITLE
Slash Commands Support

### ISSUE THREAD

**Issue by wonderlandpark** [discordjs/discord.js#5103] opened 2020-12-11 12:29 UTC
**Is your feature request related to a problem? Please describe.**
Slash commands will be added to the API at December 15th.

https://github.com/discord/discord-api-docs/pull/2295

**Describe the ideal solution**
Should support slash command to support new api updates

**Describe alternatives you've considered**
I think it should support Slash command gateway events and way to add slash commands for global or each guilds in discord.js

Working on #5448

**Comment by vladfrangu** [comment] 2020-12-11 12:43
Slash commands were *just* announced, and, as the PR you linked showed, they may still be WIP. The library will definitely have support for them in the future tho👀

**Comment by ChosenQuill** [comment] 2020-12-16 16:28
Documentation has been released on the developer docs!
[https://discord.com/developers/docs/interactions/slash-commands](https://discord.com/developers/docs/interactions/slash-commands)

**Comment by KevSlashNull** [comment] 2020-12-19 00:41
For anyone who wants to try this out using discord.js (the quick'n'dirty, non-production ready, warranty-free, and bad way! :wink:), you need to do the following, as of today with `^12.4.1`:

```js
const discordJsHandlers = require("discord.js/src/client/websocket/handlers/index");

discordJsHandlers.INTERACTION_CREATE = (_client, { d: packetData }) => {
  console.log(packetData.data);
  console.log(packetData.member);
  console.log(packetData.channel_id);
  console.log(packetData.guild_id);
};
```

If you have not already created a slash command, do it now.

For example, when executing the `/blep` command (e.g. `/blep animal:Dog`) command shown in the docs, the handler would print:

```js
{
  options: [ { value: 'animal_dog', name: 'animal' } ],
  name: 'blep',
  id: 'id of the command'
}
{
  user: {
    username: 'username',
    public_flags: 256,
    id: 'user snowflake',
    discriminator: '1234',
    avatar: 'avatar hash'
  },
  roles: [
    // a list of role snowflakes
  ],
  premium_since: null,
  permissions: 'the permissions',
  pending: false,
  nick: null,
  mute: false,
  joined_at: '2020-01-01T00:00:00.000000+00:00',
  is_pending: false,
  deaf: false
}
// the channel_id
// the guild_id
```

**Comment by AmoleR** [comment] 2020-12-23 18:50
As a person who just finished writing some things using Discord's API I can add a few comments on this (that are hard to find normally):

1. If you're interested in creating a slash command, at this point, you require to have your bot authenticated to the server with `application.commands` in addition to `bot`. In particular, I (believe) it may have to be manually removed and added to every server.
2. To create a (global) command, you can add this to your code:
```js
bot.api.applications(bot.user.id).commands.post({
  data: {
    name: "commandname",
    description: "Command Description",
  },
});
```
You can pass other options and things in the data (check the docs for this). Keep in mind that it's not possible to add spaces in the command name, so you want to use subcommands (or subcommand groups) for this. If you want to update a command, you can either post (as above) or use a patch request, such as:
```js
bot.api.applications(bot.user.id).commands(commandID).patch({
  data: {
    name: "commandname",
    description: "Command Description",
  },
});
```
To delete, you can just use `bot.api.applications(bot.user.id).commands(commandID).delete()`, and to get all of them, you can use `bot.api.applications(bot.user.id).commands.get()`.

Note that you can add a `.guilds(guildID)` after `applications(bot.user.id)` to deploy to a specific guild (which is instant). The above method will work within an hour.

To receive, you can create an interaction event:
```js
bot.ws.on("INTERACTION_CREATE", async interaction => {
  // Do stuff here - interaction is an InteractionResponse object. To get the name, use interaction.data.name
  // In particular, the values you passed to the interaction when creating it will be passed back here
});
```
To send a response to an interaction, you can use the following:
```js
bot.api.interactions(interaction.id, interaction.token).callback.post({
  data: {
    type: 3,
    data: {
      content: `I'm currently looking it up - it'll be directly messaged to you soon.`,
    },
  },
});
```
Note (this isn't well-documented as far as I know) that if you want an ephemeral message to be sent, you should add a flag of 64 (`1 << 6`) to whatever flags you send in the [message response](https://discord.com/developers/docs/resources/channel#message-object-message-structure). The documentation (should) have everything else there, and if you want, you can also send a regular channel message (get channel id by `interaction.channel_id`).

**Comment by almostSouji** [comment] 2020-12-23 18:56
please stop recommending people to use the undocumented, unsupported and private Client#api accessor in production bots.

 #5106 will add discord.js support for this, anything else does simply not belong on this repository, as they are increasingly hacky workaround and partial applications of that PR.

**Comment by KevSlashNull** [comment] 2020-12-24 00:11
@almostSouji, nobody suggested using that in production, I explicitly stated that my solution was intended for non-production test uses, so people don‘t need to set up a web socket with the Discord API. I also understood @AmoleR’s solution as temporary workaround (in non-production uses) but that’s up for debate. However, I fully agree with your point, which is why I’ve deleted my message. Looking forward to #5106!

**Comment by TehcJS** [comment] 2020-12-24 16:09
Nice! Looking forward to using this in production once it's in `stable`.

**Comment by edgycoder** [comment] 2021-01-11 00:53
> As a person who just finished writing some things using Discord's API I can add a few comments on this (that are hard to find normally):
> 
> 1. If you're interested in creating a slash command, at this point, you require to have your bot authenticated to the server with `application.commands` in addition to `bot`. In particular, I (believe) it may have to be manually removed and added to every server.
> 2. To create a (global) command, you can add this to your code:
> 
> ```js
> bot.api.applications(bot.user.id).commands.post({
>   data: {
>     name: "commandname",
>     description: "Command Description",
>   },
> });
> ```
> 
> You can pass other options and things in the data (check the docs for this). Keep in mind that it's not possible to add spaces in the command name, so you want to use subcommands (or subcommand groups) for this. If you want to update a command, you can either post (as above) or use a patch request, such as:
> 
> ```js
> bot.api.applications(bot.user.id).commands(commandID).patch({
>   data: {
>     name: "commandname",
>     description: "Command Description",
>   },
> });
> ```
> 
> To delete, you can just use `bot.api.applications(bot.user.id).commands(commandID).delete()`, and to get all of them, you can use `bot.api.applications(bot.user.id).commands.get()`.
> 
> Note that you can add a `.guilds(guildID)` after `applications(bot.user.id)` to deploy to a specific guild (which is instant). The above method will work within an hour.
> 
> To receive, you can create an interaction event:
> 
> ```js
> bot.ws.on("INTERACTION_CREATE", async interaction => {
>   // Do stuff here - interaction is an InteractionResponse object. To get the name, use interaction.data.name
>   // In particular, the values you passed to the interaction when creating it will be passed back here
> });
> ```
> 
> To send a response to an interaction, you can use the following:
> 
> ```js
> bot.api.interactions(interaction.id, interaction.token).callback.post({
>   data: {
>     type: 3,
>     data: {
>       content: `I'm currently looking it up - it'll be directly messaged to you soon.`,
>     },
>   },
> });
> ```
> 
> Note (this isn't well-documented as far as I know) that if you want an ephemeral message to be sent, you should add a flag of 64 (`1 << 6`) to whatever flags you send in the [message response](https://discord.com/developers/docs/resources/channel#message-object-message-structure). The documentation (should) have everything else there, and if you want, you can also send a regular channel message (get channel id by `interaction.channel_id`).
> 
> These things can (and should) be implemented in the official library (unless I'm using something which I shouldn't use).

Sadly using Typescript this is an issue!
`Argument of type '"INTERACTION_CREATE"' is not assignable to parameter of type 'WSEventType'`

**Comment by almostSouji** [comment] 2021-01-11 11:22
Again, this issue is used to track the completion of the feature and linked PR, not to support, supply, or discuss hacky workarounds prior to release.

**Comment by amiga-500** [comment] 2021-01-31 13:32
> ephemeral

For the life of me i cant figure out why this isnt working.  You sure it works. And to clear up confusion...when the calling it "ephemeral" is it exactly what it means: The message will disappear after a short amount of time?  And if so, then what is the amount of time?   

Is there a way to send a private response that ONLY the original /slash command requester sees it?

**Comment by almostSouji** [comment] 2021-01-31 13:38
> Is there a way to send a private response that ONLY the original /slash command requester sees it?

Precisely what ephemeral messages are. Flags on outgoing interaction responses are currently not documented and as said above slash commands are not yet fully released (discord calls it "public dev beta") and discord.js has not yet adopted them. This issue serves to track the feature, not to provide or receive support for using raw API requests.

**Comment by amiga-500** [comment] 2021-01-31 13:58
> 
> 
> > Is there a way to send a private response that ONLY the original /slash command requester sees it?
> 
> Precisely what ephemeral messages are. Flags on outgoing interaction responses are currently not documented and as said above slash commands are not yet fully released (discord calls it "public dev beta") and discord.js has not yet adopted them. This issue serves to track the feature, not to provide or receive support for using raw API requests.

Thanks for the quick reply.  I got it working but it seems to only work on interaction responses while only using the content parameter.  If one uses the embeds then the reply back ends up empty :( :(  Any work around for that so as to have ephemeral while showing embed content?

**Comment by almostSouji** [comment] 2021-01-31 14:00
no, embeds are not supported in ephemeral responses

**Comment by amiga-500** [comment] 2021-01-31 14:00
> 
> 
> no, embeds are not supported in ephemeral responses

Thanks again for the clarification.

**Comment by amiga-500** [comment] 2021-01-31 16:00
Quick question.  Is it possible to get back an interactive request when a user clicks a reaction found on a bot's message?  Or are the only interaction requests we get are from slash commands?

**Comment by seiyria** [comment] 2021-01-31 16:03
@amiga-500 please see this comment: https://github.com/discordjs/discord.js/issues/5103#issuecomment-757887662

**Comment by sindrekjr** [comment] 2021-03-02 06:15
Any good guess on when support for slash commands will be finalized and merged, and if it will be ready for when slash commands move out of beta?

**Comment by ckohen** [comment] 2021-03-02 06:20
It's unrealistic to give any guesses here, since discord is still making breaking changes to the API that we'll need to acommadate. We have been told that the API will be stable after https://github.com/discord/discord-api-docs/pull/2615 is merged, so that's likely when work can pick back up.

**Comment by AnImperialMan** [comment] 2021-03-11 12:47
> It's unrealistic to give any guesses here, since discord is still making breaking changes to the API that we'll need to acommadate. We have been told that the API will be stable after [discord/discord-api-docs#2615](https://github.com/discord/discord-api-docs/pull/2615) is merged, so that's likely when work can pick back up.

the pr in discord repo is merged, what about support in discordjs? Cant wait for this feature, all my work of bot stopped due to waiting of slash commands..

**Comment by Johnsiras** [comment] 2021-03-20 14:42
how to delete the slash commands? just ask..

**Comment by wonderlandpark** [comment] 2021-03-20 16:01
> how to delete the slash commands? just ask..

https://github.com/discordjs/discord.js/issues/5103#issuecomment-757887662

**Comment by Johnsiras** [comment] 2021-03-21 07:26
ok thx..

**Comment by UltimatePro-Grammer** [comment] 2021-04-11 02:07
Since [we can now use this](https://stackoverflow.com/a/65422307/13608595), is there a PR for a nicer API? At the moment the API is pretty hacky looking.

**Comment by advaith1** [comment] 2021-04-11 02:08
#5448

**Comment by Colonel-Ltd** [comment] 2021-04-20 15:11
How `awaitMessages`  can be done with slash command ?

**Comment by monbrey** [comment] 2021-04-21 01:13
> How `awaitMessages` can be done with slash command ?

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by LoneDev6** [comment] 2021-05-03 09:13
> channel

Keep in mind that this message `type` is deprecated https://discord.com/channels/533407895010803753/786912739313975336/838704482463645727

**Comment by neelkarma** [comment] 2021-05-08 12:31
#5448 got merged 🎉

**Closed** 2021-05-09 12:09 UTC
Labels: reason: API support, s: Discord, t: REST, t: gateway
