### ISSUE TITLE
fetchMessages( { limit : 1 } ) does not return the last message in channel if sent by a bot

### ISSUE THREAD

**Issue by MasonStooksbury** [discordjs/discord.js#4724] opened 2020-08-19 22:09 UTC
What up folks. As a precursor to this, I have made several Discord bots in the past but I did so in Python. This is my first attempt using the discord.js version. That being said, I'm pretty familiar with Javascript but just need a fresh set of eyes to make sure I'm not completely missing something.

So basically, a user is able to send a DM to the bot. The bot will then respond with a message and then react to it (very common way of doing polls and what not). This is where things get a little complicated. 

I've figured out a way to use this reaction system as almost a kind of directory for FAQs. Because the "directory", as it were, has two levels, I need a way to keep the conversation going and have the reactions be on the correct message.

Here's where "fetchMessages" comes in. In order to piggyback off the previous messages reactions, I need to get the last message sent by the bot, not the user. However, using "fetchMessages" returns the last thing the user said, and the only way I can grab what the bot last said (also the last thing in the DM thread) is if I nest the calls as shown below.

Please let me know if I'm missing something or if you need more code. Hopefully there is an actual solution because I hate the way this looks (I realize the emojis aren't real. I just put placeholders to make things a bit more readable):

```
msg.author.send('What is your issue?').then(reaction => {
	reaction.react('1').then(() => reaction.react('2')).then(() => reaction.react('3'));
})

const filter = (reaction, user) => {
	return ['1', '2', '3'].includes(reaction.emoji.name) && user.id === msg.author.id;
};

msg.channel.fetchMessages({ limit: 1 }).then(message => {
	msg.channel.fetchMessages({ limit: 1 }).then(message => {

		let lastMessage = message.last();
		console.log(lastMessage);
                
                lastMessage.awaitReactions(filter, { max: 1, time: 60000, errors: ['time'] })
			.then(collected => {
				const reaction = collected.first();
		
				// Option 1
				if (reaction.emoji.name === emojis[1]) {
					msg.author.send('What is your issue?').then(reaction => {
					reaction.react('1').then(() => reaction.react('2')).then(() => reaction.react('3'));
				})
                   ....
```

**Further details:**

- discord.js version: 11.5.1
- Node.js version: 12.13.1
- Operating system: Windows 10
- Priority this issue should have: Meh

**Comment by monbrey** [comment] 2020-08-19 22:16
This is most likely being caused by simultaneous execution of async functions. `msg.channel.fetchMessages` will be starting its async execution prior to `msg.author.send` resolving.

I'd suggest seeking further support by asking in the [Discord server](https://discord.gg/bRCvFy9) where we can provide guides on handling promises effectively.

**Comment by MasonStooksbury** [comment] 2020-08-19 22:20
Could I slap a ```.then()``` on the end of ```msg.author.send```? And put the fetch calls and what not inside that?

**Comment by monbrey** [comment] 2020-08-19 22:20
You could, though if you don't like the way this looks as you suggested, I'd recommend looking at the `async/await` syntax rather than nesting `.then` callbacks.

**Comment by MasonStooksbury** [comment] 2020-08-19 22:23
Yeah, you're probably right. I just tested the ```.then()``` thing and it totally do. But I'll look more into async/await for a bit cleaner/more correct way to do it.

Thanks again for your quick response and help!

**Closed** 2020-08-19 22:33 UTC
Labels: s: unverified, type: bug
