### ISSUE TITLE
Couldn't load the documentation data.  TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by BotTest298** [discordjs/discord.js#4859] opened 2020-09-28 19:03 UTC
When i go to https://discord.js.org/#/docs/main/stable/general/welcome, it shows an error that says:https://discord.js.org/#/docs/main/stable/general/welcome. I'm not sure what's causing it, but everything was working yesterday. I don't think its my PC/software, but I'm not sure.

**Comment by almostSouji** [comment] 2020-09-28 19:19
duplicate of #4860

**Closed by almostSouji** 2020-09-28 19:19 UTC
Labels: s: duplicate
