### ISSUE TITLE
TypeError: channel.isTextBased is not a function

### ISSUE THREAD

**Issue by david-geisinger** [discordjs/discord.js#9298] opened 2023-03-29 23:57 UTC
### Which package is this bug report for?

discord.js

### Issue description

We have been running an app where a user clicks a button and we process a simple interaction on our node server for several weeks. Today it seems to have broken and "TypeError: channel.isTextBased is not a function" is the error.

Steps to reproduce:
1. Add a button to a discord channel
2. Try to interact with the button from the backend by listening using 
``` client.on(Events.InteractionCreate, async (interaction) => { ```

### Package version

14.7.1

### Node.js version

18.15.0

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, GuildMessageReactions

**Comment by Jiralite** [comment] 2023-03-29 23:57
Duplicate of #9295.

**Closed by Jiralite** 2023-03-29 23:57 UTC
Labels: bug, need repro, packages:discord.js
