### ISSUE TITLE
 voice adapter creator type and discord.js adapter creator type is not assignable to each other

### ISSUE THREAD

**Issue by Lechixy** [discordjs/discord.js#7273] opened 2022-01-14 22:17 UTC
### Which package is this bug report for?

voice

### Issue description

i think adapter creator type discord.js and voice is not assignable to each other cause it different types
and also this happens when i use joinVoiceChannel() method it says:
Error: Type 'InternalDiscordGatewayAdapterCreator' is not assignable to type 'DiscordGatewayAdapterCreator'

![image](https://user-images.githubusercontent.com/51778131/149592048-5666c704-6aab-4df5-b639-54b24919cd2f.png)

### Package version

13.6.0

### Node.js version

v17.3.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES

**Comment by imranbarbhuiya** [comment] 2022-01-15 00:55
duplicate of #7221

**Comment by chevtek** [comment] 2022-01-16 18:57
Same issue here.

**Comment by ronniegeraghty** [comment] 2022-01-18 23:48
Does anyone know what update to discordjs or voice caused this incompatibility so I can go back before it happened?

**Comment by ronniegeraghty** [comment] 2022-01-19 17:18
> Same issue here.
> 
> I was able to temporarily resolve it by explicit casting.
> 
> ```ts
>     adapterCreator: channel.guild.voiceAdapterCreator as DiscordGatewayAdapterCreator
> ```
> 
> But I feel like I shouldn't have to do that.

Was not able to use this temp fix as the type `InternalDiscordGatewayAdapterCreator` does not overlap sufficiently with the type `DiscordGatewayAdapterCreator`

**Comment by chevtek** [comment] 2022-01-19 17:21
I’m not sure why it works for me but not you. At any rate, here’s the code in case you want to look at it in context.

https://github.com/chevtek/chevcasttv/blob/master/server/api-clients/discordClient.ts#L40

**Comment by iCrawl** [comment] 2022-01-19 17:40
This is the correct way of doing things for now, has been since the release of the voice lib.

A fix liket his is obviously needed, but it's not on a high priority since its solely a typing issue. Not a functional one.

**Comment by chevtek** [comment] 2022-01-19 17:47
I agree it’s no big deal since it’s easy to fix, but I will point out that this definitely changed at some point. The `channel.guild.voiceAdapterCreator` was at one point a `DiscordGatewayAdapterCreator`. At some point in a minor or patch version of Discord.js the type of that changed to `InternalDiscordGatewayAdapterCreator`. Not sure why it changed, but that’s definitely why it suddenly doesn’t work with the voice package. Has to be a minor or patch update because I hadn’t made any major version changes in package.json but the caret (`^`) in front of the package version tells npm to go ahead and pull in all minor and patch version updates.

**Closed** 2022-01-25 06:45 UTC
Labels: bug, need repro, packages:voice

**Comment by ReFruity** [comment] 2022-05-29 20:40
The problem is back in @discordjs/voice 0.9.0

**Comment by kyranet** [comment] 2022-05-29 20:55
Seems to be caused by `discord.js@13.6.0` using `discord-api-types@0.26.0` and `discord.js@13.7.0` using `discord-api-types@0.30.0`, while `@discordjs/voice@0.9.0` uses `discord-api-types@0.29.0`.

I believe the version mismatch may have been caused because the version of /voice discord.js v13 was made to use precedes the monorepo, which has helped us keep the dependencies in sync. Making a new version of /voice that's compatible with discord.js v13 may be impossible to achieve.

There are two solutions, though:

- **Override the version**:
  - **Yarn**:
    Add the following to your `package.json`:
    ```json
    "resolutions": {
      "discord-api-types": "^0.30.0"
    }
    ```

    [Documentation](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
  - **npm**:
    Add the following to your `package.json`:
    ```json
    "overrides": {
      "discord-api-types": "^0.30.0"
    }
    ```

    Alternatively, if your `npm` version is too old and doesn't support it, or you support npm and yarn in the project, you may also use [`npm-force-resolutions`](https://yarnpkg.com/package/npm-force-resolutions).

    [Documentation](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)
- **Using dev versions**:
  In the dev versions, all of our packages are published at the same time with matching versions, and therefore, no conflicts exist.
  This approach also requires migrating to v14, see the guide's draft [here](https://deploy-preview-1011--discordjs-guide.netlify.app/additional-info/changes-in-v14.html).

Sadly, I don't think we'll be able to resolve this issue for v13, so please use either workaround above.
