### ISSUE TITLE
Bot receiver listen only to itself

### ISSUE THREAD

**Issue by IcedElect** [discordjs/discord.js#2963] opened 2018-11-21 15:54 UTC
Hello, i have problem with createReceiver. I have code:

    client.on('message', message => {
      // Voice only works in guilds, if the message does not come from a guild,
      // we ignore it
      if (!message.guild) return;

      if (message.content === '/q') {
        // Only try to join the sender's voice channel if they are in one themselves

        const voiceChannel = message.member.voiceChannel;

        if (message.member.voiceChannel) {
          message.member.voiceChannel.join()
            .then(connection => { // Connection is an instance of VoiceConnection
                connection.on('error', console.error);

                // const dispatcher = connection.playFile('C:/Denwer/ddradio/lyubov.mp3');

                connection.on('speaking', (user, speaking) => {
                    if(speaking) {
                        const receiver = connection.createReceiver();
                        const stream = receiver.createPCMStream(user);

                        stream.on('data', chunk => {
                            console.log(chunk.length);
                        });
                    }
                });
            })
            .catch(console.log);
        } else {
          message.reply('');
        }
      }
    })

`console.log(chunk.length);` working only when playing music, those. only when the bot speaking. He does not hear other members. Please tell me what the problem is

**Comment by IcedElect** [comment] 2018-11-21 16:08
He will send pcm only when he speaks himself, but does not transmit pcm, when other users speak, while speaking, speaking, it also works for users.

**Comment by Dev-Yukine** [comment] 2018-11-21 22:09
this seems related to #2929

**Comment by iCrawl** [comment] 2018-11-27 16:12
Duplicate of #2929

**Closed by iCrawl** 2018-11-27 16:12 UTC
