### ISSUE TITLE
Types incompatible with `discord.js` in `SlashCommandBuilder`

### ISSUE THREAD

**Issue by Mighty683** [discordjs/discord.js#7962] opened 2022-05-23 14:01 UTC
### Which package is this bug report for?

builders

### Issue description

`Client.application.commands.set` is using `RESTPostAPIApplicationCommandsJSONBody` type from `discord-api-types/rest/v9` but `SlashCommandBuilder.toJSON` is using `RESTPostAPIApplicationCommandsJSONBody` from `discord-api-types/rest/v10`, which is causing type errors when I try to use `SlashCommandBuilder` to build an command for application.

Packages versions which I use:
```
"discord-api-types": "0.33.0",
"discord.js": "13.7.0",
"@discordjs/rest": "0.4.1",
````

### Code sample

```typescript
const client = new Discord.Client({...});
// configure client
const commandBuilder = new SlashCommandBuilder();
// build command
const commandBody = commandBuilder.toJSON();

client.application.commands.set([commandBody]); // Typescript will throw 
// workaround for typescript throwing error
client.application.commands.set([commandBody as ApplicationCommandDataResolvable]);
```

### Package version

13.7.0

### Node.js version

16.13

### Operating system

Alpine Linux Docker Container

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug), No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by kyranet** [comment] 2022-05-24 08:15
`discord.js` v13.7.0 works best with discord-api-types 0.30.0, see [here](https://github.com/discordjs/discord.js/blob/v13/package.json#L58), and you must as well use `discord-api-types/v9` instead of `discord-api-types/v10` as well, since it's the version both its [http](https://github.com/discordjs/discord.js/blob/v13/src/util/Options.js#L164) and [ws](https://github.com/discordjs/discord.js/blob/v13/src/util/Options.js#L160) handlers use by default. `@discordjs/rest` v4.0.1 [uses discord-api-types 0.29.0](https://github.com/discordjs/discord.js/blob/@discordjs/rest@0.4.0/packages/rest/package.json#L57), which is a mismatching version.

To get around this version conflict, you can use npm's [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or Yarn's [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to set the version of `discord-api-types` to [0.30.0](https://www.npmjs.com/package/discord-api-types/v/0.30.0).

> **Warning**
> `@discordjs/rest` [v4.0.1 uses `/v10`](https://github.com/discordjs/discord.js/blob/@discordjs/rest@0.4.0/packages/rest/src/lib/utils/constants.ts#L1), not `/v9` like `discord.js` v13.7.0 does. This means that **you cannot use types interchangeably**. Please keep this in mind when building your bot.

If you desire to use discord-api-types [0.33.0](https://www.npmjs.com/package/discord-api-types/v/0.33.0) (and by extension, also latest /rest and /builders), please switch to the development versions. At the time of writing, the very latest versions you can get (which I can confirm they work) are:

- `discord.js` [14.0.0-dev.1653091711-fdeac9d](https://www.npmjs.com/package/discord.js/v/14.0.0-dev.1653091711-fdeac9d)
- `@discordjs/builders` [0.14.0-dev.1653091712-fdeac9d](https://www.npmjs.com/package/@discordjs/builders/v/0.14.0-dev.1653091712-fdeac9d)
- `@discordjs/rest` [0.5.0-dev.1653091732-fdeac9d](https://www.npmjs.com/package/@discordjs/rest/v/0.5.0-dev.1653091732-fdeac9d)

To help updating to the development version (named v14), we also have a migration guide [PR](https://github.com/discordjs/guide/pull/1011), you can also see the preview [here](https://deploy-preview-1011--discordjs-guide.netlify.app/additional-info/changes-in-v14.html).

I'll close this as wontfix because it's not an issue the library can resolve, but rather an issue with conflicting versions, which you as a user can fix.

**Closed by kyranet** 2022-05-24 08:15 UTC
Labels: bug, need repro
