### ISSUE TITLE
429 hit on route /gateway/bot

### ISSUE THREAD

**Issue by gc** [discordjs/discord.js#3902] opened 2020-03-06 07:40 UTC
**Please describe the problem you are having in as much detail as possible:**

My bot randomly had almost all shards stop working strangely, so i rebooted, where it would no longer start up at all, so I enabled debug logs to find this being *spammed* like crazy:

`429 hit on route /gateway/bot`

I don't know if its a bug in d.js potentially causing it, it seems like it could be that D.JS is sending too many requests. This is the second time this happened, and I haven't been able to get help on why/how. 

**Include a reproducible code sample here, if possible:**

N/A - I have no idea why/how, and it happens randomly.  The bot is opensource however if that helps https://github.com/gc/oldschoolbot

**Further details:**

- discord.js version: discordjs/discord.js#97eac663b3e1292cc399c56eb701069301f4637d
- Node.js version: v12.12.0
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by vladfrangu** [comment] 2020-03-06 07:49
This really doesn't make sense as you use Internal Sharding, and there is only ONE request per attempt to create a shard... Can you DM me debug logs of what happens BEFORE the ratelimit spam?

**Comment by gc** [comment] 2020-03-06 08:08
[osts-out.log](https://github.com/discordjs/discord.js/files/4297186/osts-out.log)
[osts-error.log](https://github.com/discordjs/discord.js/files/4297187/osts-error.log)

I've also upgraded to a more recent d.js version now `#fe7df708e44e0280dfaf0f8e457b154781bb5140`

**Comment by MattIPv4** [comment] 2020-03-06 10:37
Related: https://github.com/discordjs/discord.js/issues/3891 & https://github.com/discordjs/discord.js/issues/3890

**Comment by iCrawl** [comment] 2020-03-07 05:09
Duplicate of 3891

**Closed by iCrawl** 2020-03-07 05:09 UTC
Labels: s: unverified, type: bug
