### ISSUE TITLE
client.on('guildMemberRemove') and client.on('guildMemberAdd') suddenly ceased functioning.

### ISSUE THREAD

**Issue by kovalide** [discordjs/discord.js#4959] opened 2020-10-30 05:21 UTC
**Please describe the problem you are having in as much detail as possible:**

From no modification of my own (last edit was 24th of october, issue appeared 26th or 27th of october), my code inside client.on('guildMemberAdd', (member) => {}); and client.on('guildMemberRemove', (member) => {}); stopped working. I tested it with my bot with everything else functioning properly, those doesn't seem to want to trigger.

May or may not be related : I've also encountered an issue including stuff into my cache. I noticed my ''role-react'' message wasn't behaving properly because it's the entrance of my server and nobody would get access. The bot seems to only fetch the specific message in the cache once an input that calls the bot is sent (I use !ping which tells him to delete the !ping message. Once it deletes the message, the role-react function suddenly works, as if the fact that I sent an input to the bot made the cache update, but this wasn't necessary before October 26th to my knowledge). I'll make another issue report once I've properly established the cause and effect, with sample code.

I don't believe anything but source code could affect this.

**Include a reproducible code sample here, if possible:**

```js
//basic discord stuff
const Discord = require('discord.js');
const client = new Discord.Client();
const token = **replace your own token here** //this requires modification
client.once('ready', () => {
  console.log("I'm in!");
  console.log("-" +client.user.username);
});

//functions to test
client.on('guildMemberAdd', (member) => {
  console.log("someone joined!");
});
client.on('guildMemberRemove', (member) => {
  console.log("someone left!");
});
//end of functions to test

client.login(token);
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.16.1
- Operating system: Repl.it
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by jxpsert** [comment] 2020-10-30 05:28
Duplicate of #4949 / #4950

**Comment by vBread** [comment] 2020-10-30 05:30
Refer to https://github.com/discordjs/discord.js/issues/4950#issuecomment-718138480

**Closed** 2020-10-30 08:14 UTC
Labels: s: duplicate
