### ISSUE TITLE
Detect if a message is a reply to another one

### ISSUE THREAD

**Issue by datorium** [discordjs/discord.js#5055] opened 2020-11-27 22:18 UTC
Discord is rolling up a reply feature. Users can now reply to messages (see attached image). But currently there is no explicit way (so far known to us) to detect weather the message is a reply to another one, or just a simple message. Would be very useful to have this feature.

Ideally, would be useful to be able to detect if a message is a reply message, if yes then also get reference to the original message and user.

![Capture](https://user-images.githubusercontent.com/45357320/100486817-68a6d800-310e-11eb-9c25-ed325bdbc015.PNG)

Thanks,
El

**Comment by almostSouji** [comment] 2020-11-27 22:25
duplicate of and solved in https://github.com/discordjs/discord.js/pull/4874

**Closed by almostSouji** 2020-11-27 22:25 UTC
Labels: type: enhancement

**Comment by monbrey** [comment] 2020-11-28 01:36
This is actually already possible on v12, since replies use the same `Message#reference` property as crossposts, which are already supported. The PR for sending inline replies is not required.
