### ISSUE TITLE
Role Update Audit Log Does Not State Which Role Was Updated

### ISSUE THREAD

**Issue by Skillz4Killz** [discordjs/discord.js#2741] opened 2018-08-12 17:30 UTC
**Please describe the problem you are having in as much detail as possible:**
When fetching audit logs for ROLE_UPDATE, I get a object that doesn't tell me what role it was that was affected.

```js
'463894437261475840' => GuildAuditLogsEntry {
     targetType: 'ROLE',
     actionType: 'UPDATE',
     action: 'ROLE_UPDATE',
     reason: null,
     executor: [KlasaUser],
     changes: [Array],
     id: '463894437261475840',
     extra: null,
     target: undefined }
```

### Solution:

Use `target` property to show the Role ID.

### Raw API Response

```js
"audit_log_entries": [
    {
      "target_id": "412083758741848066",
      "changes": [
        {
          "new_value": 3661965,
          "old_value": 14524637,
          "key": "color"
        }
      ],
      "user_id": "403069175121182720",
      "id": "476645729771847691",
      "action_type": 31
    },
```

**Include a reproducible code sample here, if possible:**
```js
const auditLogs = await guild.fetchAuditLogs({ type: 'ROLE_UPDATE' })
console.log(auditLogs.entries.first());
```

**Further details:**

- discord.js version: Master "github:discordjs/discord.js#7d2744be89f90fa16b77b6fbad95902e26f4564a"
- node.js version: v10.6.0
- Operating system: Mac OSX
- Priority this issue should have – please be realistic and elaborate if possible: Medium (Audit logs are a very important feature in order to provide the best possible moderation tools to users.)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:
"github:discordjs/discord.js#7d2744be89f90fa16b77b6fbad95902e26f4564a"

**Comment by SpaceEEC** [comment] 2018-08-12 17:31
Can you please fill in the "**Further details**"?

**Comment by SpaceEEC** [comment] 2018-08-12 18:11
Just to be sure, is the role in this case already deleted?
Because I can only reproduce it for deleted roles.

**Comment by Skillz4Killz** [comment] 2018-08-12 18:48
Nope the role does indeed exist

**Comment by SpaceEEC** [comment] 2018-08-12 18:54
There seems to be no role with the id `'412083758741848066'` in `guild.roles`:
<https://github.com/discordjs/discord.js/blob/7d2744be89f90fa16b77b6fbad95902e26f4564a/src/structures/GuildAuditLogs.js#L358>

If you could console.log a bit around there, that would be nice.
Stuff like `data.target_id`, `guild.roles.keyArray()`, etc.

**Comment by Skillz4Killz** [comment] 2018-08-12 21:04
I tried some more debugging but I am unable to replicate this. Perhaps you are right; however, the role still exists its my admin role so I know it still exists and has existed. If I am able to replicate this in the future I will let you know because right now it is working oddly enough.

**Comment by SpaceEEC** [comment] 2018-08-15 07:58
I'll closing this as it seems to be "fixed" (for) now.
If it happens again feel free to comment again / open a new issue, whatever seems more appropriate.

**Closed** 2018-08-15 07:58 UTC
Labels: p: medium, t: REST, type: bug
