### ISSUE TITLE
guild.roles.create method no longer returns ANYTHING on one server only.

### ISSUE THREAD

**Issue by dougwithseismic** [discordjs/discord.js#4019] opened 2020-04-04 12:12 UTC
The guild.roles.create method is no longer returning - 
I've been programmatically creating roles on one server using the below code; However, today it isn't returning anything at all - **But only when called on ONE PARTICULAR SERVER.**

The code works fine when targeting a new server, but not my normal test one. I thought maybe it was because I had created the max. no of roles, and deleted to make room for them but still, no dice. 

To hazard a guess at recreating, I'd look at creating 250 roles on a server, deleting them all and trying to create more perhaps?

```js
      guild.roles
        .create({
          data: {
            name: `Pickup Group`,
            color: 'BLUE'
          },
          reason: 'For Pickup Groups'
        })
        .then((x) => console.log('x :', x))
        .catch(error => console.error(error))
```

**Further details:**

- discord.js version: Stable 57334
- Node.js version: 12.16.1
- Operating system: Win 10 10.0.18362
- Priority this issue should have – please be realistic and elaborate if possible: High

- [x] I have also tested the issue on latest master, commit hash:

**Comment by SketchyLxve** [comment] 2020-04-04 13:00
This might seem like an odd question, but are you by any chance doing this in a `try/catch` without resolving the promise inside of it? Your client might not have the permissions necessary to create roles in that guild (`MANAGE_ROLES` if I'm not mistaken). The way I mean this is, does your code look something like:
```js
try { 
  guild.roles.create({
     data: { /* ... */ },
     reason: "Some Reason"
  });
} catch { 

}
```
I might be mistaken completely and perhaps I'm not looking at this issue correctly, but I believe that this is a possibility.

**Comment by dougwithseismic** [comment] 2020-04-04 13:29
@SketchyLxve Good thought - I did try a trycatch previously with nothing and I've tried once more after reading with no luck. No errors at all. It's a strange one.

**Comment by SketchyLxve** [comment] 2020-04-04 13:31
My point wasn't that a try/catch would fix it, but rather that the `catch` would never execute since Promises aren't interpreted as errors directly. But the rejected promise is. Anyways, I'm unable to reproduce this "bug" in any of my guilds.

**Comment by iCrawl** [comment] 2020-06-19 10:05
Closing as it is a stale issue, reopen or check open issues if this is still an issue.

**Closed by iCrawl** 2020-06-19 10:05 UTC
Labels: s: unverified, t: REST, t: ratelimits, type: bug

**Comment by JMTK** [comment] 2021-08-09 18:57
Don't know if it's worth reopening, but I was able to reproduce this when a server that has my bot had 250 roles. I had expected the `create` call to throw an error code of  `MAXIMUM_ROLES: 30005` but it just hangs indefinitely.

I can make a new issue if needed
