### ISSUE TITLE
messageBulkDelete firing twice. 

### ISSUE THREAD

**Issue by russellg89** [discordjs/discord.js#2485] opened 2018-04-18 21:47 UTC
bot.on("messageDeleteBulk", messages => {
    console.log("saw bulk delete")
}
if(command==="prune"){
    if(!args[0]){ message.delete();    } else{ let num=parseInt(args[0])+1; channel.bulkDelete(num); }
}

Result of one command:
![image](https://user-images.githubusercontent.com/20692895/38959934-85777774-4330-11e8-9f1b-c66faf60ffbf.png)

Versions:
discord.js 11.3.2
node.js 9.9.0
ubuntu 16.04.4

**Comment by iCrawl** [comment] 2018-04-18 21:48
Duplicate of #2382

**Closed by iCrawl** 2018-04-18 21:48 UTC
