### ISSUE TITLE
Embed Color is not accepting #HEX

### ISSUE THREAD

**Issue by rodycouto** [discordjs/discord.js#8304] opened 2022-07-18 00:02 UTC
### Which package is this bug report for?

builders

### Issue description

![Screenshot_1](https://user-images.githubusercontent.com/70030588/179430132-e6b2e667-4ecc-431d-90d4-60d1238139f0.png)

### Code sample

```typescript
return await interaction.reply({
    embeds: [
        {
            color: '#FF0000',
            title: 'Some title'
        }
    ]
})
```

### Package version

14.0.1

### Node.js version

v16.15.0

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent, GuildScheduledEvents

**Comment by suneettipirneni** [comment] 2022-07-18 01:02
Hi, this is intended behavior in v14. Colors within json objects are not resolved by default. If you'd like to use hex colors you have three options:

1. Use a hex number literal
Instead of using the `color: '#FF0000'` you can use a hex literal `color: 0xFF0000`

2. Use `EmbedBuilder` either via the constructor or the setters.

3. Use 	the `resolveColor(color)`utility function to resolve the hex color in the json.

**Closed** 2022-07-18 01:04 UTC
Labels: bug, need repro, packages:discord.js
