### ISSUE TITLE
embedFieldsArrayPredicate - does not satisfy the constraint error

### ISSUE THREAD

**Issue by Natto-PKP** [discordjs/discord.js#8262] opened 2022-07-09 19:59 UTC
### Which package is this bug report for?

builders

### Issue description

Generate documentation with typedoc
1. Run `typedoc src/api.doc.ts typings/index.d.ts --out docs`
2. Errored : 
```
Error: node_modules/@discordjs/builders/dist/index.d.ts:14:78 - error TS2344: Type '{ name: string; value: string; inline: boolean | undefined; }' does not satisfy the constraint 'unknown[]'.
  Type '{ name: string; value: string; inline: boolean | undefined; }' is missing the following properties from type 'unknown[]': length, pop, push, concat, and 29 more.

declare const embedFieldsArrayPredicate: _sapphire_shapeshift.ArrayValidator<{
```

### Code sample

```typescript
@discordjs/builds/dist/index.d.ts


declare const embedFieldsArrayPredicate: _sapphire_shapeshift.ArrayValidator<{
    name: string;
    value: string;
    inline: boolean | undefined;
}>;
```

must be ?

```ts
declare const embedFieldsArrayPredicate: _sapphire_shapeshift.ArrayValidator<{
    name: string;
    value: string;
    inline: boolean | undefined;
}[]>;
```

### Package version

0.14.0

### Node.js version

17.3.0

### Operating system

Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment] 2022-07-09 20:10
Duplicate of #8244.

**Closed by Jiralite** 2022-07-09 20:10 UTC
Labels: duplicate, packages:builders
