### ISSUE TITLE
messageDeleteBulk fired twice

### ISSUE THREAD

**Issue by TimoZaaijer** [discordjs/discord.js#2649] opened 2018-07-05 11:35 UTC
**Please describe the problem you are having in as much detail as possible:**
I am trying to code a log that logs deleted messages etc... When i started working on the messageDeleteBulk, it logged it twice, after trying and trying ti fix this. I haven't fixed it...

**Include a reproducible code sample here, if possible:**
```js
const { RichEmbed } = require("discord.js");

module.exports = (client, messageCollection) => {
    let channel = client.channels.get(client.guildSettings.get(messageCollection.first().guild.id).LogChannel);
console.log('Test')
    messageCollection.forEach(message => { 
        client.emit('messageDelete', message)
})
};
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.4.0
- Operating system: Mac OS
- Priority this issue should have – Medium

- [ ] I found this issue while running code on a __bot account__

**Comment by SpaceEEC** [comment] 2018-07-05 11:43
Duplicate of #2382 and #2485.

**Closed by SpaceEEC** 2018-07-05 11:43 UTC
