### ISSUE TITLE
`getSubcommand` Omitted from type `CommandInteractionOptionResolver`

### ISSUE THREAD

**Issue by chexburger** [discordjs/discord.js#8459] opened 2022-08-09 21:19 UTC
### Which package is this bug report for?

discord.js

### Issue description

When using TypeScript, the CommandInteractionOptionResolver has omitted valid function calls and thus results in an error.

From VSCode:
```
Property 'getSubcommand' does not exist on type 'Omit<CommandInteractionOptionResolver<CacheType>, "getMessage" | "getFocused" | "getMentionable" | "getRole" | "getAttachment" | ... 6 more ... | "getSubcommand">'.ts(2339)
```

### Code sample

```typescript
const option = interaction.options.getSubcommand();
```

### Package version

14.1.2

### Node.js version

v16.16.0, TS 4.7.4

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

### I have tested this issue on a development release

aac8aac.0

**Comment by Jiralite** [comment] 2022-08-09 21:23
You have provided no context whatsoever. Until then, this bug report is not useful.

**Comment by chexburger** [comment] 2022-08-09 21:26
> You have provided no context whatsoever. Until then, this bug report is not useful.

I have included the VSCode output when hovering.

**Comment by Jiralite** [comment] 2022-08-09 21:27
It's still not enough information.

What is the type of `interaction`?

**Comment by chexburger** [comment] 2022-08-09 21:29
> What is the type of `interaction`?

CommandInteraction

**Comment by Jiralite** [comment] 2022-08-09 21:29
Then this is working as expected and is not a bug. Duplicate of #8306. See the comment - it may help you.

**Closed by Jiralite** 2022-08-09 21:29 UTC
Labels: bug, need repro, typings, packages:discord.js

**Comment by chexburger** [comment] 2022-08-09 21:32
Ended up being the same issue. My typings set interaction as `ChatInteraction` and I forgot to change that with everything else even though the function required `ChatInputCommandInteraction` to be passed for interaction. Simply missed a change which was overwriting what I was looking at.
