### ISSUE TITLE
[MessageEmbed] TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by Shaehl** [discordjs/discord.js#4341] opened 2020-06-07 19:59 UTC
**Please describe the problem you are having in as much detail as possible:**
I using glitch as place where i can make any sync with discord server and run into this error with MessageEmbed on line 443.
```
TypeError: fields.flat is not a function

    at Function.normalizeFields (/rbd/pnpm-volume/5f00682a-3f01-4890-ac71-8018b6903145/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:443:8)

    at MessageEmbed.addFields (/rbd/pnpm-volume/5f00682a-3f01-4890-ac71-8018b6903145/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:259:42)

    at MessageEmbed.addField (/rbd/pnpm-volume/5f00682a-3f01-4890-ac71-8018b6903145/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:250:17)
```

**Include a reproducible code sample here, if possible:**
```js
var embed = new Discord.MessageEmbed()
.setTitle(stickerInfo.pl)
.addField("Image id", stickerInfo.ii)
.addField("Canvas position", stickerInfo.pos)
```
**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.0
- Operating system: i think glithc based on linux
- Priority this issue should have – please be realistic and elaborate if possible: 

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment] 2020-06-07 20:04
Duplicate of #3913, #3910, #3888, #3887, #3883 and #3949

**Closed** 2020-06-07 21:56 UTC
Labels: s: duplicate
