### ISSUE TITLE
Small sound no playing or cut

### ISSUE THREAD

**Issue by crizip** [discordjs/discord.js#2546] opened 2018-05-08 21:48 UTC
**Please describe the problem you are having in as much detail as possible:**
Small sound under 10 sec not playing or is not playing in full time !

```
const dispatcher = connection.playFile("/var/bot/sound.mp3", {volume:0.50});
      dispatcher.on('end', () => {
          const timeoutObj = setTimeout(() => {
            const dispatcher = null;
            connection.disconnect();
          }, 2000);

          dispatcher.on('error', error => {
            console.log(error)
          });
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v10.0.0
- Operating system: linux

**Comment by robflop** [comment] 2018-05-21 09:34
Hey, check out Issue #2548, maybe the answer I left there could be helpful to you.

**Comment by hydrabolt** [comment] 2018-06-21 20:56
Can you try reproducing this with the master branch? `npm i discordjs/discord.js` should install the development version of discord.js you need to test this with. To make your code compatible with the new version, just replace `playFile` with `play`

**Comment by Tentoe** [comment] 2018-07-04 06:50
I had a similar Problem. Sounds would be cut off a few seconds early using Node 10. Node 8.11 seems to work fine.

**Comment by xan105** [comment] 2018-07-09 05:15
As Tentoe said i think this issue appeared with node 10.x 
I have a similar problem when playing short small file where the sound being played cuts off before the end. After a lot of test, i concluded that it was since i had updated from node 9.x to node 10.x. I have reproduced the issue on both my dev machine and vps. Downgrading to node 9.x solve the issue.

discord.js@11.3.2

**Comment by hydrabolt** [comment] 2018-07-09 09:10
Great news! When v12 releases I'll close this issue.

**Closed** 2018-08-10 09:05 UTC
Labels: p: medium, t: voice, type: bug
