### ISSUE TITLE
stopTyping function not working

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#3237] opened 2019-04-27 11:01 UTC
**Please describe the problem you are having in as much detail as possible:**
The stopTyping() function seems to not work, even with force option.

**Include a reproducible code sample here, if possible:**
```js
channel.startTyping();
channel.stopTyping(); // Not working
channel.stopTyping(true); // Not working
```

**Further details:**
- discord.js version: lastest master
- Node.js version: 11.14.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible: high

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment] 2019-04-27 16:16
Closing because duplicate of #3216

**Closed by amishshah** 2019-04-27 16:16 UTC
