### ISSUE TITLE
`RoleManager#everyone` can be `undefined`

### ISSUE THREAD

**Issue by Syjalo** [discordjs/discord.js#8411] opened 2022-08-01 05:52 UTC
### Which package is this bug report for?

discord.js

### Issue description

`<Guild>.roles.everyone` typed as `Role`, but it can be `undefined` if there's no `Guilds` intent. Leads to internal errors when interacting with roles.
![image](https://user-images.githubusercontent.com/62868468/182080779-f9115c70-65f8-48d6-b101-3bc7cfd2cb63.png)
![image](https://user-images.githubusercontent.com/62868468/182080267-ca946add-aa9c-429f-88ad-24d458f959c5.png)

### Code sample

```typescript
import { Client } from 'discord.js';
import 'dotenv/config';

const client = new Client({
  intents: 0,
});

client.on('ready', async () => {
  const guild = await client.guilds.fetch('724163890803638273');
  guild.roles.highest;
  console.log('Ready');
});

client.login();
```

### Package version

14.1.2

### Node.js version

16.16.0

### Operating system

Win 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment] 2022-08-01 06:24
Duplicate of #8301.

**Closed by Jiralite** 2022-08-01 06:24 UTC
Labels: bug, need repro
