### ISSUE TITLE
Parse custom emoji as emoji ID automatically.

### ISSUE THREAD

**Issue by zero734kr** [discordjs/discord.js#4889] opened 2020-10-04 21:35 UTC
**Is your feature request related to a problem? Please describe.**
When I use ``message.react("<:sending:636204938103488534>")``, Discord API throws an error that saying ``636204938103488534>`` is not a snowflake.

**Describe the ideal solution**
It's would be more helpful when parse automatically to 636204938103488534.

**Describe alternatives you've considered**
Just use the emoji ID, I'm too lazy to click on backspaces but I didn't think opening an issue would make me more lazy.

**Additional context**
![image](https://user-images.githubusercontent.com/51540538/95027605-36c64780-0670-11eb-8c0b-8ca0ecdf681d.png)

**Comment by IDjinn** [comment] 2020-10-05 21:18
I've had same problem

**Comment by monbrey** [comment] 2020-10-05 21:21
I don't believe running a regex over user input to extract IDs is something the library should be responsible for doing.

**Comment by IDjinn** [comment] 2020-10-05 21:23
I think it's look like just doesn't remove > after id...

**Comment by monbrey** [comment] 2020-10-05 21:24
Discord.js doesn't remove anything - that's just how Discord interpreted the request and responded.

**Comment by IDjinn** [comment] 2020-10-05 21:26
Ohh, okay thank you

**Comment by IDjinn** [comment] 2020-10-05 21:27
@zero734kr If you have emoji id, so just use emoji id 🤔

**Comment by almostSouji** [comment] 2020-10-05 21:33
duplicate of https://github.com/discordjs/discord.js/issues/4006

**Closed by almostSouji** 2020-10-05 21:33 UTC
Labels: type: enhancement
