### ISSUE TITLE
Finish event doesn't get fired when the dispatcher gets destroyed while the stream is paused.

### ISSUE THREAD

**Issue by CheesyZaem** [discordjs/discord.js#2648] opened 2018-07-04 10:13 UTC
**Please describe the problem you are having in as much detail as possible:**
Supposedly, the "finish" event should get fired when the dispatcher gets destroyed but somehow it doesn't when the dispatcher is destroyed while the stream is paused.

**Include a reproducible code sample here, if possible:**
```js
var dispatcher = <Connection>.play(ytdl("url", {audioonly: true}));
dispatcher.on("finish", () => console.log("ended"));
setTimeout(() => dispatcher.pause(), 3000);
setTimeout(() => dispatcher.destroy(), 5000);
```

**Further details:**

- discord.js version: master
- node.js version: v8.11.2
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by PLASMAchicken** [comment] 2018-07-04 10:41
I am sure destroying the dispatcher will make it unable to emit any events

**Comment by Dev-Yukine** [comment] 2018-07-08 10:56
Dispatcher extends WritableStream and you use a method from that. if you would've looked in the node.js docs you would've seen that WritableStream#end is the method you want since it will call the finish event.

**Comment by CheesyZaem** [comment] 2018-07-08 11:21
I tried it, it does nothing as well.

**Comment by amishshah** [comment] 2018-08-11 09:50
I can reproduce this, will try to fix this over the next week

**Comment by amishshah** [comment] 2018-08-13 16:41
Fixed in the above commit, @Dev-Yukine was correct about using `.end()` instead of `.destroy()` to get the `finish` event. If you can still reproduce, please re-open.

**Closed by amishshah** 2018-08-13 16:41 UTC
Labels: t: voice, type: bug
