### ISSUE TITLE
interaction.fetchReply isn't working

### ISSUE THREAD

**Issue by DragosPV** [discordjs/discord.js#8338] opened 2022-07-22 16:25 UTC
### Which package is this bug report for?

discord.js

### Issue description

`await interaction.reply('Pong!');`
`const message = await interaction.fetchReply();`
`console.log(message);`

this is from the documentation and isn't working, this is the error

![image](https://user-images.githubusercontent.com/98609931/180481450-9a1b90e6-985d-4344-a15d-cccb401e43af.png)

### Package version

13.6.0

### Node.js version

16.15.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by kyranet** [comment] 2022-07-22 16:26
Duplicate of #8335.

**Closed** 2022-07-22 16:26 UTC
Labels: bug, need repro

**Comment by kentiphp** [comment] 2022-07-22 16:36
![image](https://user-images.githubusercontent.com/52530011/180484524-629db12c-ba64-4d2d-ab31-4c66447496e1.png)
