### ISSUE TITLE
"message.content" is empty

### ISSUE THREAD

**Issue by devrusty** [discordjs/discord.js#8333] opened 2022-07-22 01:28 UTC
### Which package is this bug report for?

discord.js

### Issue description

Inside of a "messageCreate" event, the `message.content` property of the `message` parameter is an empty string.

![image](https://user-images.githubusercontent.com/57299745/180341770-c81eac6f-341c-478f-b91e-fdf1b926a4e3.png)
![image](https://user-images.githubusercontent.com/57299745/180341796-74a6e73b-2963-4f57-8209-8479cc92cb7e.png)

### Package version

14.0.3

### Node.js version

18.6.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, DirectMessages

**Comment by Jiralite** [comment] 2022-07-22 01:28
Duplicate of #7840.

**Closed by Jiralite** 2022-07-22 01:28 UTC
Labels: bug, need repro

**Comment by glitchychoppa** [comment] 2023-04-04 02:03
I can't get it in any way, it always comes back empty. I can't understand

**Comment by almostSouji** [comment] 2023-04-04 02:31
As the linked issue states, you need the [`MessageContent` gateway intent](https://discordjs.guide/popular-topics/intents.html#gateway-intents). You need to supply it in the Client options and enable it in the application dashboard (or apply for it, should your bot be verified).

Without the intent, you will still receive messages, but they will not have any content.
If you need more specific help with your code, please join the Discord server at https://discord.gg/djs

**Comment by glitchychoppa** [comment] 2023-04-04 09:06
Thank you for informing me

Souji ***@***.***>, 4 Nis 2023 Sal, 05:31 tarihinde şunu
yazdı:
