### ISSUE TITLE
[BUG]: Discord responses with 405 when sending DMs

### ISSUE THREAD

**Issue by jxn-30** [discordjs/discord.js#5261] opened 2021-01-25 19:33 UTC
**Please describe the problem you are having in as much detail as possible:**
Hello together,
I'm facing an issue with sending DMs via discord.js:
whenever I called `User#send`, discord.js threw the following Error:
```
DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/home/jan/Dokumente/TCC/Dispatcher/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at RequestHandler.push (/home/jan/Dokumente/TCC/Dispatcher/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at User.createDM (/home/jan/Dokumente/TCC/Dispatcher/node_modules/discord.js/src/structures/User.js:252:18) {
  method: 'post',
  path: '/users/channels',
  code: 0,
  httpStatus: 405
}
```

According to [Discord Developer Portal](https://discord.com/developers/docs/resources/user#create-dm) the path must be `/users/@me/channels`, not just `/users/channels`.
I wonder, how that issue seems not to be reported yet, so it may be a unique issue?
However, I changed the code within my `node_modules` a bit to find out wether the usage of `/@me` solves the issue and indeed it does:
Changing [Line 32 in `node_modules/discord.js/src/rest/APIRouter.js`](https://github.com/discordjs/discord.js/blob/master/src/rest/APIRouter.js#L32) to
```js
route.join('/') === '/users/channels' ? '/users/@me/channels' : route.join('/'),
```
does the thing and the bot can send DMs without any Problems.

**Include a reproducible code sample here, if possible:**

```ts
<User>user.send('Hello World');
```

**Further details:**

- discord.js version: 12.5.1 *(latest)*
- Node.js version: v14.8.0
- Operating system: Kubuntu 19.10
- Priority this issue should have – please be realistic and elaborate if possible: medium to high. Seen this for the first time but does not allow the bot to send DMs

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment] 2021-01-26 03:59
This is because discord.js is using the client user id in the endpoint instead of `@me`, which seems to work but is not documented and should be changed. You are probably running this before the client is logged in so the user id is not yet set.

**Comment by jxn-30** [comment] 2021-01-26 05:35
The bot has been receving and sending messages before, so i don't understand how it shouldn't be logged in.

**Comment by KokosnussDEV** [comment] 2021-01-26 09:24
I tried reproducing this but I end up getting 400 errors:
```
C:\Users\Konstantin\Desktop\test\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (C:\Users\Konstantin\Desktop\test\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async RequestHandler.push (C:\Users\Konstantin\Desktop\test\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async User.createDM (C:\Users\Konstantin\Desktop\test\node_modules\discord.js\src\structures\User.js:252:18) {
  method: 'post',
  path: '/users/550995072221446155/channels',
  code: 50007,
  httpStatus: 400
}
```
**Code:**
```js
const Discord = require('discord.js');

const client = new Discord.Client();

client.once('ready', () => {
    console.log(`Logged in as ${client.user.username}`);
});

client.on('message', (msg) => {
    msg.author.send(msg.content);
});

client.login('xxxxxxxxxxxxxxxx');
```
**System:**
Discord.js: 12.5.1
Node.js: 15.5.0
OS: Windows 10 [10.0.19042.746]

**Comment by tipakA** [comment] 2021-01-26 09:26
@KokosnussDEV Your error is caused because the bot tries to DM itself, since sending DM triggers message event.

**Comment by KokosnussDEV** [comment] 2021-01-26 09:47
I can reproduce this behaviour on my windows machine using the same TypeScript codebase as @jxn-30.

**Comment by almostSouji** [comment] 2021-01-26 10:23
Cannot reproduce. Neither on 12.5.1 nor #master 9ffcd83027f0fc06d69df21475865ad55138de01

**Comment by jxn-30** [comment] 2021-01-26 11:24
> Cannot reproduce. Neither on 12.5.1 nor #master [9ffcd83](https://github.com/discordjs/discord.js/commit/9ffcd83027f0fc06d69df21475865ad55138de01)

So it seems to be an unique issue. I will investigate that further and see if I find any further clues why exactly this happens...

**Comment by jxn-30** [comment] 2021-01-26 20:33
I was able to create a Code-Snippet that produces the error:

```ts
import Discord from 'discord.js';
import pconfig from './configs/.private';

const client = new Discord.Client();
client.once('ready', async () => {
    console.log(client.user);
    setInterval(() => {
        if (typeof client.user === 'string') {
            console.log(`client.user is currently ${client.user}`);
            process.exit(-1);
        }
    }, 1000);
    client.guilds.cache.forEach(guild => guild.members.fetch(client));
});

client.login(pconfig.token).then(() => console.info('logged in'));
```

`GuildMemberManager#fetch` does accept a [`UserResolvable`](https://discord.js.org/#/docs/main/stable/typedef/UserResolvable). `Client` however is not a `UserResolvable`. TypeScript still does not throw an Error at this point because the TypeDefinitions allow `UserResolvable | FetchMemberOptions | (FetchMembersOptions & { user: UserResolvable })` as first Parameter.
`Client` is compatible with `FetchMemberOptions` as it is defined as
```ts
interface FetchMemberOptions {
    user: UserResolvable;
    cache?: boolean;
    force?: boolean;
}
```
And `Client#user` is of course a `UserResolvable`.

So **if** I do unterstand that right:
* `GuildMemberManager#fetch(user)` does change the `user` object if `user` is a client.
* TypeScript allows to pass a `Client` as parameter which results in the presented Error.

Having a look at [GuildMemberManager](https://github.com/discordjs/discord.js/blob/stable/src/managers/GuildMemberManager.js#L123)s Code:
```js
fetch(options) {
    if (!options) return this._fetchMany();
    const user = this.client.users.resolveID(options);
    if (user) return this._fetchSingle({ user, cache: true });
    if (options.user) {
      if (Array.isArray(options.user)) {
        options.user = options.user.map(u => this.client.users.resolveID(u));
        return this._fetchMany(options);
      } else {
        options.user = this.client.users.resolveID(options.user);
      }
      if (!options.limit && !options.withPresences) return this._fetchSingle(options);
    }
    return this._fetchMany(options);
  }
  ```
fetching does change the `user` attribute of `client` (or any other passed argument).

This has never resulted in issues as passing the client as argument is not intended!

**Comment by iCrawl** [comment] 2021-01-26 20:50
Why exactly are you fetching your client user in every guild?

But as a general workaround just doing `guild.members.fetch(client.user.id)` will do the trick.

**Comment by jxn-30** [comment] 2021-01-26 20:53
> Why exactly are you fetching your client user member in every guild?
for checking permissions & setting Nickname

> But as a general workaround just doing guild.members.fetch(client.user.id) will do the trick.
Yes, I've already done that in our repo. Still thanks for the tip!

**Comment by iCrawl** [comment] 2021-01-27 13:32
I'm going to close this in favor of #5267

**Closed by iCrawl** 2021-01-27 13:32 UTC
Labels: s: cannot reproduce, type: bug
