### ISSUE TITLE
Discord.js TypeError: Cannot convert "null" to int

### ISSUE THREAD

**Issue by fellon24** [discordjs/discord.js#3997] opened 2020-03-26 07:02 UTC
function play(connection, message) {

                var server = servers[message.guild.id];
                server.dispatcher = connection.play(ytdl(server.queue[0], { filter: "audioonly" }));
                server.queue.shift();
                server.dispatcher.on("finish", function () {
                    if (server.queue[0]) {
                       play(connection, message);
                    } else {
                        connection.disconnect();
                    }
                });
            }

            if (!args[1]) {
                message.channel.send('1.')
                return;
            }
            if (!message.member.voice.channel) {
                message.channel.send('2.')
                return;
            }

            if (!servers[message.guild.id]) servers[message.guild.id] = {
                queue: []
            }

            var server = servers[message.guild.id];

            server.queue.push(args[1]);

            if (!message.guild.voiceConnection) message.member.voice.channel.join().then(function (connection) {
                play(connection, message);
            });
            break;
*And here's the console log after this*

```
TypeError: Cannot convert "null" to int

C:\Users\Дима\Desktop\Chaos Bot\node_modules\opusscript\build\opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Modu
abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```
Nodejs - 12.16.1
opusscript - 0.0.7
ytdl - ^0.29.7
ffmpeg - 0.0.4

**Comment by SketchyLxve** [comment] 2020-03-26 07:19
I believe that this is a duplicate of #3895. 
And I think that the only time that this error will occur at is when you resolve the promise and use the callback variable from it in order to call `VoiceConnection#play()`, as per this comment - <https://github.com/discordjs/discord.js/issues/3895#issuecomment-596296996>
However I did not test this myself and can't say for certain.

**Closed** 2020-03-26 10:34 UTC
Labels: s: unverified, type: bug

**Comment by isolin** [comment] 2020-05-01 21:49
I found a solution for that!

Please read my answer at [StackOverflow](https://stackoverflow.com/questions/60695216/how-to-resolve-typeerror-cannot-convert-null-to-int/61551067#61551067). It contains a hack fix where you need to delete a conditional in **prism-media**.

I also filed a bug report [over here](https://github.com/amishshah/prism-media/issues/45)

@BannerBomb @kSt4rz @Impalez @superVoja @qazxsw1240 hopefully a solution for you as well.
