### ISSUE TITLE
Network Failure Unhandled

### ISSUE THREAD

**Issue by ChrisTalman** [discordjs/discord.js#1677] opened 2017-07-10 10:18 UTC
**Please describe the problem you are having in as much detail as possible:**
An unhandled exception, as follows, is thrown when my network adaptor is disabled. This seems odd, as I was under the impression that this should be handled gracefully by the `disconnect` event.

```
Error: getaddrinfo ENOENT gateway.discord.gg:443
    at Object.exports._errnoException (util.js:1034:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Include a reproducible code sample here, if possible:**
The exception is thrown whenever there is any active connection to the Discord API, such as below.

```js
const Discord = require('discord.js');
let robot = new Discord.Client();
let token = 'example123';
robot.login(token);
```

**Further details:**

- discord.js version: 11.1.0.
- node.js version: 7.8.0.
- Operating system: Windows 10 Pro 10.0.15063 Build 15063.
- Priority this issue should have – please be realistic and elaborate if possible: Medium. This exception may not be thrown very often, but if the intention is for `disconnect` to handle it, it could cause ungraceful failures in some cases, which would seem undesirable.

- [x] I found this issue while running code on a __bot account__

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment] 2017-07-10 11:07
this is your internet, not a lib problem

**Comment by ChrisTalman** [comment] 2017-07-10 11:12
@devsnek Well, in this case, my Internet was fine, and I deliberately disabled my network adaptor to see whether a loss of connection would be handled gracefully. It was not. Strictly speaking, is this not what the `disconnect` event is intended to handle? Its description is as follows: '_Emitted when the client's WebSocket disconnects_'. Is this not a case of the client's WebSocket disconnecting?

**Comment by devsnek** [comment] 2017-07-10 18:10
it only emits when the socket disconnects in a way that it can't reconnect, usually we will automatically resume the ws for you.

**Comment by ChrisTalman** [comment] 2017-07-11 16:35
@devsnek Okay. Well, this seems to be such a case, where the socket cannot reconnect. It would be nice for Discord.js to gracefully handle an exception such as this. It seems to fall within the scope of the event as described in the documentation, and would be very helpful in a library which handles WebSockets at its core.

**Comment by CharlotteDunois** [comment] 2017-07-16 13:12
@ChrisTalman How exactly would you handle such an exception? If you can't get DNS info about an address, then you can't reconnect. The only thing you can do at this point is to shut down the process.

**Comment by ChrisTalman** [comment] 2017-07-16 18:32
@CharlotteDunois The context is that a network connection is not currently possible, but that it could be in the future. Thus, it is possible to reconnect, eventually. The library could handle this itself by reconnecting automatically, or application code could handle `disconnect` and call `login` at some interval.

**Comment by ShadowDrakken** [comment] 2017-08-17 12:07
This error happens when internet connectivity is lost by any means, not just manually disabling the NIC. Previously, the bot would sit there and wait and if the connection returned within about 2 minutes it would reconnect. Well, sometimes, it's always been flakey about reconnecting.

Anyway, the correct behavior would be to sit and wait, occasionally polling to see if it can reconnect. SAy once per minute or something to that effect. Not to just dump out and give up without the user's interaction.

**Comment by devsnek** [comment] 2017-08-17 15:50
I disagree, we aren't responsible for your internet. If you need to keep something hosted 24/7 buy yourself some hosting or get better internet.

**Comment by ShadowDrakken** [comment] 2017-08-17 22:55
That's not what the issue is about. It's about gracefully handling network interruptions, like every other half decent piece of software.

**Comment by devsnek** [comment] 2017-08-17 23:02
we will not keep a thread open "occasionally polling to see if it can reconnect". that is objectively stupid. you can poll yourself and call login if you need to.

**Comment by ChrisTalman** [comment] 2017-08-17 23:07
If that's the behaviour the user wants, I don't see how that's 'objectively stupid'. It's hardly like that would be an intensive operation, and it could be made optional. But, in any case, this issue started with the even more basic expectation that the `disconnect` event be fired in the case of a network failure instead of an exception being thrown. If this were done, a user could implement their own reconnection attempts. Although, having said this, having reconnection functionality out of the box would clearly be valuable to some users as has been demonstrated by this issue thread.

**Comment by ShadowDrakken** [comment] 2017-08-17 23:20
"You can poll yourself and call login"

That really IS objectively stupid, because the exception is closing the process out leaving no opportunities so do this.

**Comment by ShadowDrakken** [comment] 2017-08-17 23:28
ChrisTalman: it used to have auto-reconnect. Prior to this error developing.

**Comment by devsnek** [comment] 2017-08-17 23:40
the option known as `autoReconnect` was removed in 11.x because we made it so **you cannot turn it off**. The issue with the error not bubbling up through client#onerror and client#ondisconnect will be fixed, but no new methods for "extended" reconnection will be added.

**Comment by aemino** [comment] 2017-08-19 14:20
Personally, I think that the library should be tolerant of various network faults. If no one else bothers to implement this, I will eventually.

**Comment by hydrabolt** [comment] 2017-08-26 12:49
Mostly fixed in master, may still error on failed reconnects (not sure can't test atm)

**Comment by SpaceEEC** [comment] 2018-01-23 17:21
Is this still an issue?
Simply handling the error event with a console.log and letting discord.js reconnecting is working fine for me on `11.3` and https://github.com/discordjs/discord.js/commit/5352e28700e51f1148463f350fe5694124a3c270.

**Comment by ChrisTalman** [comment] 2018-01-23 20:17
I'm not sure. I didn't see this issue mentioned in the release notes for `11.3`.

I certainly know that socket hang exceptions still seem to happen (for instance, see #2047). This may or may not be related to the network failure handling, but this is difficult to determine given that in both cases the exception is thrown out of nowhere. Both certainly concern appropriately handling failure on the network, though.

**Comment by kyranet** [comment] 2018-01-23 20:20
After voice-rewrite, it seems to be fixed. The commit from the master branch in [`5efddac`](https://github.com/discordjs/discord.js/commit/5efddac0250a6c92573ee107a82db511dd4f95cf) doesn't handle these errors, and oddly enough, it logs the ECONNRESET twice: one as handled, and another as unhandled.

After [`86da7af`](https://github.com/discordjs/discord.js/commit/86da7af4f18abc295dccf7535b1ce8c1effd8b6e), that got fixed in my end and these errors are properly handled by the `event` error.

**Comment by Lewdcario** [comment] 2018-03-02 16:41
This is not an issue on 11.3-dev, so I will close this.

**Closed by Lewdcario** 2018-03-02 16:41 UTC
Labels: p: medium, t: gateway, type: bug
