### ISSUE TITLE
.toJSON() is 'unknown'

### ISSUE THREAD

**Issue by fronkdev** [discordjs/discord.js#10311] opened 2024-06-02 03:39 UTC
### Which package is this bug report for?

discord.js

### Issue description

TypeScript deems 'Class#toJSON()' as unknown, replicable by utilising any of the toJSON methods with a d.js structure (I've only personally tested User#toJSON and GuildMember#toJSON)
This becomes an issue when attempting to utilise a spread operator: `Spread types may only be created from object types.ts(2698)`

### Code sample

```typescript
const member = await guild.members.fetch('User ID');
const basicSpread = {
  ...member.toJSON() // Spread types may only be created from object types.ts(2698)
}
```

### Versions

discord.js@14.15.2
typescript@5.4.3
node@20.12.2

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment] 2024-06-02 05:44
Duplicate of #9432.

**Closed by Jiralite** 2024-06-02 05:44 UTC
Labels: bug, need repro, packages:discord.js
