### ISSUE TITLE
Cannot read properties of undefined (reading 'fetchReply')

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [discordjs/discord.js#7043] opened 2021-11-27 06:33 UTC
### Issue description

1. Update a interaction

### Code sample

```typescript
await updateInt(int, { content: "test" } )

async function updateInt(int,content) {
    switch (int.replied){
        case true:
            return await int.editReply(content)

        case false:
            return await int.update(content)
    }
}


TypeError: Cannot read properties of undefined (reading 'fetchReply')
    at ButtonInteraction.update (C:\Users\User\OneDrive\Desktop\Karyl\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:208:17)
    at exports.updateInt (C:\Users\User\OneDrive\Desktop\Karyl\Tools.js:10:30)
    at Battle (C:\Users\User\OneDrive\Desktop\Karyl\Explore_Commands\test.js:680:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Battle (C:\Users\User\OneDrive\Desktop\Karyl\Explore_Commands\test.js:845:23)
    at async Battle (C:\Users\User\OneDrive\Desktop\Karyl\Explore_Commands\test.js:740:31)
```

### discord.js version

13

### Node.js version

17.1.0

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGE_REACTIONS

**Comment by Jiralite** [comment] 2021-11-27 06:54
On version 13 as specified by you, the error comes from line 208 here:

https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/interfaces/InteractionResponses.js#L206-L210

This means `update()` was called with no arguments (or `undefined` literally). This method expects an argument. Additionally, on the latest stable version (currently 13.3.1), this check is removed due to the new ability to fetch ephemeral messages. It would also seem the reproducible code sample is not reproducible per your error and the referenced code...?

I would urge you to update to 13.3.1 and make sure you are supplying the required arguments as necessary to methods. This is not a bug.

**Comment by kyranet** [comment] 2021-12-02 00:31
Closing as it's caused by user-error (not passing a required parameter) and is most likely fixed in latest stable release.

**Closed by kyranet** 2021-12-02 00:31 UTC
Labels: bug, need repro
