### ISSUE TITLE
The search box crashes the whole site on specific values.

### ISSUE THREAD

**Issue by IxAlpha** [discordjs/discord.js#10086] opened 2024-01-13 21:44 UTC
### Which application is this bug report for?

Documentation

### Issue description

I have encountered a recurring issue that has prompted me to express a preference for the older documentation, which I found more user-friendly in terms of readability and navigation. Additionally, there is an issue with the current search functionality; at times, it causes the website to crash unexpectedly, necessitating the opening of a new tab. I have attached a video demonstrating this particular bug occures while searching for "Sharding Manager". 

https://github.com/discordjs/discord.js/assets/82391184/8e29e84a-3bf4-415b-be4d-cad494ee8e62

### Steps to Reproduce

1. Go to the [docs](https://[discord.js](https://discord.js.org/docs/packages/discord.js/14.14.1).org/docs/packages/discord.js/14.14.1).
2. Open the search box and type "Sharding Manager".
3. After typing "Sharding", the crash occurs for around 30 seconds. Then a pop up message with "This page isn't responding". After seconds, it will get back to nornal.

![Alpha_1705182132](https://github.com/discordjs/discord.js/assets/82391184/bc33277c-5d54-4775-b8b8-372766dec3a8)

### Versions

- Edge version 120.0.2210.133 (Official build) (64-bit)
- Windows 11 Pro (v22H2)

### Issue priority

Medium (should be fixed soon)

**Comment by Jiralite** [comment] 2024-01-13 21:50
Duplicate of #10029.

**Closed by Jiralite** 2024-01-13 21:50 UTC
Labels: bug, need repro, apps:website
