### ISSUE TITLE
Reaction collector

### ISSUE THREAD

**Issue by Aleksio1123** [discordjs/discord.js#4849] opened 2020-09-25 08:39 UTC
**Please describe the problem you are having in as much detail as possible:**
Reaction collectors nor awaitReactions collect reactions

**Include a reproducible code sample here, if possible:**

```js

message.channel.send("s").then(msg => {
        //addReactions(msg)
        const filter = (reaction, user) => {
            return reaction.emoji.name === '👍' && user.id === message.author.id;
        };
        const collector = msg.createReactionCollector(filter, { time: 60000 })
        collector.on('collect', r => {
            console.log(r.emoji.name)
        })

        collector.on('end', () => {
            console.log("Collector ended")
            msg.reactions.removeAll().catch(console.error)
        })
    })
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.5.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: high

**Relevant client options:**

- partials: none
- gateway intents: enabled
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment] 2020-09-25 08:57
Running this exact piece of code on 12.3.1 results in a thumbs up being logged and after the full minute in removal of the reaction, i'm  really not too sure what the bug is supposed to be here.

**Comment by Aleksio1123** [comment] 2020-09-25 12:59
I'm sure he adds to the news thumb reactions up

**Comment by almostSouji** [comment] 2020-09-25 13:25
I ran it again with a complete reproducible code example (attached below), please try to reproduce it with this (based on your code, adding a thumbs up reaction, decreasing the collector duration and based on the [standard discord.js boilerplate](https://discord.js.org/#/docs/main/stable/examples/ping) with added debug logs):

- discord.js `12.3.1` (in the bot project folder run `npm list discord.js`)
- node.js: `14.0.9` (in the bot project folder run `node -v`)
- os: windows 10 - 2004 (OS Build 19041.508) `winver`
- Intents: none
- partials: none
- other: none

<details>
<summary>Debug boilerplate proposal</summary>

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
	console.log('I am ready!');
});


client.on('message', message => {
	if (message.content === 'test') {
		message.channel.send('s').then(msg => {
			msg.react('👍');
			const filter = (reaction, user) => reaction.emoji.name === '👍' && user.id === message.author.id;
			const collector = msg.createReactionCollector(filter, { time: 5000 });
			collector.on('collect', r => {
				message.channel.send(`Reaction with ${r.emoji}`);
			});

			collector.on('end', () => {
				message.channel.send('collector ended');
				msg.reactions.removeAll().catch(console.error);
			});
		});
	}
});

client.on('debug', console.log)
	.on('warn', console.log);

// Log our bot in using the token from https://discordapp.com/developers/applications/me
client.login('token');

```

</details>

![demo](https://user-images.githubusercontent.com/26532370/94271882-902cc900-ff42-11ea-8a8a-bf53dc932fc7.gif)

Since I see absolutely no reason why this wouldn't work for you i'm going to close this.

**Closed by almostSouji** 2020-09-25 13:25 UTC
Labels: s: cannot reproduce, type: bug
