### ISSUE TITLE
Type is missing in subcommand builders

### ISSUE THREAD

**Issue by djedje72** [discordjs/discord.js#7408] opened 2022-02-05 18:09 UTC
### Which package is this bug report for?

builders

### Issue description

Try the subcommand code from documentation : https://discordjs.guide/popular-topics/builders.html#subcommands

This error occurs :
```js
options[0].type: This field is required
    at RequestHandler.execute (/config/workspace/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/config/workspace/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async GuildApplicationCommandManager.create (/config/workspace/node_modules/discord.js/src/managers/ApplicationCommandManager.js:117:18)
    at async Client.<anonymous> (/config/workspace/index.js:79:29) {
  method: 'post',
  path: '/applications/****/guilds/****/commands',
  code: 50035,
  httpStatus: 400,
```

When i look [Discord Documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure) i can see the type is mandatory for subCommands (not default to 1 like Command).

If i use `SlashCommandSubcommandBuilder` inside `.addSubcommand`, it's KO.

If i manualy set the type to 1 inside `.addSubcommand`, the command registration is OK.
```js
const command = new SlashCommandBuilder()
	.setName('info')
	.setDescription('Get info about a user or a server!')
	.addSubcommand(subcommand => {
		const tmp= subcommand
			.setName('user')
			.setDescription('Info about a user')
			.addUserOption(option => option.setName('target').setDescription('The user')));
        tmp.type = 1;
        return tmp;
	})
	.addSubcommand(subcommand =>
		subcommand
			.setName('server')
			.setDescription('Info about the server'));
```

### Package version

0.12.0

### Node.js version

17.4.0

### Priority this issue should have

Medium (should be fixed soon)

**Comment by vladfrangu** [comment] 2022-02-05 18:11
The builder code is fine, you need to call .toJSON() before sending the data to Discord or to d.js methods. If you can repro after that, let us know

**Comment by djedje72** [comment] 2022-02-05 18:13
okay, with .toJSON() it's good :)

**Comment by vladfrangu** [comment] 2022-02-05 18:18
Yep, as said, it's not a bug, you need to always call .toJSON before sending, so I'll be closing this! If you have any other questions, or similar, feel free to follow up or ask in our [Discord server](https://discord.gg/djs). 😄

**Closed by vladfrangu** 2022-02-05 18:18 UTC
Labels: bug, invalid, packages:builders
