### ISSUE TITLE
Abort Error: User Aborted A Request

### ISSUE THREAD

**Issue by FirezzzZ** [discordjs/discord.js#4367] opened 2020-06-19 06:54 UTC
**Please describe the problem you are having in as much detail as possible:**
why does this error occur? even though my bot is hosted with the help of a vps
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment] 2020-06-19 06:58
This happens when discord.js doesn't receive a response to a request for more than 15 seconds.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by iCrawl** [comment] 2020-06-19 09:39
Duplicate of #3471

**Closed by iCrawl** 2020-06-19 09:39 UTC
Labels: s: unverified, type: bug
