### ISSUE TITLE
MessageEmbed > .flat is not a function.

### ISSUE THREAD

**Issue by Nicoxx45** [discordjs/discord.js#3949] opened 2020-03-16 20:08 UTC
**Please describe the problem you are having in as much detail as possible:**
I'm trying to send an embed using the MessageEmbed constructor but I get an error: `.flat is not a function` for MessageEmbed. When I'm trying to send an embed with embed since v12 I get this error.
**Include a reproducible code sample here, if possible:**

```js
const embed = new Discord.MessageEmbed()
            embed.setTitle("my text");
            embed.addFields( 
                {name: "my text", value: "`my text`"},
                {name: "my text", value: "my text"}
            );
            embed.setFooter("my text");
            embed.setColor("#892252");
            return message.channel.send(embed);
//I got the same error by using .addField("my text", "my text")...
```

**Further details:**

- discord.js version: v12.0.2
- Node.js version: Latest version (>12)
- Operating system: Windows, Linux
- Priority this issue should have – please be realistic and elaborate if possible: Many devs use MessageEmbed constructor and can be stuck.

- [x] I have also tested the issue on latest master, commit hash:

**Comment by LxveFades** [comment] 2020-03-16 20:10
It is because you're not using Node v12.x.x or greater. For future cases, I suggest that you report to the [Discord Server](https://discord.gg/bRCvFy9) before opening up an issue, as this is not a bug with the library. Discord.js v12 *requires* Node v12.x.x or greater. Please use the Discord Server for an issue like this next time. If necessary, you would be redirected to open up an issue.

**Comment by anandre** [comment] 2020-03-16 20:11
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.

That said, the readme for the library clearly states you need Node v12.x or higher to use the discord.js library.  Please update your Node.

**Comment by SpaceEEC** [comment] 2020-03-16 20:11
Duplicate of #3913, #3910, #3888, #3887, and #3883.

**Closed by SpaceEEC** 2020-03-16 20:11 UTC
Labels: s: duplicate, s: invalid
