### ISSUE TITLE
Mentions are not recognized when the mentioned person has a nickname and the mention is sent from android

### ISSUE THREAD

**Issue by denizariyan** [discordjs/discord.js#2948] opened 2018-11-15 12:26 UTC
When the mentions are sent from android they have a construction of `<@[id]>` even when the mentioned person has a nickname. On different platforms when a user has a nickname and they are mentioned the mention is constructed as `<@![id]>`. Because of this bots doesn't recognize mentions that are sent from Android. 

There are libs that check for both of them when looking for mentions but discord.js is not one of them. You can check the ss for what I meant in the first paragraph from[this link](http://prntscr.com/liossv)

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.11.1
- The priority this issue should have: Medium-Easy fix

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment] 2018-11-15 12:48
Please provide a reproducible code sample, expected behavior, as well as actual behavior, because I have no clue what you are actually reporting.

---

Also:
The Discord-API sends the mentioned users as an array along the message.
There is exactly zero string parsing going on behind the scenes for that.

See:
https://github.com/discordjs/discord.js/blob/3418b5a1a2e2e424369da42f0a04dc3523f3d933/src/structures/Message.js#L131
https://github.com/discordjs/discord.js/blob/3418b5a1a2e2e424369da42f0a04dc3523f3d933/src/structures/MessageMentions.js#L47-L50

---

Also the regex we provide for mentions (but not use for above reasons) accounts for the ! being optional:
https://github.com/discordjs/discord.js/blob/3418b5a1a2e2e424369da42f0a04dc3523f3d933/src/structures/MessageMentions.js#L163

---

Note: If you test on latest master always provide the hash you actually tested.
("latest" changes all the time, a commit hash does not)

**Comment by denizariyan** [comment] 2018-11-15 14:10
I have tried it with the code I provided below and as you can see from [the video](https://youtu.be/EtVY85kZE0E) (yeah it took me 10 sec to write a simple message in mobile) when mention is sent from windows client there is no problem but when sent from android the mention is not recognized. Maybe a problem at how discord.js checks if mention array is empty or not?

the prefix is empty in this test, thus ignore it.

`if (message.content.toLowerCase().startsWith(prefix + 'test1')) {
		var membertest= message.mentions.members.first();
		if (!message.content.toLowerCase().includes(membertest)){
			message.channel.send("no mention has been recognized")
		}else {
			message.channel.send("mention has been recognized")
		}
	}`

I lost the commit has which I have tried it on so I can't send it, you may consider it as not tested but I'm sure it still exists

**Comment by SpaceEEC** [comment] 2018-11-15 14:55
You are using [String.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) on the content of the message to see whether a user mention (another string) is in there.
This is very well defined behavior and there is no magic going on behind the scenes.
For example: `Text <@218348062828003328> Text` simply does not contain `<@!218348062828003328>`.
That is nothing we can or should change.

---

How a user mention (with a nickname in your case) looks like is explicitly specified in [discord's api documentation](https://discordapp.com/developers/docs/reference#message-formatting-formats).
We are following that, see:
https://github.com/discordjs/discord.js/blob/3418b5a1a2e2e424369da42f0a04dc3523f3d933/src/structures/GuildMember.js#L359-L361

The discord mobile client not following that would be a bug on their end; Nothing we can fix either.

---

You can solve this issue on your end by using the earlier mentioned [`MessageMentions`](https://discord.js.org/#/docs/main/stable/class/MessageMentions), which (at least users) are populated by discord directly.
Simply check whether a key with the id of any user is in [`MessageMentions#users`](https://discord.js.org/#/docs/main/stable/class/MessageMentions?scrollTo=users). (See [`Map.prototype.has`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has))
You can find the relevant class instance under [`Message#mentions`](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=mentions).

---

Closing this as this is not a bug on our end.

**Closed by SpaceEEC** 2018-11-15 14:55 UTC
Labels: s: invalid
