### ISSUE TITLE
Discord.js Voice problem with Ubuntu and not Windows

### ISSUE THREAD

**Issue by Rizuk1** [discordjs/discord.js#5013] opened 2020-11-14 23:37 UTC
- discord.js version: latest(12.4.1)
- Node.js version: latest(15.2.0)
- Operating system: Ubuntu-Server(latest)
- Priority this issue should have – please be realistic and elaborate if possible: Hi, I just created a discord bot but there are some issues with some libraries. I tested the bot on Windows everything works fine, but on Ubuntu Server the 'pause ()' and 'resume ()' method doesn't work. When I perform these methods the dispatcher pauses, but when resuming the playing sound starts playing quickly unlike Windows where there is no problem.

- partials: none
- gateway intents: none
- other: none

- ✔ I have also tested the issue on latest master, commit hash.

**Comment by Rizuk1** [comment] 2020-11-14 23:53
Is there someone to help me figure out this bug ?

**Comment by almostSouji** [comment] 2020-11-15 00:03
This is not a chat platform, please be patient and provide as much information as you can for us to be able and reproduce and investigate your issue. (A reproducible code sample would be pretty useful, for example - see below)

> ✔ I have also tested the issue on latest master, commit hash.

please edit the actual commit hash you are on - master moves quite quickly and we need to be able and back-reference which version the bug appears in for you.

--- 

Please provide a minimal reproducible code sample so we can attempt to reproduce and verify your issue. This means isolating the erroneous behavior to a fresh bot, or stripping away functionality until you can be sure the code is minimal. Also include a manual with the steps you take interacting with the code in question which results in the behavior you outlined.

Please try to reproduce the issue yourself on a fresh bot. If you can't reproduce it, it's very likely that we can't either and the code sample in question is not enough.

Boilerplate: https://discord.js.org/#/docs/main/stable/examples/ping
Minimal Reproducible sample: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Rizuk1** [comment] 2020-11-15 00:28
Sorry, but i has test a new bot and the problem persists only Ubuntu. I had my code checked, no error returned. Only one assigned discord.js bug.

**Comment by Rizuk1** [comment] 2020-11-15 02:17
I just re-created a discord bot, the same result the 'pause ()' and 'resume ()' methods are perfect on Windows, Debian, Arch but on Ubuntu-Server the methods are as if they were poorly constructed. When I perform this method everything is fine. But when resuming the dispatcher is reset and goes back to the time it is or disconnects as in this problem: https://github.com/discordjs/discord.js/issues/672

I would like to let you know that this is not a code problem. I would just like to fix the problem and be able to understand why this one only works on Windows and Debian and not on Ubuntu-Server.

Thank you for your understanding.

**Comment by toclean** [comment] 2020-11-20 18:05
Have also ran into this issue with Ubuntu 20.04 and Windows 18363.1198. Pausing and Resuming a dispatcher has inconsistent results on Ubuntu but works just fine on windows.

**Comment by amishshah** [comment] 2021-06-09 10:51
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it

**Closed** 2021-06-09 13:23 UTC
Labels: s: unverified, t: voice, type: bug
