### ISSUE TITLE
If bot is connected to a voice channel for too long, it stops playing audio.

### ISSUE THREAD

**Issue by Dorfnox** [discordjs/discord.js#4021] opened 2020-04-04 18:46 UTC
Hi -

I have a discord bot that plays music in a voice channel.

I leave it connected overnight. Around 3am~ish, a user enters the voice channel and begins playing music just fine. They log out at 5am.

At 9am I wake up and join the voice channel, and music doesn't play. There are no errors thrown in the console.

It's as if everything works perfectly fine, except music doesn't stream through.
Some of my code:

```js
    _playRecursively() {
        const wr = new WaffleResponse();
        const { info, msg } = this.musicQueue.peek();
        const { title, videoId } = info.player_response.videoDetails;
        const ytLink = `https://www.youtube.com/watch?v=${videoId}`;

        const connection = this._getVoiceConnection();
        if (!connection) return ;

        const readableStream = ytdl.downloadFromInfo(info, { quality: 'highestaudio', highWaterMark: 1 << highWaterMarkBitShift }); /* ~4mbs */

        readableStream.on('error', err => {
            wr.setResponse(`'${title}' encountered an error while streaming. skipping.`).setError(err).reply(msg);
            const dispatcher = this._getDispatcher();
            if (dispatcher) dispatcher.end();
        });

        const dispatcher = connection.play(readableStream, { highWaterMark: 1 })
        dispatcher.on('start', () => {
                const embeddedMessage = this._getEmbeddedQueueMessage(false);
                wr.setEmbeddedResponse(embeddedMessage).reply(msg);
                this.client.user.setPresence({ activity: { name: `${title} 🎧`, type: 'PLAYING', url: ytLink }});
            })
            .on('finish', () => {
                wr.setResponse(`**${title}** has finished playing`).setIsSendable(false).reply(msg);
                this.client.user.setPresence({ activity: { name: '', type: '' }});
                getSafe(() => dispatcher.destroy());
                this.musicQueue.dequeue();
                if (!this.musicQueue.isEmpty()) {
                    this._playRecursively();
                }
            })
            .on('error', err => {
                wr.setResponse(`'${title}' encountered an error while streaming. skipping.`).setError(err).reply(msg);
                this.client.user.setPresence({ activity: { name: '', type: '' }});
                getSafe(() => dispatcher.destroy());
                this.musicQueue.dequeue();
                if (!this.musicQueue.isEmpty()) {
                    this._playRecursively();
                }
            });
        dispatcher.setVolumeLogarithmic(0.5);
    }
```

- discord.js version: latest
- Node.js version: latest
- Operating system: MaxOS Catalina 
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by uhKevinMC** [comment] 2020-04-05 00:53
This could be caused by the stream collapsing between you and the 3rd party, and your bot not recognizing that it has stopped. Did your bots speaking status also change or?

**Comment by Dorfnox** [comment] 2020-04-05 18:55
Thanks -
The bot even shows up as green as if it's 'speaking' when I play a song.

Do you think I should regularly disconnect it from the voice channel if there has been no activity for a while? I'm wondering if it could be because  leave it connected to the voice channel for days without disconnecting.

**Comment by uhKevinMC** [comment] 2020-04-06 23:20
> The bot even shows up as green as if it's 'speaking' when I play a song.

> Do you think I should regularly disconnect it from the voice channel if there has been no activity for a while?

Usually, the StreamDispatcher shouldn't stop like that, even if its for long periods at a time. It might be a possibility of having too many dropped packets and the dispatcher just stopping. If you can, can you attempt this again and `console.log()` the reason for the dispatcher finishing/erroring?

**Comment by Tenpi** [comment] 2020-04-07 16:54
I sometimes had this problem when playing from a readableStream. The solution was to write the stream onto an audio file, and then play the audio file.

**Comment by amishshah** [comment] 2021-06-09 10:55
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it

**Closed** 2021-06-09 13:23 UTC
Labels: s: unverified, t: voice, type: bug
