### ISSUE TITLE
channel.isTextBased is not a function

### ISSUE THREAD

**Issue by theSignSaysDie** [discordjs/discord.js#9297] opened 2023-03-29 23:25 UTC
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce:
- Create a basic Discord bot using this library
- Create any event file that listens to `Events.InteractionCreate` (codeblock below)
- Program a slash command for, say, displaying a button in a channel
- Start the bot, run the command, slick the button
- See something like the following error in the bot console:
```
29.03 22:15:38 [Bot] /node_modules/discord.js/src/client/actions/InteractionCreate.js:50
29.03 22:15:38 [Bot] if (channel && !channel.isTextBased()) return;
29.03 22:15:38 [Bot] ^
29.03 22:15:38 [Bot] TypeError: channel.isTextBased is not a function
29.03 22:15:38 [Bot] at InteractionCreateAction.handle (/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
29.03 22:15:38 [Bot] at Object.module.exports [as INTERACTION_CREATE] (/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
29.03 22:15:38 [Bot] at WebSocketManager.handlePacket (/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
29.03 22:15:38 [Bot] at WebSocketShard.onPacket (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
29.03 22:15:38 [Bot] at WebSocketShard.onMessage (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
29.03 22:15:38 [Bot] at callListener (/node_modules/ws/lib/event-target.js:290:14)
29.03 22:15:38 [Bot] at WebSocket.onMessage (/node_modules/ws/lib/event-target.js:209:9)
29.03 22:15:38 [Bot] at WebSocket.emit (node:events:513:28)
29.03 22:15:38 [Bot] at Receiver.receiverOnMessage (/node_modules/ws/lib/websocket.js:1180:20)
29.03 22:15:38 [Bot] at Receiver.emit (node:events:513:28)
```
I give this issue a High priority because Interactions are crucial to the operation of a Discord bot. My app in particular makes extensive use of buttons in action rows and modal inputs, which all crash the application when interacted with.

I tested this on the latest development version and found that it fixed the problem; HOWEVER, I am unable to install the development version of discord.js on the server the production version of the bot is running on.

### Code sample

```typescript
module.exports = {
	name: Events.InteractionCreate,
	async execute(interaction) {
            // Method body of your choice
        }
}
```
```


### Package version

14.7.1

### Node.js version

16.17.1

### Operating system

CentOS 8 Stream/Rocky Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, DirectMessages, MessageContent

### I have tested this issue on a development release

3cf4f4b.0

**Comment by monbrey** [comment] 2023-03-29 23:31
Update to v14.8.0 which includes a fix for this issue.

**Comment by Jiralite** [comment] 2023-03-29 23:32
Duplicate of #9295.

**Closed by Jiralite** 2023-03-29 23:32 UTC
Labels: bug, need repro, packages:discord.js
