### ISSUE TITLE
Library cannot locate sodium libraries

### ISSUE THREAD

**Issue by PapiOphidian** [discordjs/discord.js#8800] opened 2022-10-31 08:11 UTC
### Which package is this bug report for?

voice

### Issue description

The dependency report and runtime display errors saying that a sodium library cannot be found. The output of generateDependencyReport() and npm list can be found below. 0.11.0 works fine with the exact same setup of dependencies.

```
C:\Users\papi\Documents\GitHub\Volcano>npm run dep-report

> volcano@1.5.0 dep-report
> node ./scripts/generateDependencyReport.js

--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.13.0
- prism-media: not found

Opus Libraries
- @discordjs/opus: not found
- opusscript: not found

Encryption Libraries
- sodium-native: not found
- sodium: not found
- libsodium-wrappers: not found
- tweetnacl: not found

FFmpeg
- version: 5.0.1-essentials_build-www.gyan.dev
- libopus: yes
--------------------------------------------------

C:\Users\papil\Documents\GitHub\Volcano>npm list
volcano@1.5.0 C:\Users\papil\Documents\GitHub\Volcano
+-- @discordjs/opus@0.8.0
+-- @discordjs/voice@0.13.0
+-- @lavalink/encoding@0.1.2
+-- @types/node@18.11.7
+-- @types/ws@8.5.3
+-- @typescript-eslint/eslint-plugin@5.41.0
+-- @typescript-eslint/parser@5.41.0
+-- backtracker@3.3.1
+-- eslint@8.26.0
+-- ffmpeg-static@5.1.0
+-- html-entities@2.3.3
+-- lavalink-types@1.0.0 (git+ssh://git@github.com/AmandaDiscord/LavalinkTypes.git#e2844e22d3f881220be9dd08a1982ac5fffa691b)
+-- m3u8stream@0.8.6
+-- music-metadata@8.1.0
+-- node-html-parser@6.1.1
+-- play-dl@1.9.6
+-- prism-media@1.3.4
+-- sodium-native@3.4.1
+-- twitch-m3u8@1.1.3 (git+ssh://git@github.com/AmandaDiscord/twitch-m3u8.git#ba927b26fb3c5cb118d75c20f990c5cce8a1ae7a)
+-- typescript@4.8.4
+-- volcano-sdk@1.0.0 (git+ssh://git@github.com/AmandaDiscord/VolcanoSDK.git#729e6476704203557b5f16e30a353318a11269ab)
+-- ws@8.10.0
+-- yaml@2.1.3
`-- ytmusic-api@3.1.1
```

### Code sample

```typescript
N.A.
```

### Package version

0.13.0

### Node.js version

18.6.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by imranbarbhuiya** [comment] 2022-10-31 08:24
Duplicate of #8745

**Closed** 2022-10-31 08:27 UTC
Labels: duplicate, packages:voice
