### ISSUE TITLE
GuildMemberManager method send undefined 

### ISSUE THREAD

**Issue by AgustLuj** [discordjs/discord.js#7824] opened 2022-04-21 23:13 UTC
### Which package is this bug report for?

discord.js

### Issue description

i use await interaction.guild.members.fetch() and obtain this menssage. I can provider more information

TypeError: Cannot read properties of undefined (reading 'send')
0|index    |     at /*/node_modules/discord.js/src/managers/GuildMemberManager.js:403:24
0|index    |     at new Promise (<anonymous>)
0|index    |     at GuildMemberManager._fetchMany (/*/node_modules/discord.js/src/managers/GuildMemberManager.js:400:12)
0|index    |     at GuildMemberManager.fetch (/*/node_modules/discord.js/src/managers/GuildMemberManager.js:175:31)
0|index    |     at FichageManager.addRoleUser (/*/base/RoleManager.js:167:46)

### Package version

13.1.0

### Node.js version

v16.10.0

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment] 2022-04-21 23:15
Firstly try updating to the latest stable release to see if you can reproduce this error. Secondly, please attach a reproducible code sample (one that can generate that error with as few lines as possible)

**Comment by AgustLuj** [comment] 2022-04-21 23:20
It is quite complicated since it was generated on a production server and I do not have the context in which that problem was generated, it was an uncached error. But i try to replicated the error. 
Okey i updated to the last version

**Comment by vladfrangu** [comment] 2022-05-02 14:38
I'm confused what the issue is. GuildMemberManagers do not have a send method, so I think this is more user error than an issue with the library. I'll be closing this for now, but please do follow up with reproduction samples and I'll reopen this if applicable 👍

**Closed by vladfrangu** 2022-05-02 14:38 UTC
Labels: bug, need repro

**Comment by AgustLuj** [comment] 2022-05-15 17:18
Hi the GuildMemberManagers dont have the method send but in the line 422 has this
`this.guild.shard.send({
        op: Opcodes.REQUEST_GUILD_MEMBERS,
        d: {
          guild_id: this.guild.id,
          presences,
          user_ids,
          query,
          nonce,
          limit,
        },
      });` 
I cant reproduction but i put a few try catch to have the context to send you

**Comment by Cuhadari-Deniz** [comment] 2022-05-18 16:57
I have the same issue. Am I using the members wrong?
Hope somebody can help.

````
this.client.guilds.fetch({guild: 'MY_GUILD_ID'}).then(guilds => {
      guilds.members.fetch() // <- fails here
    });
````

Stacktrace:
````
C:\Users\...\myproject\node_modules\discord.js\src\managers\GuildMemberManager.js:419
    return new Promise((resolve, reject) => {
           ^
TypeError: Cannot read properties of undefined (reading 'send')
    at C:\Users\...\myproject\node_modules\discord.js\src\managers\GuildMemberManager.js:422:24
    at new Promise (<anonymous>)
    at GuildMemberManager._fetchMany (C:\Users\...\myproject\node_modules\discord.js\src\managers\GuildMemberManager.js:419:12)
    at GuildMemberManager.fetch (C:\Users\...\myproject\node_modules\discord.js\src\managers\GuildMemberManager.js:177:31)
    at C:\Users\...\myproject\src\features\discord\bot\discord.bot.ts:46:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
````

**Comment by ImRodry** [comment] 2022-05-18 17:06
You shouldn't be fetching guilds, they're all cached. This issue has been closed for days, please don't reply to it and if you really believe there's a bug open a new one, otherwise use the [Discord server](https://discord.gg/djs)
