### ISSUE TITLE
Problems With Discord

### ISSUE THREAD

**Issue by LeManock** [discordjs/discord.js#4362] opened 2020-06-16 20:23 UTC
Hello! I have this problems for **2** weeks and i did not find a **solution**.

`(node:4) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.`

And my bot’s ping is **high**!
My bot reply me after **3**-**5** minutes or **not**

![Capture d’écran 2020-06-16 à 22 18 20](https://user-images.githubusercontent.com/30638194/84824035-9a742880-b01f-11ea-9890-e7019ba9a14b.png)

_**Can someone help me please?**_

**Comment by iCrawl** [comment] 2020-06-16 20:26
Duplicate of #3471

**Closed by iCrawl** 2020-06-16 20:26 UTC
Labels: s: unverified, type: bug

**Comment by ledlamp** [comment] 2020-06-18 22:13
I'd say this isn't exactly a duplicate but it seems for whatever reason on your side you have a very slow connection to discord, and that issue #3471 usually happens on slow connections when it takes to long to send a request like upload an attachment. But in your case since your bot is extremely slow with everything I guess you are getting that error from other http requests as well.

**Comment by LeManock** [comment] 2020-06-18 22:29
I contacted my internet operator and they added me to a **GOOD** line, but I have same problems. And my bot isn't hosted to my internet, I hosted my bot to a vps.

(I have good connections, Sending files in Discord take  normal duration. I touched **nothing**, and this problems appeared.)

Sometimes my bot is work with no problems. 80% isn't working.
