### ISSUE TITLE
Unable to play music file with either of recommended libraries

### ISSUE THREAD

**Issue by tiritto** [discordjs/discord.js#3784] opened 2020-02-13 17:33 UTC
**Please describe the problem you are having in as much detail as possible:**
I am simply unable to play any music as every attempt to results in an error. I've tested each one of the recommended libraries and none of them seems to be working. I've been trying to reinstall those libraries and always keep only one library installed at the time, however it didn't change anything.

**Include a reproducible code sample here, if possible:**
```js
VoiceChannel.join().then(connection => {
	const path = './musicfile.mp3';
	//const path = '/home/myuser/musicfile.mp3'; // Not working either...
	//const path = '~/musicfile.mp3'; // Not working either...
	connection.play(path, {
		volume: false,
		bitrate: 'auto'
	});
}).catch(console.error);
```
While using either `@discordjs/opus` or `node-opus` I get this:
```
Error: Could not find an Opus module! Please install @discordjs/opus, node-opus or opusscript.
    at new OpusStream (/srv/discord/node_modules/prism-media/src/opus/Opus.js:42:13)
    at new Encoder (/srv/discord/node_modules/prism-media/src/opus/Opus.js:130:5)
    at AudioPlayer.playPCMStream (/srv/discord/node_modules/discord.js/src/client/voice/player/BasePlayer.js:64:33)
    at AudioPlayer.playUnknown (/srv/discord/node_modules/discord.js/src/client/voice/player/BasePlayer.js:59:17)
    at VoiceConnection.play (/srv/discord/node_modules/discord.js/src/client/voice/util/PlayInterface.js:70:28)
    at /srv/discord/laura.js:269:35
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

And while using `opusscript` I get this instead:
```
TypeError: Cannot convert "null" to int
/srv/dis/node_modules/opusscript/build/opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){retur
```

**Further details:**
- discord.js version: Master (commit: a36f386)
- Node.js version: 12.15.0
- Operating system: Debian GNU/Linux 9.12
- Priority: Low. Apparently it's a rather uncommon problem.
- ffmpeg version: 3.2.14-1
- [x] I have also tested the issue on latest master, commit hash: a36f386

**Comment by tiritto** [comment] 2020-02-13 18:32
I would like to do a little followup on this issue. I think it's safe to say that ffmpeg is totally irrelevant for this problem since I am getting exactly the same error when using `createReadStream` that is claimed by documentation to bypass ffmpeg altogether.

```
VoiceChannel.join().then(connection => {
	const path = './musicfile.ogg';
	//const path = '/home/myuser/musicfile.ogg'; // Not working either...
	//const path = '~/musicfile.ogg'; // Not working either...
	connection.play(fs.createReadStream(path), {
		type: 'ogg/opus'
	});
}).catch(console.error);
```

**Comment by JMTK** [comment] 2020-02-13 20:50
The only time I've had those kind of issues is when the node version that my bot was executing on was different than the node version that I installed `node-opus` with. Otherwise you'd probably wanna join the Discord for more direct support

**Comment by tiritto** [comment] 2020-02-13 22:04
I've tried reaching out on discord but no one seems to know what might be the reason.
However, I found out that playing mp3 files works just fine on my personal machine. I still have no clue what might be causing those problems on my VPS. I think I've checked everything:
 - Same version of npm - Checked
 - Same version of node - Checked
 - Same version of all npm libraries - Checked
 - Same version of ffmpeg - Checked
 - Same folder structure - Checked

I am really confused about this issue.

**Comment by tiritto** [comment] 2020-02-13 23:48
After playing around with the code I've decided to make some changes directly in `/prism-media/src/opus/Opus.js` file to find something more about the issue. Thanks to that I have found out the reason why `@discordjs/opus` and `node-opus` were "invisible" for DiscordJS:

`@discordjs/opus` : `Error: Cannot find module '/srv/discord/node_modules/@discordjs/opus/prebuild/node-v79-linux-x64/opus.node'`
I've checked deeper and indeed, there is not even such folder as `prebuild` in the first place. I guess it's important to note that npm install worked just fine and there were no errors during installation.

`node-opus` : `Error: Could not locate the bindings file.`
I haven't investigated this one more.

`opusscript` : The biggest surprise here - it worked. I've changed my code back and forth few times but apparently the cause of this library error is located in loader function.

**Original loader function:**
```js
function loader(requireData, objMap = {}) {
  for (const [name, reqFn] of requireData) {
    try {
      const dep = require(name);
      const fn = reqFn ? reqFn(dep) : dep;
      return {
        [objMap.module || 'module']: dep,
        [objMap.name || 'name']: name,
        [objMap.fn || 'fn']: fn,
      };
    } catch (e) { }
  }
  return {};
};
```

**My custom loader function:**
```js
function myloader(requireData, objMap = {}) {
  for (const [name, reqFn] of requireData) {
    try {
      const dep = require(name);
      const fn = reqFn ? reqFn(dep) : dep;
      return {
        [objMap.fn || 'fn']: fn,
      };
    } catch (e) { 
      console.error("Loading of " + name + " failed!");
    }
  }
  return {};
};
```

After this change, running my bot and playing the file worked like a charm without any error.

**Comment by iCrawl** [comment] 2020-02-24 14:02
Can you set up a test repo for this?

**Comment by Blogshot** [comment] 2020-04-15 00:15
Hello,

I'm also experiencing this error. Today I converted all my bot's MP3s to OGG to eliminate FFMPEG. After changing my code according to documentation, the bot stopped playing audio and instead instantly jumps to leaving the channel.

I don't know if this helps, but here's my repository: https://github.com/Blogshot/trump-bot. This isn't a specific testing repo, but the error is reproducible.

**Comment by isolin** [comment] 2020-05-02 10:34
I encountered both issues mentioned above yesterday.
1. **@discordjs/opus** you can probably spot the problem after starting `node` and typing in `require("@discordjs/node")`. In my setup (Focal Fossa) the problem is that my version of libc6 is newer than the one supported by the package. I reported it over [here](https://github.com/discordjs/opus/issues/13).

2. **opusscript** throws an error that is caused by **prism-media** passing a null argument to opusscript. I found out how to hack it by editing one of the files in the node_packages... well atemporary solution that works. Follow the details in my [StackOverflow answer](https://stackoverflow.com/questions/60695216/how-to-resolve-typeerror-cannot-convert-null-to-int). It would be of course the best if a proper fix would be integrated to prism-media, so here is the [issue to follow](https://github.com/amishshah/prism-media/issues/45).

**Comment by isolin** [comment] 2020-05-02 10:41
@tiritto Your fix basically avoided **prism-media** to recognize **opusscript** by name, so the problematic `name === 'opusscript' ? null : frameSize` jumped to the false branch providing a vaild `int` instead of a `null`.

**Comment by amishshah** [comment] 2020-05-02 11:32
prism-media [v1.2.2](https://github.com/amishshah/prism-media/releases/tag/v1.2.2) has been released with a fix for this issue :)

**Closed** 2020-05-03 23:14 UTC
Labels: meta: dependencies, s: unverified, t: voice, type: bug
