### ISSUE TITLE
guildMemberAdd is not working anymore.

### ISSUE THREAD

**Issue by TheDevJulian** [discordjs/discord.js#5012] opened 2020-11-14 21:37 UTC
**Please describe the problem you are having in as much detail as possible:**
The event **guildMemberAdd** is not triggered anymore. I used the code from https://discord.js.org/#/docs/main/stable/examples/greeting but this is also not working. There is also no error log or any errors in my console.

**Include a reproducible code sample here, if possible:**

```js
client.on('guildMemberAdd', member => {
    console.log('This also does not work and or show in console.');
    // Send the message to a designated channel on a server:
    const channel = member.guild.channels.cache.find(ch => ch.name === 'algemeen');
    // Do nothing if the channel wasn't found on this server
    if (!channel) return;
    // Send the message, mentioning the member
    channel.send(`Welcome to the server, ${member}`);
});
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: v12.19.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: high, because now my bot is not working anymore.

**Comment by TheDevJulian** [comment] 2020-11-14 21:39
Also for the record when using `const channel = member.guild.channels.cache.get(channel-id-here);` it is also not working.

**Comment by SpaceEEC** [comment] 2020-11-14 21:46
> :gear:  **Events for privileged intents are not sent if not enabled:**
• Discords FAQ on this change: <https://dis.gd/gwupdate>
• your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
• your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
• you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: **update to v12**, we no longer support v11.
>
> **Symptoms you might be experiencing with discord.js**:
• member caches are empty     *(or only have very few entries)*
• user cache is empty      *(or has only very few entries)*
• fetching members times out
• login times out if you try to fetch all members on startup
• The client events `"guildMemberAdd"`, `"guildMemberRemove"`, `"guildMemberUpdate"` do not emit
• `Guild#memberCount` returns count as of ready

Closing this issue as it is a duplicate of  #4998, #4976, #4970, #4959, #4950, #4949, and probably more.

**Closed by SpaceEEC** 2020-11-14 21:46 UTC
Labels: s: duplicate
