### ISSUE TITLE
the event "guildMemberAdd" is not working.

### ISSUE THREAD

**Issue by biolix06** [discordjs/discord.js#5301] opened 2021-02-07 13:41 UTC
### the event "guildMemberAdd" is not working.

I try several times to relaunch the bot/change the code but it still doesn't work. Normally the bot is supposed to display something in the console and send a welcome message to the user but neither works, and there is no error in the console. 

```js
client.on('guildMemberAdd', member => {

      console.log(`User ${member.nickname} join!`);

   let embedNewUser = new Discord.MessageEmbed()
        .setColor('GREEN')
        .addField('Welcome! 🎉', `Bienvenu sur ${member.guild.name}, ${member.nickname}!\nJe suis RealDream|Bot et mon prefis est "%", n'hésite pas à faire %help pour obtenir la liste des commandes disponible 😉\n\nÀ bientôt et ammuse toi bien!`, true)
        .setThumbnail(member.user.displayAvatarURL({format : 'png', dynamic : true, size : 512}))
       .setFooter('RealDreamStudio official bot');

      member.createDM().then((c) => {
        c.send(embedNewUser).catch(console.error);
      }).catch(console.error);

    // updateMemberStats('785577759225151508', '797497564823552040');
    // updateLastBoost('785577759225151508', '797497626131693568');
    //  updateMemberBots('785577759225151508', '797497782009069589');
    });
```

**Further details:**

- discord.js version: last version
- Node.js version: v14.8.0
- Operating system: Windows (for test) / debian (for host)
- Priority this issue should have – please be realistic and elaborate if possible: This bug needs to be dealt with fairly quickly because the "guildMemberAdd" event is a very useful event for developers.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

Sorry if the translation is not good, I use a translator.

**Comment by Siris2408** [comment] 2021-02-07 13:59
The `guildMemberAdd` event wont fire if you dont have the `GUILD_MEMBERS` intent

**Comment by kyranet** [comment] 2021-02-07 14:08
Duplicate of  #4998, #4976, #4970, #4959, #4950, #4949, and probably more.

**Closed by kyranet** 2021-02-07 14:08 UTC
Labels: s: unverified, type: bug
