### ISSUE TITLE
Having a bot create several roles one after another assigns all of them the same .position

### ISSUE THREAD

**Issue by Drithyl** [discordjs/discord.js#3175] opened 2019-04-01 19:22 UTC
**Please describe the problem you are having in as much detail as possible:**
A bot creating multiple roles one after another through `guild.createRole()` will assign all of them with the same position (1 in my case), even on a guild with some other already existing roles.

Manually moving around the role hierarchy within the discord guild options immediately resolves this, but until that is done, all of the roles that were created that way remain with the same position, which is a problem when checking those positions for, say, permissions.

**Include a reproducible code sample here, if possible:**
```js

// Place your code here
guild.createRole({name: "firstRole"}).then(function(firstRole)
{
     guild.createRole({name: "secondRole"}).then(function(secondRole)
     {
          guild.createRole({name: "thirdRole"}).then(function(thirdRole)
          {
               //will all print 1 in my case
               console.log(firstRole.position);
               console.log(secondRole.position);
               console.log(thirdRole.position);
          }
     }
}
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.15.3
- Operating system: Windows 10

**Comment by SpaceEEC** [comment] 2019-04-05 14:24
This seems to be the intended behavior as Discord does not calculate a new position before a role was moved. (This probably is an optimization)

[`Role#position`](https://discord.js.org/#/docs/main/11.4.2/class/Role?scrollTo=position) (on `11.x`) is documented as "The position of the role from the API".
We do not do any changes to it on our own accord.

You want to use [`Role#calculatedPosition`](https://discord.js.org/#/docs/main/11.4.2/class/Role?scrollTo=calculatedPosition) which accounts for Discord's behavior.
Although while writing this response I found a potential bug within that getter, which should be fixed with #3184.

**Closed** 2019-04-08 16:24 UTC
Labels: s: Discord
