### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by HRK44** [discordjs/discord.js#8769] opened 2022-10-20 00:32 UTC
### Which package is this bug report for?

discord.js

### Issue description

I just started seeing this error message in my logs, I have the same code for multiple months and I noticed the behavior today.

discordjs v14.3.0 (tried as well with 14.6.0)
nodejs v16.13.1

I have a for loop that goes over the same guild and fetch the members, so this doesn't happen at bot connection time but on every loop iteration (after bot initially connected).

```
[674002] 2022-10-20T00:29:58.613Z warn: TypeError: Cannot read properties of undefined (reading 'send')
    at /home/xxx/git/xxx/api/node_modules/discord.js/src/managers/GuildMemberManager.js:504:24
```

which corresponds to the code in the GuildMemberManager.js : https://github.com/discordjs/discord.js/blob/aec44a0c93f620b22242f35e626d817e831fc8cb/packages/discord.js/src/managers/GuildMemberManager.js#L504

and my code that triggers it:

`await communityGuild.members.fetch().catch(err => logger.warn(err));`

### Package version

14.3.0

### Node.js version

v16.13.1

### Operating system

linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by Jiralite** [comment] 2022-10-20 00:38
Can you show how you are calling this? This is the most important information which you've left out.

**Comment by Jiralite** [comment] 2022-10-20 01:32
You've stated that yes - but in a minimal reproducible sample?

**Comment by HRK44** [comment] 2022-10-20 01:39
```
690969] 2022-10-20T01:32:00.618Z debug: Provided token: *******.*****.**************************************
[690969] 2022-10-20T01:32:00.620Z debug: Preparing to connect to the gateway...
[690969] 2022-10-20T01:32:00.623Z error: Provided token: ********.*****.**************************************
[690969] 2022-10-20T01:32:00.839Z debug: [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[690969] 2022-10-20T01:32:00.840Z debug: [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 990
[690969] 2022-10-20T01:32:00.844Z debug: [WS => Manager] Spawning shards: 0
[690969] 2022-10-20T01:32:00.845Z debug: [WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 10
    Encoding   : json
    Compression: none
[690969] 2022-10-20T01:32:00.845Z debug: [WS => Shard 0] Setting a HELLO timeout for 20s.
[690969] 2022-10-20T01:32:01.044Z debug: [WS => Shard 0] [CONNECTED] Took 199ms
[690969] 2022-10-20T01:32:01.046Z debug: [WS => Shard 0] Clearing the HELLO timeout.
[690969] 2022-10-20T01:32:01.046Z debug: [WS => Shard 0] Setting a heartbeat interval for 41250ms.
[690969] 2022-10-20T01:32:01.047Z debug: [WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 32767
[690969] 2022-10-20T01:32:01.201Z warn: TypeError: Cannot read properties of undefined (reading 'send'
....
```

some debug logs.


> You've stated that yes - but in a minimal reproducible sample?

That's all my code is doing, connect, fetch guild and fetch members > errors out with this error message

```typescript

 constructor() {
        this.client = new Client({ intents: [32767, 'GuildMembers'] });
 }

async init() {
        await new Promise<void>((resolve, reject) => {
            this.client.on('ready', () => {
                logger.info(`Discord bot ${this.id} connected`);
                resolve();
            });

            this.client.on('debug', err => {
                logger.debug(err);
                reject(err);
            });

            this.client.on('error', err => {
                logger.debug(err);
                reject(err);
            });

            void this.client.login(bot.token).catch(err => logger.warn(err));
        }).catch(err => logger.error(err));
}

 async sync() {
            for (const community of communities) {
                    if (community.guild) {
                        const communityGuild = await this.client.guilds.fetch(community.guild.id);

                        //refresh cache
                        await communityGuild.members.fetch().catch(err => logger.warn(err));
                  }
           }
 }

await init();
await sync();
```

**Comment by Jiralite** [comment] 2022-10-20 01:47
From those logs, it looks like your client is not ready - this can be identified when it logs `[WS => Shard 0] Shard received all its guilds. Marking as fully ready.`. Therefore, your implementation does not wait for your client to be fully ready when you are requesting guild members over the gateway.

**Comment by HRK44** [comment] 2022-10-20 02:06
Ok so the client is not ready when the 'ready' event is triggered? is there some other event I need to wait for the client to be 'ready'?

**Comment by Jiralite** [comment] 2022-10-20 02:13
The client is ready when that event is triggered. The issue here just seems to lie with how you implemented this, as I assume (as you stated) this isn't the entirety of your code. As a sidenote, copying & pasting your code does not yield this error for me.

**Comment by HRK44** [comment] 2022-10-20 02:24
It looks like some race condition is happening, sometimes the error doesn't trigger, sometimes it does (with the exact same code).

It seems that my 'ready' implementation is not correct and that my `sync` function (that also assigns some roles after the members fetch) runs before the client is fully ready thus triggering this error, then for some reason, even after the bot is fully connected (I see the log), the error stays on each loop iteration.

Other times, with the same implementation, my `sync` function runs before the client is not fully connected but it doesn't trigger this error for some reason.

I'll rework my connection flow but let me know if you think something might need to be fixed in this repo and if you need more info on the issue, thanks for you help

**Closed** 2022-10-20 09:59 UTC
Labels: invalid, packages:discord.js
