### ISSUE TITLE
Timeout - Shards With Unavailable Guilds Not Starting

### ISSUE THREAD

**Issue by tandpfun** [discordjs/discord.js#3956] opened 2020-03-17 18:20 UTC
**Please describe the problem you are having in as much detail as possible:**
When I start my bot sharded bot (in 4240 servers), one of the shards times out and stops starting. This issue is persistent across all versions of djs, including 12. The timeout happens around 90% of the time I start the shards. Here are the errors and messages I receive in the console for that shard.

`Error: Shard 1's Client took too long to become ready.`
`Error: Something took too long to do.`
`Left a guild called undefined.`

The last message is me logging the guild leave event, which also seems to be firing from that specific shard.

**Include a reproducible code sample here, if possible:**

My Sharding File (Code for version 11):
```js
const { ShardingManager } = require('discord.js');
const manager = new ShardingManager('./bot.js', { token: process.env.TOKEN });

manager.spawn(20); // Start 4 Shards
manager.on('launch', shard => console.log("Sharding Manager ➜".bold.brightYellow, `Launched shard ${shard.id}`.bold.brightCyan));
```
Code for `Ready` event:
```js
client.login(process.env.TOKEN).catch(console.error)

client.on('ready', (i, callback) => {
    functions.log(`Online in ${client.guilds.size} servers!`)

    blapi.handle(client, apiKeys, 10);

    setTimeout(() => {
        /* Bot Presence (Game and Status) */
        client.shard.fetchClientValues('guilds.size').then(results => {

            let servercount = results.reduce((prev, guildCount) => prev + guildCount, 0)

            client.user.setPresence({
                game: {
                type: 0,
                name: game + " | " + servercount
                //name: 'Discord API Error ➜ https://status.discordapp.com'
                },
                status: status
            });

            if (client.shard.id === 3) {
                Glenn.updateStats(servercount, client.shard.count);
                functions.postStats(client)
                functions.log(`Posted ${servercount} servers!`)
            }
        })
    },60000);
});
```

The error is persistent across different IP addresses and computers, and I get no email from discord.

**Further details:**

- discord.js version: 11.4.2, 11.5.1, 11.6.1, 12, 12.0.2
- Node.js version: v12.15.0
- Operating system: Ubuntu & Mac
- Priority this issue should have – please be realistic and elaborate if possible: Not sure...

- [x] I have also tested the issue on latest master, commit hash:

**Comment by TheMonsters29** [comment] 2020-03-17 21:11
i have get same error 
![image](https://user-images.githubusercontent.com/43083436/76902391-f3131880-68ac-11ea-844c-49b58bd02d20.png)

**Comment by Linck2718** [comment] 2020-03-17 21:12
Noticed the exact same issues yesterday on a ShardingManager running 11 shards.

It really hurts my userbase.
Please help!

**Comment by tandpfun** [comment] 2020-03-17 21:48
This seems to have to do with shards with unavalible guilds, which would explain leaving an undefined guild.

**Comment by tandpfun** [comment] 2020-03-17 21:58
Pressed close instead of comment, whoops!

**Comment by Woeler** [comment] 2020-03-20 00:30
Same issue here. Seems to be indeed unavailable guilds causing this.

**Comment by floodlock** [comment] 2020-03-20 00:34
the unavailable guilds seems to completely stop bots from connecting shaded or not

**Comment by razpeitia** [comment] 2020-03-20 02:43
Running an small bot (no shards) and it's unable to start because of this. I have to manually reset it until it becomes available again.

**Comment by Hentaiartz** [comment] 2020-03-20 07:06
Same issue here.

**Comment by timotejroiko** [comment] 2020-03-20 09:29
The workaround for this issue is to manually run triggerReady(). You can do it on a timer like this for example (for v11):

```js
setTimeout(() => {
    client.ws.connection.triggerReady()
},30000)
```

This will force it to become ready after 30 seconds no matter what.
Not sure if this is the best way to do it, but it seemed to work for many people.

**Comment by Woeler** [comment] 2020-03-20 10:48
> The workaround for this issue is to manually run triggerReady(). You can do it on a timer like this for example (for v11):
> 
> ```js
> setTimeout(() => {
>     client.ws.connection.triggerReady()
> },30000)
> ```
> 
> This will force it to become ready after 30 seconds no matter what.
> Not sure if this is the best way to do it, but it seemed to work for many people.

Can confirm that this solved my problem for now. The broken shard is working again.

**Comment by TheMonsters29** [comment] 2020-03-20 11:00
> The workaround for this issue is to manually run triggerReady(). You can do it on a timer like this for example (for v11):
> 
> ```js
> setTimeout(() => {
>     client.ws.connection.triggerReady()
> },30000)
> ```
> 
> This will force it to become ready after 30 seconds no matter what.
> Not sure if this is the best way to do it, but it seemed to work for many people.

where should i put this

**Comment by timotejroiko** [comment] 2020-03-20 11:14
> where should i put this

anywhere in your bot's main file, ie: ```js
let client = new Discord.Client();

setTimeout(() => {
    client.ws.connection.triggerReady()
},30000)

client.login();
```

**Comment by TheMonsters29** [comment] 2020-03-20 11:19
> > where should i put this
> 
> anywhere in your bot's main file, ie:
> 
> ```js
> let client = new Discord.Client();
> 
> setTimeout(() => {
>     client.ws.connection.triggerReady()
> },30000)
> 
> client.login();
> ```

thx

**Comment by tandpfun** [comment] 2020-03-20 16:35
This issue is an issue for version 11 which should be fixed in version 12 according to the DJS staff.

Solution:
Quoting @timotejroiko:

> The workaround for this issue is to manually run triggerReady(). You can do it on a timer like this for example (for v11):
> 
> ```js
> setTimeout(() => {
>     client.ws.connection.triggerReady()
> },30000)
> ```
> 
> This will force it to become ready after 30 seconds no matter what.
> Not sure if this is the best way to do it, but it seemed to work for many people.

I'm closing this thread now!

**Comment by iCrawl** [comment] 2020-03-20 16:41
This is definitely not a "real" solution. Hence keeping it open.

**Comment by Linck2718** [comment] 2020-03-20 16:54
If it is true, that it is fixed in v12, then this is a real solution and can be closed i'd say.

**Comment by CatsMiaow** [comment] 2020-04-01 01:48
discord.js v12.1.1
```sh
Error [SHARDING_READY_TIMEOUT]: Shard 10's Client took too long to become ready.
    at Timeout.onTimeout (/home/bot/node_modules/discord.js/src/sharding/Shard.js:160:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  [Symbol(code)]: 'SHARDING_READY_TIMEOUT'
}
```

**Comment by jerbgit** [comment] 2020-04-14 18:33
Any update/fix on this?

**Comment by tandpfun** [comment] 2020-04-14 19:41
Not currently, but a temporary solution is above for version 11:

> The workaround for this issue is to manually run triggerReady(). You can do it on a timer like this for example (for v11):
> 
> ```js
> setTimeout(() => {
>     client.ws.connection.triggerReady()
> },30000)
> ```
> 
> This will force it to become ready after 30 seconds no matter what.
> Not sure if this is the best way to do it, but it seemed to work for many people.

**Comment by CatsMiaow** [comment] 2020-04-16 01:21
Is there any way for version 12?

**Comment by azbaron** [comment] 2020-04-18 05:42
Getting this error in v12.1.1

**Comment by wonderlandpark** [comment] 2020-04-24 08:21
+1

**Comment by Blogshot** [comment] 2020-04-26 12:15
Got this error in the latest 12.2.0. Here are my findings after a bit of testing:

I have overridden the default timeout via `manager.spawn(manager.totalShards, 5500, -1);`.

As stated in https://github.com/discordjs/discord.js/blob/master/src/sharding/ShardingManager.js, setting the last parameter to `-1` will disable the timeout completly. The other parameters are the default values.

I now no longer get the error message. However, it seems like the shards are not getting online at all.
```
manager.on('launch', shard => {
    logger.log(null, "=== Launched shard " + shard.id);
});
```
is not getting triggered and my bot is listed as offline, even after waiting for well over 10 minutes. 

This indicates that there is an issue with the login itself. According to https://discordapp.com/developers/docs/change-log, there has been no API changes since March 3rd.
I have then verified my token on https://discordapp.com/developers/applications. I regenerated the token and used a newly created one in case my old token got banned.

After al this, it seems to me that there is a bigger underlying issue here.

**Comment by SpaceEEC** [comment] 2020-04-26 13:43
There no longer is a `'launch'` event on v12, the only event the sharding manager currently has is `'shardCreate'`, see [`ShardingManager#shardCreate`](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=e-shardCreate).

Without further info (read: logs) there is nothing that can be done about this really.

Probably relevant to log:
- Everything from [`Shard`](https://discord.js.org/#/docs/main/stable/class/Shard)
- [`Client#debug`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-debug)

**Comment by Blogshot** [comment] 2020-04-26 20:34
Thank you @SpaceEEC for the information.

[`Client#debug`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-debug) produced a helpful log:
```
[...]
[4/26/2020 10:13:34 PM]  [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 11
[4/26/2020 10:13:34 PM]  [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 0
[4/26/2020 10:13:34 PM]  [WS => Manager] Spawning shards: 0
[4/26/2020 10:13:34 PM]  [WS => Manager] Exceeded identify threshold. Will attempt a connection in 13919462ms
[...]
```

In my case, my bot did a bootloop in the middle of the night, causing Discord to ratelimit my app for 24h according to their [documentation](https://discordapp.com/developers/docs/topics/gateway#identifying). 
I will edit this reply as soon as I have tested again by tomorrow.

**Comment by vypr** [comment] 2020-08-30 00:34
Getting this on v12.3.1

**Comment by akirablaid** [comment] 2020-11-28 23:24
+1

**Comment by sinkaroid** [comment] 2020-12-24 13:48
any update/fix on this?

**Comment by Jade3375** [comment] 2020-12-24 14:14
Issue seemed to be fixed a while ago, my bots been running fine for a long time now without running into it

**Comment by Pudochu** [comment] 2021-01-09 13:11
I have a this problem...

**Comment by OtaquKing1** [comment] 2021-01-13 18:12
Any update/fix on this?

**Comment by tandpfun** [comment] 2021-01-13 18:17
Haven't seen any of these issues in DJS v12

**Comment by Curse345** [comment] 2021-02-12 22:52
Is there a fix for this? I need a fix for v12 ASAP please

**Comment by tandpfun** [comment] 2021-02-13 03:15
> Is there a fix for this? I need a fix for v12 ASAP please

Discord is currently having an issue where sharded bots are unable to log in. It's not on their status page, so idk if it's been fixed or not. Something to do with GCP.

**Comment by ggdiam** [comment] 2021-02-13 05:53
Seems fixed now, working for me

**Comment by RJain12** [comment] 2021-02-19 17:43
Still having this issue as of now.

**Comment by tandpfun** [comment] 2021-02-19 17:44
Was about to mention it. Having issues as well. I think these are a Discord problem since I am having them too.

**Comment by Helixable** [comment] 2021-02-20 16:33
> Same issue still in 12. "triggerready" does not function in 12 so that's not a solution unfortunately.

Yeah I have the same issue. Still have no idea what's happening. One of my shards just always returns null.

**Comment by HellpMe** [comment] 2021-02-25 18:03
+1

**Comment by cobsidian-crim** [comment] 2021-03-01 17:06
this is STILL a issue stop ignoring it

**Comment by RJain12** [comment] 2021-03-01 18:34
I was suggested this potential solution in the discord.js server.
Consider attempting `client.login()` as early as possible (before your database init., etc.)

For me, this resolved the issue.

**Comment by Ramzi-Sah** [comment] 2021-03-01 21:36
same issue here :/ SHARDING_READY_TIMEOUT, its not an API ban wget -S https://discord.com/api/ works fine.

**Comment by cobsidian-crim** [comment] 2021-03-01 23:56
> I was suggested this potential solution in the discord.js server.
> Consider attempting `client.login()` as early as possible (before your database init., etc.)
> 
> For me, this resolved the issue.

ill try that thank you!

**Comment by cobsidian-crim** [comment] 2021-03-02 00:08
> I was suggested this potential solution in the discord.js server.
> Consider attempting `client.login()` as early as possible (before your database init., etc.)
> 
> For me, this resolved the issue.

nope, i kept getting this error
```js
0|index  | [WS => Shard 1] An open connection was found, attempting an immediate identify.
0|index  | [WS => Shard 1] [IDENTIFY] Shard 1/17
0|index  | [WS => Shard 1] [INVALID SESSION] Resumable: false.
0|index  | [WS => Shard 1] Failed to connect to the gateway, requeueing...
0|index  | [WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
0|index  | Preparing to connect to the gateway...
```

**Comment by tandpfun** [comment] 2021-03-02 00:39
If you're coming to this page, there's likely an ongoing issue with sharding at the moment. I'd ask about it in the Discord Developers server, as it is the same timeout error for an issue logging into the gateway. The cause of the reason for this bug for this issue has been fixed in v12. Any issues with the same errors are probably something else.

**Comment by cobsidian-crim** [comment] 2021-03-02 01:17
in the Discord API server they havent said anything about it, unlike when there WAS a sharding issue with the API

**Comment by cobsidian-crim** [comment] 2021-03-02 02:31
> > I was suggested this potential solution in the discord.js server.
> > Consider attempting `client.login()` as early as possible (before your database init., etc.)
> > For me, this resolved the issue.
> 
> This worked perfectly for me!
> 
> I just added it to the beginning of my shard file instead of the end

i put it right here but it didnt fix anything
```js
const Discord = require("discord.js");
const client = new Discord.Client();

client.on('debug', console.log)
      .on('warn', console.log)

const botsettings = require('./botsettings.json');
const prefix = "?"
client.login(botsettings.token);```

**Comment by Ramzi-Sah** [comment] 2021-03-02 10:57
this worked for me => 

Got this error: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.?
The spawnTimeout can be set to  -1 or Infinity to prevent future errors:
https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=spawn. This can also happen if you call ShardingManager#spawn before attaching a listener to the shardCreate event which could create a race condition possibly preventing the shard 0 to perform a successful launch.

**Comment by eyooooo** [comment] 2021-03-31 17:49
all of the sudden my bot has been getting this error

```
debug -> Provided token: myToken42069
debug -> Preparing to connect to the gateway...
debug -> [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
debug -> [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 0
debug -> [WS => Manager] Spawning shards: 0
debug -> [WS => Manager] Exceeded identify threshold. Will attempt a connection in 20516803ms
```

I have a script that runs once a minute that logs in to discord and sends a few alerts then spins down. This script ran for weeks with no issues. suddenly yesterday i am getting the above error and getting 6+ hour bans. 

wtf?

**Comment by tandpfun** [comment] 2021-03-31 19:22
> all of the sudden my bot has been getting this error
> 
> ```
> debug -> Provided token: myToken42069
> debug -> Preparing to connect to the gateway...
> debug -> [WS => Manager] Fetched Gateway Information
>     URL: wss://gateway.discord.gg
>     Recommended Shards: 1
> debug -> [WS => Manager] Session Limit Information
>     Total: 1000
>     Remaining: 0
> debug -> [WS => Manager] Spawning shards: 0
> debug -> [WS => Manager] Exceeded identify threshold. Will attempt a connection in 20516803ms
> ```
> 
> I have a script that runs once a minute that logs in to discord and sends a few alerts then spins down. This script ran for weeks with no issues. suddenly yesterday i am getting the above error and getting 6+ hour bans.
> 
> wtf?

Off topic, though it looks like your bot was restart looped. Discord rolled out stage channels that had some issues with discord.js  bots crashing. I'd open a new issue for this or wait for them to add support.

**Comment by j-dogcoder** [comment] 2021-04-08 23:12
Still not working for me. Any ideas?

**Comment by tandpfun** [comment] 2021-04-08 23:16
The cause of this original issue has been fixed in DJS v12. If you are in djs v12, it's likely something else. Make sure you aren't temporarily gateway blocked or something with `curl -I https://discord.com/api/gateway`. Is your entire bot offline? Just one shard? What is being logged?

**Comment by j-dogcoder** [comment] 2021-04-08 23:19
It is logging
```
(node:60944) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/sharding/Shard.js:163:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tandpfun** [comment] 2021-04-08 23:21
> I was suggested this potential solution in the discord.js server.
> Consider attempting `client.login()` as early as possible (before your database init., etc.)
> 
> For me, this resolved the issue.

Try this maybe? If this doesn't work, pls answer all my questions I asked in the comment above.

**Comment by j-dogcoder** [comment] 2021-04-08 23:23
@tandpfun That doesn't work. I only have one shard, and my bot appears to be online

**Comment by tandpfun** [comment] 2021-04-08 23:24
Did you check if you were temporarily IP banned with the curl command I sent above?

**Comment by j-dogcoder** [comment] 2021-04-08 23:25
The curl command worked just fine.

**Comment by tandpfun** [comment] 2021-04-08 23:26
> this worked for me =>
> 
> Got this error: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.?
> The spawnTimeout can be set to -1 or Infinity to prevent future errors:
> https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=spawn. This can also happen if you call ShardingManager#spawn before attaching a listener to the shardCreate event which could create a race condition possibly preventing the shard 0 to perform a successful launch.

Read this to see if any of this helps you.

**Comment by j-dogcoder** [comment] 2021-04-08 23:27
How do I give it a timeout?

**Comment by tandpfun** [comment] 2021-04-08 23:30
Read the docs link in the comment. If this doesn't work, maybe wait and see if the issue solves itself. I won't be able to help ya with everything, but there's a lot of solutions if you scroll up in this issue. Ask in the djs server if ya need more help.

**Comment by j-dogcoder** [comment] 2021-04-09 00:49
@tandpfun Could you perhaps look at the code and see if you can figure out the error? I have done some extensive debugging and cannot figure it out (the discord server wasn't very helpful) You can find the repo at [https://github.com/Heptagram-Bot/Heptagram](https://github.com/Heptagram-Bot/Heptagram)

**Comment by tandpfun** [comment] 2021-04-09 04:38
There's not much I can do, it's a normal shard start timeout error. If it just happened all of a sudden, maybe try it again in a bit and see if it works.

**Comment by adrifcastr** [comment] 2021-04-09 09:10
> @tandpfun That doesn't work. I only have one shard, and my bot appears to be online

If you only need one shard why are you sharding at all? Just don't unless you require at least 2 shards. Running on one shard is essentially just overcomplicating things for no reason. Just turn the sharding off.

**Comment by Blogshot** [comment] 2021-04-09 09:57
> > @tandpfun That doesn't work. I only have one shard, and my bot appears to be online
> 
> If you only need one shard why are you sharding at all? Just don't unless you require at least 2 shards. Running on one shard is essentially just overcomplicating things for no reason. Just turn the sharding off.

I disagree. A bot can go viral and supporting sharding from the get-go is a good idea to prevent downtimes if large growth is possible/anticipated.

**Comment by adrifcastr** [comment] 2021-04-09 10:06
> I disagree. A bot can go viral and supporting sharding from the get-go is a good idea to prevent downtimes if large growth is possible/anticipated.

No. Unless your bot is at about reaching 2000 guilds not a single thought about sharding needs to be on your mind. You seem to fundamentally misunderstand what sharding is and why it is being used.

**Comment by Blogshot** [comment] 2021-04-09 10:39
> > I disagree. A bot can go viral and supporting sharding from the get-go is a good idea to prevent downtimes if large growth is possible/anticipated.
> 
> No. Unless your bot is at about reaching 2000 guilds not a single thought about sharding needs to be on your mind. You seem to fundamentally misunderstand what sharding is and why it is being used.

Did you read and understand my comment at all? I deliberately added the parts about going viral and large growth. Also, your point of "why do you do this at all" is derailing the thread and not contributing to a solution of the issue at hand.

**Comment by adrifcastr** [comment] 2021-04-09 11:47
> Did you read and understand my comment at all? I deliberately added the parts about going viral and large growth. Also, your point of "why do you do this at all" is derailing the thread and not contributing to a solution of the issue at hand.
your point is null and void. even when you reach 2K guilds you can just turn on internal sharding til you reach 20k, which despite enabling requires no further code changes or 'preventing down times if it goes viral'. Unless you require more then 10 shards you as I  said, need not think a single second about process sharding.

As I said, the solution to the issue at hand is as follows: process sharding is causing issues -> no need for process sharding -> disable it = no more issues.

**Comment by Blogshot** [comment] 2021-04-09 12:21
> your point is null and void. even when you reach 2K guilds you can just turn on internal sharding til you reach 20k, which despite enabling requires no further code changes or 'preventing down times if it goes viral'. Unless you require more then 10 shards you as I said, need not think a single second about process sharding.

And again: You don't seem to grasp what I mean by going viral. My Trump-Bot exceeded 16.000 guilds at one point and I have always considered it a shitpost-bot. More than 20k can easily be achieved if a bot gets popular.

> the solution to the issue at hand is as follows: process sharding is causing issues -> no need for process sharding -> disable it = no more issues.

"If you have problems, just don't use it!" is **not** a solution, but at best a workaround. The solution is to fix sharding and not to ignore the issue because you believe it to be a non-issue.

**Comment by anandre** [comment] 2021-04-09 12:31
Please take the argument about "needing" to shard somewhere else and keep this to the actual problem at hand. If this happens when sharding at 2000 guilds or 20, it doesn't really matter.

There is also a channel dedicated to sharding support.

**Comment by tandpfun** [comment] 2021-04-09 15:04
I guess try without sharding and try with multiple shards. You can always client shard (if I remember what that's called).

**Comment by CarsonGamer** [comment] 2021-04-19 16:13
> I guess try without sharding and try with multiple shards. You can always client shard (if I remember what that's called).

How would I do this I currently have the same issue as everyone else and would like to finish my discord bot by the end of the school year so this really puts a damper on my discord bot...

**Comment by fishuke** [comment] 2021-05-13 00:53
Same issue here. My bot doesnt get started sometimes i see 900+ unavailable server. Sometimes starts but goes offline after couple seconds.

**Comment by fishuke** [comment] 2021-05-13 02:12
Just fixed after couple hours.

**Comment by srabouin** [comment] 2021-05-31 14:06
Also seeing this issue, I updated to the latest stable 12.5.3 and still seeing this issue. I added just now the -1 timeout, will see if this helps but doesn't seem like the proper fix. My bot is in almost 5000 server so sharding is not optional...

**Comment by Helixable** [comment] 2021-05-31 20:41
My bot's been offline for two weeks now because of this issue. I've tried everything here :(

**Comment by Pudochu** [comment] 2021-06-13 12:06
**I fixed this problem for my shard.js** 😇🥳
```js
const settings = require('./settings.json');
const { ShardingManager } = require('discord.js')

const manager = new ShardingManager('./bot.js', {
    totalShards: "auto", // or number e.g ( totalShards: 10 )
    token: settings.token, // or token e.g ( token: "YOUR BOT TOKEN" )
    spawnTimeout: -1,
    respawn: true
});
manager.on('shardCreate', shard => console.log(`Launched shard ${shard.id}`));

manager.spawn(manager.totalShards, 5500, -1).catch(e => console.log(e))
```

**Comment by Poly-Pixel** [comment] 2021-07-22 18:19
Is this still an issue?

**Comment by j-dogcoder** [comment] 2021-07-23 19:33
Also wondering that.

**Comment by SpaceEEC** [comment] 2021-12-02 09:26
Closing this issue as the reported behavior has been removed from discord.js with (I think) v12.

The cause for this issue likely was a soft-deleted guild (`Left a guild called undefined`), which caused the client to become stuck waiting for it to become available and eventually time out (`Something took too long`).
This then cascaded into the sharding manager, which also was waiting for the client to become ready, causing a stop to spawning new shards after one shard's ready event timed out. (`Shard 1's Client took too long to become ready.`)

This has been fixed by readying the client after 15 seconds after receiving the last guild when there are unavailable guilds left.
(=> `Something took too long` was removed :tada:)

**Closed by SpaceEEC** 2021-12-02 09:26 UTC
Labels: bug, gateway, need repro, sharding
