### ISSUE TITLE
VoiceState.speaking returns null

### ISSUE THREAD

**Issue by Wengiel31** [discordjs/discord.js#4318] opened 2020-05-27 00:32 UTC
So i've been doing this Discord bot in Discord.js for a couple of days now and I have a problem 'cos (as it says in the title) client.voice.connections.first().voice.speaking returns null, but this little sucker: [https://discord.js.org/#/docs/main/stable/class/VoiceState](https://discord.js.org/#/docs/main/stable/class/VoiceState) says it should work. I've alreay posted it on a couple of Discord programming-related servers (including official Discord API server) and the only reply I got was to open an issue so here I am. **I would like to also point out that the bot IS connected to a voice channel** (obviously), as well as everything is nice and updated (I use the newest versions of everything - from node and npm to modules themselves)

A little bit of very professional and efficient code I've created 100% myself without any help (copying) from StackOverflow:
```js
let connections = client.voice.connections.array();
let connection = connections[0];
console.log(connection.voice.speaking);
```

AND

```js
let connections = client.voice.connections.array();
let connection = connections[0];
console.log(connection.voice);
```
returns:
```js
VoiceState {
  guild: <ref *1> Guild {
    members: GuildMemberManager {
      cacheType: [Function: Collection],      
      cache: [Collection [Map]],
      guild: [Circular *1]
    },
    channels: GuildChannelManager {
      cacheType: [Function: Collection],      
      cache: [Collection [Map]],
      guild: [Circular *1]
    },
    roles: RoleManager {
      cacheType: [Function: Collection],      
      cache: [Collection [Map]],
      guild: [Circular *1]
    },
    presences: PresenceManager {
      cacheType: [Function: Collection],      
      cache: [Collection [Map]]
    },
    voiceStates: VoiceStateManager {
      cacheType: [Function: Collection],      
      cache: [Collection [Map]],
      guild: [Circular *1]
    },
    deleted: false,
    available: true,
    id: '701958810624983131',
    shardID: 0,
    name: 'WengielBot 7.0 Development server',
    icon: 'b47941217711eb71b01bc59c74acc368', 
    splash: null,
    region: 'europe',
    memberCount: 2,
    large: false,
    features: [],
    applicationID: null,
    afkTimeout: 300,
    afkChannelID: null,
    systemChannelID: '701958811073904690',
    embedEnabled: undefined,
    premiumTier: 0,
    premiumSubscriptionCount: 0,
    verificationLevel: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 0,
    joinedTimestamp: 1587430476866,
    defaultMessageNotifications: 'ALL',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    vanityURLCode: null,
    description: null,
    banner: null,
    rulesChannelID: null,
    publicUpdatesChannelID: null,
    ownerID: '260384981371584522',
    emojis: GuildEmojiManager {
      cacheType: [Function: Collection],
      cache: Collection(0) [Map] {},
      guild: [Circular *1]
    }
  },
  id: '701958388011237447',
  serverDeaf: false,
  serverMute: false,
  selfDeaf: false,
  selfMute: false,
  sessionID: 'b18847c0e880bff5b154f4fbd545f114',
  streaming: false,
  channelID: '701958811073904691'
}
```

**Further details:**
- discord.js version: 12.2.0
- Node.js version: 13.8.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Sardonyx78** [comment] 2020-05-27 11:10
According to that VoiceState it doesnt return null. It is undefined

**Comment by ApexFelix** [comment] 2020-05-27 11:31
> According to that VoiceState it doesnt return null. It is undefined

I agree with you

**Comment by iCrawl** [comment] 2020-06-19 10:21
Duplicate of #4273

**Closed by iCrawl** 2020-06-19 10:21 UTC
Labels: s: unverified, type: bug

**Comment by gregz07** [comment] 2021-05-23 16:31
Hey guys, why has this been closed ? Still doesn't seem fixed, I have the same problem as OP. It's still returning null when the bot is speaking.
