### ISSUE TITLE
Unable to connect to voice channel

### ISSUE THREAD

**Issue by juancarlovieri** [discordjs/discord.js#4622] opened 2020-07-08 08:20 UTC
I am using this bot to play a certain song, after I test it locally, it's fine but when I test it on the kids this happens:

```
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/voice/VoiceConnection.js:304:26)
    at /home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/voice/VoiceConnection.js:325:61
    at Timeout.<anonymous> (/home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/voice/VoiceConnection.js:304:26)
    at /home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/voice/VoiceConnection.js:325:61
    at Timeout.<anonymous> (/home/s/sergio-v/git/vieribotglobal/Discord/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}

```
this is my code:
```js
const channel = bot.channels.cache.get("688603706039730326");
  if (!channel) return console.error("The channel does not exist!");
  channel.join().then(connection => {
    console.log("Successfully connected.");
    connection.play(ytdl('https://youtu.be/hGlyFc79BUE')).on("finish", () =>{
      play();
    }).on("error", error => console.error(error));
  }).catch(e => {
    console.log('error');
    console.error(e);
  });
```

**Further details:**

- discord.js version: latest
- Node.js version: latest
- Operating system: local=macos, server=ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by yuto0214w** [comment] 2020-07-08 15:52
What server are you using? Heroku? Glitch?

Anyway, I think this is duplicate of #2979

**Comment by juancarlovieri** [comment] 2020-07-08 17:11
@yuto0214w  I'm hosting on my own server

**Comment by yalin** [comment] 2020-07-15 03:36
In https://github.com/discordjs/discord.js/issues/2979#issuecomment-457269699 "EDIT" part; it is mentioned to change the region of voice channel and it worked with me. I changed the guild region to another place, then back to the previous. But of course, this is a temporary solution.

**Comment by alhassanv** [comment] 2020-07-28 17:32
I used to have this issue locally, it's related to your connection to the discord api, not anything to do with discord.js.

**Comment by juancarlovieri** [comment] 2020-07-29 00:33
alright then it seems to be a problem with my connection, I'll close this issue

**Closed** 2020-07-29 00:33 UTC
Labels: s: unverified, type: bug
