### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by LukaHietala** [discordjs/discord.js#8167] opened 2022-06-24 12:22 UTC
### Which package is the feature request for?

discord.js

### Feature

I wish that the Discord JS had support for the new Javascript runtime called `Deno`. Deno supports Typescript out of the box and it also has some other cool features.

### Ideal solution or implementation

Support for the Deno runtime environment in addition to Node.js.

**Comment by almeidx** [comment] 2022-06-24 12:25
Duplicate of #7065

**Closed** 2022-06-24 12:27 UTC
Labels: duplicate, packages:discord.js
