### ISSUE TITLE
msg.author.presence returning nothing.

### ISSUE THREAD

**Issue by lars0403** [discordjs/discord.js#2949] opened 2018-11-15 18:01 UTC
**Please describe the problem you are having in as much detail as possible:**

I'm trying to let my bot read the game of an user, but it's not working.
I'm trying to use my code below, but it's returning the error that i can't send empty message.
Even though i let it return when there is no message 🤔 

**Include a reproducible code sample here, if possible:**
```js

    if (msgCase.startsWith(`${PREFIX}status`)) {
        let userStatus = msg.member.presence;
        if (!userStatus) return msg.channel.send('You are playing nothing currently.');
        msg.channel.send(userStatus);
    }

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.13.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Low priority.

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment] 2018-11-15 18:07
[`GuildMember#presence`](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=presence) is a [`Presence`](https://discord.js.org/#/docs/main/stable/class/Presence), which is not a valid [`MessageOptions`](https://discord.js.org/#/docs/main/stable/typedef/MessageOptions) or a [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String);
You can not directly [`TextChannel#send`](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=send) it.

You need to manually build a string containing the information you want to get from it and send that.

---

Note: `newest` is not a valid discord.js version.
Currently the `newest` is `11.4.2`, but that will change with the next release and your info will be misleading then.

---

Closing this, as this is not a bug or feature request.
For further questions regarding this ask for help in Discord - https://discord.gg/bRCvFy9

**Closed by SpaceEEC** 2018-11-15 18:07 UTC
