### ISSUE TITLE
Typing forever (channel.startTyping)

### ISSUE THREAD

**Issue by aziznatour** [discordjs/discord.js#2283] opened 2018-01-22 00:53 UTC
**Please describe the problem you are having in as much detail as possible:**

I'm forwarding typing events across different channels and sometimes the typing does not stop and keeps going on forever.

**Include a reproducible code sample here, if possible:**
```js

// startTyping event and condition ->
channel.startTyping(3);

// stopTyping event and condition ->
channel.stopTyping(true);

// tried adding a setTimeout that calls stopTyping() ->
client.setTimeout(typingStopper, 2000, channel);

// and even a command to force stopping
// on comand ->
typingStopper(channel);

// typingStopper looks like this
const typingStopper = function(channel)
{
   channel.stopTyping(true);
};
```

So basically, `startTyping` is called a few times and doesn't stop even when `stopTyping` is called by: `stopTyping` event, `stopTyping` function, `stopTyping` command or `stopTyping` timer

**Further details:**

- discord.js version: 1.13 stable
- node.js version: 8.*
- Operating system: tested on win7 and debian
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by DudeVoid** [comment] 2018-01-22 08:56
🤔

**Comment by SpaceEEC** [comment] 2018-01-22 13:12
This should be fixed by https://github.com/discordjs/discord.js/commit/8df1ac9920a20d74c7d5cd15ee0124f6e7236abc.

Calling startTyping a second (or more) time(s) created a new entry and overwrote the old one instead of just incrementing it.
Those older entries' timeouts couldn't be cleared anymore, this will now just increment/set the already existing entry and not create more anymore.

**Comment by aziznatour** [comment] 2018-01-25 16:08
@SpaceEEC it seemed to have been fixed for a while but I realized the issue still exists - can you look into it?

**Comment by SpaceEEC** [comment] 2018-01-25 16:52
Anything else to reproduce or still the old procedure?

**Comment by Lewdcario** [comment] 2018-02-01 22:00
Closing because it doesn't appear to be reproducible.

**Closed by Lewdcario** 2018-02-01 22:00 UTC
Labels: p: low, t: REST, type: bug

**Comment by Maddoxkkm** [comment] 2018-02-19 07:02
My bot have been encountering the same problem. 

```javascript
message.channel.startTyping();
//do my stuff here
message.channel.stopTyping(true);
```

when the above code is used on the affected channel, the typing indicator stopped briefly but began to restarted typing again after a few seconds.

I have been notified of this bug by the users over and over again.

**Comment by aziznatour** [comment] 2018-02-19 10:12
@Maddoxkkm I think the problem is DM channels or cross-shard typing forwarding, make sure the channel exists/reachable before calling the startTyping - also add a timer of 5 seconds to cancel it in case stopTyping was not recognized to ensure it will stop.

**Comment by Maddoxkkm** [comment] 2018-02-19 12:35
this whole thing was triggered by this
```javascript
bot.on('message', function(message){
})
```

so the channel must exist (because that's where the message come from, right?)

and this only happens in non-DM channels.... haven't had it happening in DM channels just yet.
shards is also out of the question - my bot is only in 500 servers, and I have no idea how to shard.

I might add another function to make sure it typing if it finds the bot to be typing after a few seconds.

**Comment by aziznatour** [comment] 2018-02-19 12:43
@Maddoxkkm oh I forgot to mention that make sure you ignore bot messages otherwise it will cause a loop of typing - e.g:

```
bot.on('message', function(message){
   // ignore messages by bots
   if (message.author.bot) return;

   // otherwise, start typing
   message.channel.startTyping();

   // optional timeout after 5 seconds
   setTimeout(message.channel.stopTyping, 5000);

   // example to call stopTyping with callback/promise
   doSomething.then(()=> message.channel.stopTyping());
});
```

**Comment by Maddoxkkm** [comment] 2018-02-19 21:23
~~sorry for making things complicated~~
the startTyping and stopTyping only when certain commands are used. which shouldn't be triggered by every single message everyone sent.

**Comment by Maddoxkkm** [comment] 2018-03-03 05:19
Anyway new things came in. 
![image](https://user-images.githubusercontent.com/24591852/36930856-5a20f6aa-1efe-11e8-9394-78fdcd1751c1.png)

```javascript
    if(message.content.toUpperCase().startsWith(prefix.toUpperCase() + "ISTYPING")){
        message.channel.send(`Typing in this channel: ${SerBot.user.typingIn(message.channel)}`);
    }
    if(message.content.toUpperCase().startsWith(prefix.toUpperCase() + "STOPTYPING")){
        message.channel.stopTyping(true);
    }
```

Apparently this is something to do with the Typing status between the bot and Discord not synchronized?

**Comment by Maddoxkkm** [comment] 2018-03-03 07:48
I now have a reproducible code for the Forever Typing issue:
```javascript
const Discord = require("discord.js");
const foreverTyping = new Discord.Client();

foreverTyping.on("message", function(message){
    if(message.content.toUpperCase().startsWith("F!FOREVERTYPING")){
        message.channel.startTyping();
        setTimeout(()=>{
            message.channel.send("Testing to ForeverTyping!");
            message.channel.stopTyping();
        },2000)
    }
});

foreverTyping.login("token here");
```

to activate this forever typing, just quickly send `f!forevertyping` twice in the same channel in quick succession

**Comment by SpaceEEC** [comment] 2018-03-03 09:51
I can reproduce the forever typing bug with that code on stable, but not on 11.3-dev.

**Comment by Maddoxkkm** [comment] 2018-03-03 09:56
so basically we will just have to wait?

**Comment by SpaceEEC** [comment] 2018-03-03 09:57
For the next release, yes. (Or install the 11.3-dev branch from github directly)

**Comment by Maddoxkkm** [comment] 2018-03-03 10:00
Thanks a lot!

**Comment by AykutSarac** [comment] 2020-10-09 16:42
The issue still persists.
