### ISSUE TITLE
GuildDelete event triggers every time bot starts

### ISSUE THREAD

**Issue by DomDom3333** [discordjs/discord.js#5350] opened 2021-02-23 21:47 UTC
**Please describe the problem you are having in as much detail as possible:**
Every time I start the bot, the guildDelete event triggers. However while the guild object is valid, the name and member count is undefined. This results in an error.

**Include a reproducible code sample here, if possible:**
Can't be reproduced without this specific Token. May be related to Discord itself. Starting the bot with a different token fixes the issue.

```js
bot.on("guildDelete", guild => {
    LOG.info(`Got booted from a Server!!!!!!!!\n- Name: ${guild.name}\n- Member Count: ${guild.memberCount}\nI'm now in ${bot.guilds.cache.size} Servers!`);
    Utils.contactAdmins(`Got booted from a Server!!!!!!!!\n- Name: ${guild.name}\n- Member Count: ${guild.memberCount}\nI'm now in ${bot.guilds.cache.size} Servers!`);
})
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.18.1
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible: Low-Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Albert-J04** [comment] 2021-02-24 10:34
I am seeing the same running on Ubuntu 18.04

**Comment by almostSouji** [comment] 2021-02-24 10:40
12.4.1 is no longer supported, please check 12.5.1 for the same issue.
If you can reproduce it add a listener for the websocket event and provide the output:

```js
client.ws.on("GUILD_DELETE", console.log);
```

**Comment by MidSpike** [comment] 2021-02-25 00:21
**Can reproduce** on `12.5.1`

Output that @almostSouji requested:
```js
{ id: 'censored_guild_id' } 0
```

Good thing that I keep track of guild add / removes!

The guild in question actually removed my bot around 2021-02-24...

However every time that I start the bot, **only** that guild will have a `GuildDelete` trigger for it.

**Comment by almostSouji** [comment] 2021-02-25 10:44
I actually did not expect that to log anything. Since that's the case this behavior is coming directly from Discord and there is nothing we can do about it. Discord devs are aware but currently unsure about why it happens.

**Comment by Natemo6348** [comment] 2021-03-03 04:21
If you want to prevent it from, say sending the set message on guildDelete like I have, you could add something like 
```
if (guild.name === undefined) return;
```

**Comment by Ortovoxx** [comment] 2021-03-03 08:44
I also get the same error. This should be fixed with #5367 

> Good thing that I keep track of guild add / removes!
> The guild in question actually removed my bot around 2021-02-24...

This also happened to me. The guild which triggered it was removed about a week ago.

**Comment by almostSouji** [comment] 2021-03-09 11:03
Reopening, apparently this is something we need to handle (they should however not be considered unavailable)

**Comment by almostSouji** [comment] 2021-03-09 11:07
Reopening, apparently this is something we need to handle (they should however not be considered unavailable)

From the discord developers server:
> [...], it may be related to soft-deleted guilds .. essentially we now may delete a guild without triggering a full deletion, and attempts to join the guild (on session start) may result in this being spammed to gateway. this event can be safely ignored

**Comment by Ortovoxx** [comment] 2021-03-10 11:58
This is handled in #5367

**Comment by byacar** [comment] 2021-12-02 19:16
Currently, when I make the node version 17.x, I saw that the problem was fixed.

**Closed** 2022-06-05 07:51 UTC
Labels: bug, gateway, discord, packages:discord.js
