### ISSUE TITLE
Collector filter function type does not include collected Collection

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#7646] opened 2022-03-12 19:11 UTC
### Which package is this bug report for?

discord.js

### Issue description

When the filter function of a collector is emitted, this is done with all the arguments in the collector and an additional Collection holding all of the collected items so far. This, however, is not present in the typings, as these only include a rest parameter with the collected arguments

### Code sample

```typescript
declare const client: Client
const collector = new InteractionCollector(client, { filter: (interaction, collected) => console.log(collected)}) // Type '(interaction: any, collected: any) => void' is not assignable to type 'CollectorFilter<[any]>'. ts(2322)
```

### Package version

14.0.0-dev

### Node.js version

16.14.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

b162f27

**Comment by QuarkNerd** [comment] 2022-03-28 18:55
I believe the issue is at least partially [here](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/typings/index.d.ts#L4599)

At this point we restrict the generic of the filter to be `[T]` which means the filter can only have one argument.

You should be returning a Boolean from your filter, but that won't fix this issue

**Closed** 2022-04-12 15:13 UTC
Labels: bug, need repro, typings
