### ISSUE TITLE
MessageEmbeds .setAuthor property improperly formatting

### ISSUE THREAD

**Issue by REAZN** [discordjs/discord.js#4971] opened 2020-11-02 02:18 UTC
**Please describe the problem you are having in as much detail as possible:**
Using a link or text which is quite lengthy and does not contain spaces in the MessageEmbeds .setAuthor property causes the content in the embed spill out of the embed itself.

**Include a reproducible code sample here, if possible:**

Self-explanatory
```js
let embed = new MessageEmbed()
    .setAuthor("mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm");
message.channel.send(embed);
```

**Screenshots**

![image](https://reazn.is-very.pro/k7HjZ)
![image2](https://reazn.is-very.pro/MkfPt)

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.18.1 & 14.15.0
- Operating system: Windows 10

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment] 2020-11-02 02:29
We have no control over the way Discord displays embeds.

**Comment by advaith1** [comment] 2020-11-02 02:31
why did you move this here from discord-api-docs? it fits better there, but the best place would probably be [Discord Testers](https://discord.gg/discord-testers)

**Comment by REAZN** [comment] 2020-11-02 02:39
@advaith1 I asked in the testers discord but a Mod told me to post here.

**Comment by advaith1** [comment] 2020-11-02 02:42
well that mod was wrong, it has nothing to do with discord.js

**Comment by Jiralite** [comment] 2020-11-02 02:42
You asked if you could submit discord.js bugs in Discord Testers - this is obviously not true. But, the issue you are reporting is not an issue with the library but with Discord itself and is a known issue: https://bugs.discord.com/T554.

**Comment by REAZN** [comment] 2020-11-02 02:49
Well, it is something only caused by accessing Discords API so I thought that here would be a recommended place to put it. I don't really care if this gets fixed, it's not my problem, I'm just trying to help.

**Comment by kyranet** [comment] 2020-11-02 07:44
The issue is in the Discord client, the Discord API isn't at fault nor discord.js is. It's just some CSS on the client that is off and causes that kind of issues. However, we only send and receive JSON data, which is the data required for the underlying representation of all things within Discord, and as such, as @monbrey said, we have no control over it.

As @Jiralite mentioned, the issue is already reported the right place, so I'm closing this issue.

**Closed by kyranet** 2020-11-02 07:44 UTC
Labels: s: unverified, type: bug
