### ISSUE TITLE
Error: Specified member is not UserResolvable. - TypeError [InvalidType]: Specified member is not a UserResolvable (ThreadMemberManager.add )

### ISSUE THREAD

**Issue by HeyItsDanny** [discordjs/discord.js#10433] opened 2024-08-07 15:19 UTC
### Which package is this bug report for?

discord.js

### Issue description

Since yesterday evening the error message appears every few minutes (no specific interval recognizable): 

Full error message:

`[ERROR]: Error: Specified member is not UserResolvable. - TypeError [InvalidType]: Specified member is not a UserResolvable.
    at ThreadMemberManager.add (..../node_modules/discord.js/src/managers/ThreadMemberManager.js:99:20)
    at ..../node_modules/discord.js/src/client/actions/ThreadMembersUpdate.js:17:95
    at Array.reduce (<anonymous>)
    at ThreadMembersUpdateAction.handle (..../node_modules/discord.js/src/client/actions/ThreadMembersUpdate.js:16:27)
    at module.exports [as THREAD_MEMBERS_UPDATE] (..../node_modules/discord.js/src/client/websocket/handlers/THREAD_MEMBERS_UPDATE.js:4:38)
    at WebSocketManager.handlePacket (..../node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (..../node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (..../node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:282:31)
    at WebSocketShard.<anonymous> (..../node_modules/@discordjs/ws/dist/index.js:1190:51)
    at WebSocketShard.emit (...../node_mod`

### Versions

discord.js: 14.15.3

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution, GuildMessagePolls, DirectMessagePolls

### I have tested this issue on a development release

DiscordJS: 14.15.3

**Comment by JMTK** [comment] 2024-08-07 15:32
Probably a duplicate of #10393

**Comment by didinele** [comment] 2024-08-07 18:51
Most certainly so. If this still occurs even with #10434, feel free to re-open.

**Closed by didinele** 2024-08-07 18:51 UTC
Labels: bug, need repro, packages:discord.js

**Comment by HeyItsDanny** [comment] 2024-08-07 19:09
Just4Info: I was told by your support team that I should open it.
