### ISSUE TITLE
Error with rich embed fields

### ISSUE THREAD

**Issue by Pixelmal** [discordjs/discord.js#4114] opened 2020-04-21 08:08 UTC
```js
var test = new Discord.MessageEmbed();
test.addField('test','a');
console.log(test.toJSON());
```
in console i see that message:
C:\Users\Antero\node_modules\discord.js\src\structures\MessageEmbed.js:436
      .flat(2)
       ^

TypeError: fields.flat is not a function
    at Function.normalizeFields (C:\Users\Antero\node_modules\discord.js\src\structures\MessageEmbed.js:436:8)
    at MessageEmbed.addFields (C:\Users\Antero\node_modules\discord.js\src\structures\MessageEmbed.js:252:42)
    at MessageEmbed.addField (C:\Users\Antero\node_modules\discord.js\src\structures\MessageEmbed.js:243:17)
    at Client.<anonymous> (C:\Users\Antero\Desktop\Rin Remaster\exec.js:65:6)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (C:\Users\Antero\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Antero\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Antero\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Antero\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\Antero\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)

**Further details:**

- discord.js version:12.1.1
- Node.js version:12.16.2 LTS
- Operating system:Win 10

**Comment by iCrawl** [comment] 2020-04-21 08:10
Duplicate of #3913, #3910, #3888, #3887 #3883, and #3949

**Closed by iCrawl** 2020-04-21 08:10 UTC
Labels: s: unverified, type: bug
