### ISSUE TITLE
Allow ChannelManager#fetch without a guild

### ISSUE THREAD

**Issue by GamingGeek** [discordjs/discord.js#4929] opened 2020-10-23 17:08 UTC
**Please describe the problem you are having in as much detail as possible:**
When using ChannelManager#fetch for a channel that is not cached and is not in any guilds on the current cluster, I get null rather than the channel

![image](https://user-images.githubusercontent.com/29981918/97032532-e4cf5e00-1559-11eb-9dca-c171a6d83deb.png)

Using `client.api` works fine

![image](https://user-images.githubusercontent.com/29981918/97032786-40015080-155a-11eb-8848-fef38e64b0a7.png)

 

**Include a reproducible code sample here, if possible:**

```js
client.channels.fetch("channelID", false, true) // the channelID likely needs to be a channel accessible to the bot but not accessible to any guilds in the shards of the current process
```

**Further details:**

- discord.js version: 12.4.0
- Node.js version: 14.14.0
- Operating system: Ubuntu Server 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: ["REACTION", "MESSAGE", "CHANNEL", "GUILD_MEMBER", "USER"]
- gateway intents: 1607
- other: shardCount is 4 and the shards on the cluster with the issue are [2, 3] whereas the channel in question is on shard 0

- [x] I have also tested the issue on latest master, commit hash: 250c3ae3c1f025c092383e4661bbb386e89a3c23

**Comment by NotSugden** [comment] 2020-10-23 18:33
is the channel you're trying to fetch from a guild which is not on the current shard? that seems to be the only explanation for this https://github.com/discordjs/discord.js/blob/94c9cc2300d08eba40642f256fbcf9c68487773b/src/managers/ChannelManager.js#L32-L35 here is the only way `ChannelManager#fetch` would return a promise resolving with null

**Comment by GamingGeek** [comment] 2020-10-24 10:41
@NotSugden It's fetching from the Rest API which is agnostic of shards/clusters meaning it should still work. Using [the same method ChannelManager#fetch uses](https://github.com/discordjs/discord.js/blob/master/src/managers/ChannelManager.js#L91) to fetch the channel from the API works as seen in [this image](https://user-images.githubusercontent.com/29981918/97032786-40015080-155a-11eb-8848-fef38e64b0a7.png) so I'm not quite sure what's happening here.

**Comment by wasdennnoch** [comment] 2020-10-24 11:09
The issue lies in `Channel#create` where it only creates a d.js channel instance if the parent guild is known:
https://github.com/discordjs/discord.js/blob/94c9cc2300d08eba40642f256fbcf9c68487773b/src/structures/Channel.js#L122
Since this shard is not aware of the guild the channel you're fetching is in, that method will never create a d.js Channel object, since that requires a parent guild object to exist in the current shard's client.
So the issue is not the API call - that works just fine - but the internal structure of Discord.js, in which a GuildChannel _always_ has to have a known parent Guild object.

**Comment by GamingGeek** [comment] 2020-10-24 14:19
> in which a GuildChannel always has to have a known parent Guild object.
Well that kinda ruins what I was working on. Maybe instead of this being a bug report, it could be a suggestion to make fetching a channel without a guild possible.

**Closed** 2021-07-06 12:04 UTC
Labels: type: enhancement
