### ISSUE TITLE
Audio not playing and keeps play re-enter sound (windows)

### ISSUE THREAD

**Issue by seohoyoung94** [discordjs/discord.js#3378] opened 2019-07-15 07:03 UTC
Please describe the problem you are having in as much detail as possible:

the bot doesn't play the file of mp3 and keeps re-enter the voice channel

Include a reproducible code sample here, if possible:

let voiceChannel = await bot.channels.get(notification.voiceChannel)
      .connection;
    if (!voiceChannel) {
      return;
    }
    let dispatcher = undefined;

    if (notification.type === "boss") {
      dispatcher = voiceChannel.play(
        path.join(resPath, notification.voice + ".mp3")
      );
    }else ~~~
Further details:

discord.js version: master branch
Node.js version: v10
Operating system: linux, windows
Priority this issue should have – please be realistic and elaborate if possible: high
[v ] I have also tested the issue on latest master, commit hash:

**Comment by seohoyoung94** [comment] 2019-07-15 07:04
[https://github.com/discordjs/discord.js/issues/3311](url)

**Comment by MTGPROD** [comment] 2019-09-09 19:24
This is maybe because it can't find your file, or your file corrupted.

**Comment by iCrawl** [comment] 2019-09-10 15:40
Duplicate of #3311

**Closed by iCrawl** 2019-09-10 15:40 UTC
Labels: s: duplicate
