### ISSUE TITLE
Voice resume has some issues.

### ISSUE THREAD

**Issue by killer069** [discordjs/discord.js#5732] opened 2021-06-02 16:45 UTC
Situation : Whenever I play a song and after 10 seconds, I pause the song and after few seconds when I try to resume it, I can't hear any sound.

But when I try to pause again and then resume it, it do some audio skips(same time b/w first resume and 2nd pause) and then plays the song. Now I am able to listen it clearly.

**Reproduction Steps** :
1. Start your bot and add some playing commands
2. Use this pause and resume command
3. You will get above result easily.

**LOGS** :
```
Launched!
[WS] >> {"op":3,"d":7079371330}
[WS] << {"op":6,"d":7079371330}
Paused
[WS] >> {"op":5,"d":{"speaking":0,"delay":0,"ssrc":53145}}
[WS] >> {"op":3,"d":93385364939}
[WS] << {"op":6,"d":93385364939}
Resumed                               //After this speaking doesn't change for some reasons. But second time, it resumes.
[WS] >> {"op":3,"d":83393980956}
[WS] << {"op":6,"d":83393980956}
Paused
Resumed
[WS] >> {"op":5,"d":{"speaking":1,"delay":0,"ssrc":53145}}
[WS] >> {"op":3,"d":25730567970}
[WS] << {"op":6,"d":25730567970}
[WS] >> {"op":3,"d":74574400963}
[WS] << {"op":6,"d":74574400963}
```

**COMMAND**
```js
message.guild.me.voice.connection.dispatcher.resume() // Resume Command

message.guild.me.voice.connection.dispatcher.pause() // Pause Command
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.17.0
- Operating system: Windows 10
- Priority this issue should have – Very High

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

Moreover, This is also a bug of Master branch also. So, it is highly requested to fix this issue fast.

**Comment by XECortex** [comment] 2021-06-02 17:15
I can confirm this, we have the same problem

**Comment by killer069** [comment] 2021-06-02 20:31
> I can confirm this, we have the same problem

You have to add in resume command :
First resume command
then pause command
and then resume command.

**Comment by XECortex** [comment] 2021-06-02 23:45
This only a temporary solution, this bug needs to be fixed

**Comment by iCrawl** [comment] 2021-06-07 07:14
Duplicate of #5300

**Closed by iCrawl** 2021-06-07 07:14 UTC
Labels: s: unverified, t: voice, type: bug
