### ISSUE TITLE
ts build error

### ISSUE THREAD

**Issue by erukim** [discordjs/discord.js#9784] opened 2023-08-19 03:07 UTC
### Which package is this bug report for?

discord.js

### Issue description

I wrote "build":tsc --project tscconfig.json" in the package.json script, but the following error occurs when building yarn.

```node_modules/discord.js/typings/index.d.ts:1181:21 - error TS1139: Type parameter declaration expected.

1181   public getChannel<const T extends ChannelType = ChannelType>(
                         ~~~~~

node_modules/discord.js/typings/index.d.ts:1181:27 - error TS1434: Unexpected keyword or identifier.

1181   public getChannel<const T extends ChannelType = ChannelType>(
                               ~

node_modules/discord.js/typings/index.d.ts:1181:29 - error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.

1181   public getChannel<const T extends ChannelType = ChannelType>(
                                 ~~~~~~~

node_modules/discord.js/typings/index.d.ts:1182:9 - error TS1005: ')' expected.

1182     name: string,
             ~

node_modules/discord.js/typings/index.d.ts:1182:11 - error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.

1182     name: string,
               ~~~~~~

node_modules/discord.js/typings/index.d.ts:1183:13 - error TS1005: ';' expected.

1183     required: true,
                 ~

node_modules/discord.js/typings/index.d.ts:1184:18 - error TS1109: Expression expected.

1184     channelTypes?: readonly T[],
                      ~

node_modules/discord.js/typings/index.d.ts:1184:29 - error TS1005: ';' expected.

1184     channelTypes?: readonly T[],
                                 ~

node_modules/discord.js/typings/index.d.ts:1184:31 - error TS1011: An element access expression should take an argument.

1184     channelTypes?: readonly T[],
    

node_modules/discord.js/typings/index.d.ts:1185:3 - error TS1109: Expression expected.

1185   ): Extract<
       ~

node_modules/discord.js/typings/index.d.ts:1185:4 - error TS1128: Declaration or statement expected.

1185   ): Extract<
        ~

node_modules/discord.js/typings/index.d.ts:1196:3 - error TS1128: Declaration or statement expected.

1196   public getChannel<const T extends ChannelType = ChannelType>(
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1196:21 - error TS1109: Expression expected.

1196   public getChannel<const T extends ChannelType = ChannelType>(
                         ~~~~~

node_modules/discord.js/typings/index.d.ts:1196:29 - error TS1005: ',' expected.

1196   public getChannel<const T extends ChannelType = ChannelType>(
                                 ~~~~~~~

node_modules/discord.js/typings/index.d.ts:1197:9 - error TS1005: ')' expected.

1197     name: string,
             ~

node_modules/discord.js/typings/index.d.ts:1198:13 - error TS1005: ',' expected.

1198     required?: boolean,
                 ~

node_modules/discord.js/typings/index.d.ts:1198:14 - error TS1134: Variable declaration expected.

1198     required?: boolean,
                  ~

node_modules/discord.js/typings/index.d.ts:1199:17 - error TS1005: ',' expected.

1199     channelTypes?: readonly T[],
                     ~

node_modules/discord.js/typings/index.d.ts:1199:18 - error TS1134: Variable declaration expected.

1199     channelTypes?: readonly T[],
                      ~

node_modules/discord.js/typings/index.d.ts:1199:29 - error TS1005: ',' expected.

1199     channelTypes?: readonly T[],
                                 ~

node_modules/discord.js/typings/index.d.ts:1199:30 - error TS1005: ',' expected.

1199     channelTypes?: readonly T[],
                                  ~

node_modules/discord.js/typings/index.d.ts:1200:3 - error TS1128: Declaration or statement expected.

1200   ): Extract<
       ~

node_modules/discord.js/typings/index.d.ts:1200:4 - error TS1128: Declaration or statement expected.

1200   ): Extract<
        ~

node_modules/discord.js/typings/index.d.ts:1211:3 - error TS1128: Declaration or statement expected.

1211   public getString(name: string, required: true): string;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1211:24 - error TS1005: ',' expected.

1211   public getString(name: string, required: true): string;
                            ~

node_modules/discord.js/typings/index.d.ts:1211:42 - error TS1005: ',' expected.

1211   public getString(name: string, required: true): string;
                                              ~

node_modules/discord.js/typings/index.d.ts:1211:49 - error TS1005: ';' expected.

1211   public getString(name: string, required: true): string;
                                                     ~

node_modules/discord.js/typings/index.d.ts:1212:3 - error TS1128: Declaration or statement expected.

1212   public getString(name: string, required?: boolean): string | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1212:24 - error TS1005: ',' expected.

1212   public getString(name: string, required?: boolean): string | null;
                            ~

node_modules/discord.js/typings/index.d.ts:1212:43 - error TS1109: Expression expected.

1212   public getString(name: string, required?: boolean): string | null;
                                               ~

node_modules/discord.js/typings/index.d.ts:1212:53 - error TS1005: ';' expected.

1212   public getString(name: string, required?: boolean): string | null;
                                                         ~

node_modules/discord.js/typings/index.d.ts:1213:3 - error TS1128: Declaration or statement expected.

1213   public getInteger(name: string, required: true): number;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1213:25 - error TS1005: ',' expected.

1213   public getInteger(name: string, required: true): number;
                             ~

node_modules/discord.js/typings/index.d.ts:1213:43 - error TS1005: ',' expected.

1213   public getInteger(name: string, required: true): number;
                                               ~

node_modules/discord.js/typings/index.d.ts:1213:50 - error TS1005: ';' expected.

1213   public getInteger(name: string, required: true): number;
                                                      ~

node_modules/discord.js/typings/index.d.ts:1214:3 - error TS1128: Declaration or statement expected.

1214   public getInteger(name: string, required?: boolean): number | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1214:25 - error TS1005: ',' expected.

1214   public getInteger(name: string, required?: boolean): number | null;
                             ~

node_modules/discord.js/typings/index.d.ts:1214:44 - error TS1109: Expression expected.

1214   public getInteger(name: string, required?: boolean): number | null;
                                                ~

node_modules/discord.js/typings/index.d.ts:1214:54 - error TS1005: ';' expected.

1214   public getInteger(name: string, required?: boolean): number | null;
                                                          ~

node_modules/discord.js/typings/index.d.ts:1215:3 - error TS1128: Declaration or statement expected.

1215   public getNumber(name: string, required: true): number;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1215:24 - error TS1005: ',' expected.

1215   public getNumber(name: string, required: true): number;
                            ~

node_modules/discord.js/typings/index.d.ts:1215:42 - error TS1005: ',' expected.

1215   public getNumber(name: string, required: true): number;
                                              ~

node_modules/discord.js/typings/index.d.ts:1215:49 - error TS1005: ';' expected.

1215   public getNumber(name: string, required: true): number;
                                                     ~

node_modules/discord.js/typings/index.d.ts:1216:3 - error TS1128: Declaration or statement expected.

1216   public getNumber(name: string, required?: boolean): number | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1216:24 - error TS1005: ',' expected.

1216   public getNumber(name: string, required?: boolean): number | null;
                            ~

node_modules/discord.js/typings/index.d.ts:1216:43 - error TS1109: Expression expected.

1216   public getNumber(name: string, required?: boolean): number | null;
                                               ~

node_modules/discord.js/typings/index.d.ts:1216:53 - error TS1005: ';' expected.

1216   public getNumber(name: string, required?: boolean): number | null;
                                                         ~

node_modules/discord.js/typings/index.d.ts:1217:3 - error TS1128: Declaration or statement expected.

1217   public getUser(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['user']>;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1217:22 - error TS1005: ',' expected.

1217   public getUser(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['user']>;
                          ~

node_modules/discord.js/typings/index.d.ts:1217:40 - error TS1005: ',' expected.

1217   public getUser(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['user']>;
                                            ~

node_modules/discord.js/typings/index.d.ts:1217:47 - error TS1005: ';' expected.

1217   public getUser(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['user']>;
                                                   ~

node_modules/discord.js/typings/index.d.ts:1218:3 - error TS1128: Declaration or statement expected.

1218   public getUser(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['user']> | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1218:22 - error TS1005: ',' expected.

1218   public getUser(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['user']> | null;
                          ~

node_modules/discord.js/typings/index.d.ts:1218:41 - error TS1109: Expression expected.

1218   public getUser(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['user']> | null;
                                             ~

node_modules/discord.js/typings/index.d.ts:1218:51 - error TS1005: ';' expected.

1218   public getUser(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['user']> | null;
                                                       ~

node_modules/discord.js/typings/index.d.ts:1219:3 - error TS1128: Declaration or statement expected.

1219   public getMember(name: string): NonNullable<CommandInteractionOption<Cached>['member']> | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1219:24 - error TS1005: ',' expected.

1219   public getMember(name: string): NonNullable<CommandInteractionOption<Cached>['member']> | null;
                            ~

node_modules/discord.js/typings/index.d.ts:1219:33 - error TS1005: ';' expected.

1219   public getMember(name: string): NonNullable<CommandInteractionOption<Cached>['member']> | null;
                                     ~

node_modules/discord.js/typings/index.d.ts:1220:3 - error TS1128: Declaration or statement expected.

1220   public getRole(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['role']>;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1220:22 - error TS1005: ',' expected.

1220   public getRole(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['role']>;
                          ~

node_modules/discord.js/typings/index.d.ts:1220:40 - error TS1005: ',' expected.

1220   public getRole(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['role']>;
                                            ~

node_modules/discord.js/typings/index.d.ts:1220:47 - error TS1005: ';' expected.

1220   public getRole(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['role']>;
                                                   ~

node_modules/discord.js/typings/index.d.ts:1221:3 - error TS1128: Declaration or statement expected.

1221   public getRole(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['role']> | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1221:22 - error TS1005: ',' expected.

1221   public getRole(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['role']> | null;
                          ~

node_modules/discord.js/typings/index.d.ts:1221:41 - error TS1109: Expression expected.

1221   public getRole(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['role']> | null;
                                             ~

node_modules/discord.js/typings/index.d.ts:1221:51 - error TS1005: ';' expected.

1221   public getRole(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['role']> | null;
                                                       ~

node_modules/discord.js/typings/index.d.ts:1222:3 - error TS1128: Declaration or statement expected.

1222   public getAttachment(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['attachment']>;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1222:28 - error TS1005: ',' expected.

1222   public getAttachment(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['attachment']>;
                                ~

node_modules/discord.js/typings/index.d.ts:1222:46 - error TS1005: ',' expected.

1222   public getAttachment(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['attachment']>;
                                                  ~

node_modules/discord.js/typings/index.d.ts:1222:53 - error TS1005: ';' expected.

1222   public getAttachment(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['attachment']>;
                                                         ~

node_modules/discord.js/typings/index.d.ts:1223:3 - error TS1128: Declaration or statement expected.

1223   public getAttachment(
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1224:9 - error TS1005: ',' expected.

1224     name: string,
             ~

node_modules/discord.js/typings/index.d.ts:1225:14 - error TS1109: Expression expected.

1225     required?: boolean,
                  ~

node_modules/discord.js/typings/index.d.ts:1226:4 - error TS1005: ';' expected.

1226   ): NonNullable<CommandInteractionOption<Cached>['attachment']> | null;
        ~

node_modules/discord.js/typings/index.d.ts:1227:3 - error TS1128: Declaration or statement expected.

1227   public getMentionable(
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1228:9 - error TS1005: ',' expected.

1228     name: string,
             ~

node_modules/discord.js/typings/index.d.ts:1229:13 - error TS1005: ',' expected.

1229     required: true,
                 ~

node_modules/discord.js/typings/index.d.ts:1230:4 - error TS1005: ';' expected.

1230   ): NonNullable<CommandInteractionOption<Cached>['member' | 'role' | 'user']>;
        ~

node_modules/discord.js/typings/index.d.ts:1231:3 - error TS1128: Declaration or statement expected.

1231   public getMentionable(
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1232:9 - error TS1005: ',' expected.

1232     name: string,
             ~

node_modules/discord.js/typings/index.d.ts:1233:14 - error TS1109: Expression expected.

1233     required?: boolean,
                  ~

node_modules/discord.js/typings/index.d.ts:1234:4 - error TS1005: ';' expected.

1234   ): NonNullable<CommandInteractionOption<Cached>['member' | 'role' | 'user']> | null;
        ~

node_modules/discord.js/typings/index.d.ts:1235:3 - error TS1128: Declaration or statement expected.

1235   public getMessage(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['message']>;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1235:25 - error TS1005: ',' expected.

1235   public getMessage(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['message']>;
                             ~

node_modules/discord.js/typings/index.d.ts:1235:43 - error TS1005: ',' expected.

1235   public getMessage(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['message']>;
                                               ~

node_modules/discord.js/typings/index.d.ts:1235:50 - error TS1005: ';' expected.

1235   public getMessage(name: string, required: true): NonNullable<CommandInteractionOption<Cached>['message']>;
                                                      ~

node_modules/discord.js/typings/index.d.ts:1236:3 - error TS1128: Declaration or statement expected.

1236   public getMessage(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['message']> | null;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1236:25 - error TS1005: ',' expected.

1236   public getMessage(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['message']> | null;
                             ~

node_modules/discord.js/typings/index.d.ts:1236:44 - error TS1109: Expression expected.

1236   public getMessage(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['message']> | null;
                                                ~

node_modules/discord.js/typings/index.d.ts:1236:54 - error TS1005: ';' expected.

1236   public getMessage(name: string, required?: boolean): NonNullable<CommandInteractionOption<Cached>['message']> | null;
                                                          ~

node_modules/discord.js/typings/index.d.ts:1237:3 - error TS1128: Declaration or statement expected.

1237   public getFocused(getFull: true): AutocompleteFocusedOption;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1237:28 - error TS1005: ',' expected.

1237   public getFocused(getFull: true): AutocompleteFocusedOption;
                                ~

node_modules/discord.js/typings/index.d.ts:1237:35 - error TS1005: ';' expected.

1237   public getFocused(getFull: true): AutocompleteFocusedOption;
                                       ~

node_modules/discord.js/typings/index.d.ts:1238:3 - error TS1128: Declaration or statement expected.

1238   public getFocused(getFull?: boolean): string;
       ~~~~~~

node_modules/discord.js/typings/index.d.ts:1238:29 - error TS1109: Expression expected.

1238   public getFocused(getFull?: boolean): string;
                                 ~

node_modules/discord.js/typings/index.d.ts:1238:39 - error TS1005: ';' expected.

1238   public getFocused(getFull?: boolean): string;
                                           ~

node_modules/discord.js/typings/index.d.ts:1239:1 - error TS1128: Declaration or statement expected.

1239 }
     ~


Found 97 errors in the same file, starting at: node_modules/discord.js/typings/index.d.ts:1181```

However, when a command is executed directly from the terminal, it is built normally.

### Code sample

```typescript
tsconfig.json

{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es2021"],
    "outDir": "./build",
    "rootDir": ".",
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "exclude": ["build", "node_modules", "example.*.ts"]
}
```

### Versions

- discord.js 14.13.0
- TypeScript 4.7.4
- Node.js 18.17.1
- windows 10 pro

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment] 2023-08-19 03:10
Duplicate of #9783.

**Closed by Jiralite** 2023-08-19 03:10 UTC
Labels: bug, need repro, packages:discord.js
