### ISSUE TITLE
messageReactionAdd does not register the user.

### ISSUE THREAD

**Issue by zactham** [discordjs/discord.js#4972] opened 2020-11-02 04:51 UTC
Upon logging in the bot sends an embedded message.  The reactions are not registered until the user that is reacting first sends a message.  

So the bot sends embedded message, user reacts and nothing happens.  But if bot sends embedded message, user sends a message in the channel, then the user reacts to the bot embedded message it registers.  The bot embedded message is sent with client.once('ready', async () => {. 

```
client.on('messageReactionAdd', async(reaction, user) => {
    console.log("reaction")
    //Doesnt do anything when the bot reacts
    if (user.id == "770529819947434004") return;
    if (reaction.message.partial) await reaction.message.fetch();

    //checks for reactions in rules channel only
    if (reaction.message.channel.id === "768329542887669770" && reaction.emoji.name == '✅')
    {
        console.log("worked")
        await reaction.message.guild.members.cache.array.get(user.id).roles.add("770536018004541441")
    }

```

});
```

**Further details:**

- discord.js version: discord@0.8.2 
- Node.js version: 6.14.8
- Operating system: Mac
- Priority this issue should have – please be realistic and elaborate if possible: small

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

<!--
If this applies to you, please check the respective checkbox: [ ] becomes [x].
You don't have to modify the text to suit your particular situation – if you want to
elaborate, please do so in the description.
While it's not a requirement to test your issue on the master branch, it would make fixing
the problem a lot easier for us, so please do so if possible.
-->

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment] 2020-11-02 17:53
duplicate of #4968 , caused by API changes, either requires privileged intents or partials to be set.

**Closed by almostSouji** 2020-11-02 17:53 UTC
Labels: s: duplicate
