### ISSUE TITLE
TypeError: Cannot read property 'emoji' of undefined

### ISSUE THREAD

**Issue by curingme** [discordjs/discord.js#3898] opened 2020-03-04 18:52 UTC
A day ago I wanted to add new plugins etc, so I updated discord.js to start with. I don't remember when I created my bot. Well, after trying to get it to work whenever I use an .awaitreactions() function and then it follows to collected.emoji it decides to break.

I just get errors if I don't clear the reactions before it hits the if statement. I have another command that it is happening the same to, which I haven't touch for sometime.

```
m.channel.send(mainEmbed)
            .then(msg => {
                const help = (r: any, usr: any) => {
                    return ["⏹", "⏺️"].includes(r.emoji.name) && usr.id === m.author.id;
                };
                let i = (msg as Discord.Message)
                i.react("⏹")
                    .then(() => i.react("⏺️"))
                    .then(() => i.react("▶️"))
                    i.awaitReactions(help, {
                        max: 1,
                        time: 60000,
                        errors: ['time']
                    }).then(collected => {
                        const m = collected.first();
                        if (m.emoji.name === "⏹") { // <--- Cannot read property 'emoji' of undefined ( this is what is causing the error )
                            i.delete(1000)
                                .catch(console.error)
                        } else if (m.emoji.name === "⏺️") {
                            setTimeout(() => {
                                i.clearReactions()
                                    .catch(console.error)
                            }, 1000)
                        } else if (m.emoji.name === "▶️") {
                            setTimeout(() => {
                                i.clearReactions()
                                    .catch(console.error);
                                i.edit(page1)
                                    .then(() => {
                                        i.react("⏹")
                                            .then(() => i.react("⏺️"))
                                        i.awaitReactions(help, {
                                            max: 1,
                                            time: 60000,
                                            errors: ['time']
                                        }).then(collected => {
                                            const m = collected.first();
                                            if (m.emoji.name === "⏹") {
                                                i.delete(1000)
                                                    .catch(console.error);
                                            } else if (m.emoji.name === "⏺️") {
                                                setTimeout(() => {
                                                    i.clearReactions()
                                                        .catch(console.error);
                                                }, 1000)
                                            } else {
                                                i.clearReactions()
                                                    .catch(console.error)
                                            }
                                        })
                                    }).catch(console.error)
                            }, 1000);
                        } else {
                            i.clearReactions()
                                .catch(console.error);
                        }
                    }).catch(console.error)
            }).catch(console.error)
```

**Comment by curingme** [comment] 2020-03-05 19:05
```
TypeError: Cannot read property 'emoji' of undefined
    at i.awaitReactions.then.collected (c:\Users\curingme\Desktop\GAMING\timmy\dist\commands\help.js:88:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Jiralite** [comment] 2020-03-06 00:12
Please do not delete the issue tracker, and use it. It contains vital information to work with.

This is related to #3868.

**Comment by curingme** [comment] 2020-03-07 16:39
This thread has fixed the issue.

**Comment by SpaceEEC** [comment] 2020-03-08 16:30
Closing this issue as it is a duplicate of #3868.

**Closed by SpaceEEC** 2020-03-08 16:30 UTC
Labels: s: duplicate
