### ISSUE TITLE
v11.3.2 incompatible with Node.js 6

### ISSUE THREAD

**Issue by synixebrett** [discordjs/discord.js#2486] opened 2018-04-19 17:20 UTC
The docs at https://discord.js.org/#/docs/main/stable/general/welcome say that Node 6.0.0 or greater is required. I was using discord.js in a Node 7 environment and was disappointed today to discover some functions will not work as they require Node 8. This has caused me quite a bit of headache.

To close this issues the docs just need to be updated and then kept up to date better in the future.

**Comment by BigBrainAFK** [comment] 2018-04-19 18:02
1. There was a nice template for issues iirc
2. How about you are a bit more specific and tell us what those functions are?

**Comment by Gawdl3y** [comment] 2018-04-19 18:27
If you're trying to use the master branch, that requires Node 8, and the docs for it *have* been updated to reflect that.

**Comment by brettmayson** [comment] 2018-04-20 13:33
I get that, my complaint is that the node version listed is 6.0, but following the instructions directly underneath will install a version dependent on Node 8.0.

**Comment by Gawdl3y** [comment] 2018-04-20 13:34
In what way?

**Comment by brettmayson** [comment] 2018-04-20 13:36
`npm install discord.js` installs 11.3.2

The instructions in the documentation for stable say Node 6.0 is the minimum version required, and the installation instructions is to run `npm install discord.js` which results in 11.3.2 requiring Node 8.

**Comment by Dev-Yukine** [comment] 2018-04-20 13:36
Could you explain what you mean by "version listed"? the github site is only for master and master needs node 8.x while the npm site is only for stable what needs 6.x

**Comment by brettmayson** [comment] 2018-04-20 13:37
![installation](https://user-images.githubusercontent.com/3946739/39053953-96d956fc-446d-11e8-91e7-797192512e22.png)

This is from https://discord.js.org/#/docs/main/stable/general/welcome, the stable branch documentation. But the instructions will install 11.3.2 from the master.

**Comment by Dev-Yukine** [comment] 2018-04-20 13:38
the command `npm install discord.js` installs the stable version what doesn't need node.js 8.x 🤔

**Comment by brettmayson** [comment] 2018-04-20 13:39
I got errors related to undefined functions that require Node 8.

**Comment by Dev-Yukine** [comment] 2018-04-20 13:41
i just tested discord.js stable on node.js version 6.14 and it works fine, this is not an error related to discord.js or atleast i cant reproduce your error.

**Comment by Gawdl3y** [comment] 2018-04-20 13:47
You're going to need to tell us what errors you're getting, because v11.3.2 should definitely be compatible with Node 6.

**Comment by brettmayson** [comment] 2018-04-20 13:48
The errors were in reference to an the use of Object.values() which was undefined.

**Comment by Gawdl3y** [comment] 2018-04-20 13:48
You're not on Node 6, then.

**Comment by Gawdl3y** [comment] 2018-04-20 13:55
Found it. https://github.com/discordjs/discord.js/blob/stable/src/client/rest/RESTManager.js#L19

Thanks for bringing this to our attention - it'll be fixed in an upcoming version.

**Comment by brettmayson** [comment] 2018-04-20 13:56
Awesome, thanks.

**Comment by kyranet** [comment] 2018-04-21 08:56
@synixebrett Can you test again in the branch `11.3-dev` and tell us if there is another incompatibily, please?

**Comment by synixebrett** [comment] 2018-04-22 19:57
I've already upgraded to Node 8 since I needed to get my project deployed.

**Closed** 2018-08-10 09:04 UTC
Labels: p: medium, type: bug
