### ISSUE TITLE
Random Undefined Error | Library Issue

### ISSUE THREAD

**Issue by Seek0999** [discordjs/discord.js#7006] opened 2021-11-19 03:42 UTC
### Issue description

I have recently encountered an error while updating from v12 to v13, 

I am not sure how to reproduce the error as none of my code has been referenced in the error nor am i sure what causes this error to be thrown.

I have been told that it could be due to my sharding file so i have put that down below.

### Code sample

```typescript
Error Code:

Error [ReferenceError]: res is not defined
    at eval (eval at _eval (C:\Users\OneDrive\Desktop\Spixx d.js v13\node_modules\discord.js\src\client\Client.js:534:12), <anonymous>:1:35)
    at eval (eval at _eval (C:\Users\OneDrive\Desktop\Spixx d.js v13\node_modules\discord.js\src\client\Client.js:534:12), <anonymous>:1:68)
    at Client._eval (C:\Users\OneDrive\Desktop\Spixx d.js v13\node_modules\discord.js\src\client\Client.js:534:12)
    at ShardClientUtil._handleMessage (C:\Users\OneDrive\Desktop\Spixx d.js v13\node_modules\discord.js\src\sharding\ShardClientUtil.js:184:82)
    at process.emit (node:events:402:35)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

Sharding Manager:

const { ShardingManager } = require('discord.js');
const Discord = require('discord.js');
const config = require('./config.json');
const manager = new ShardingManager('./bot.js', { 
    token: config.token
});
const webhookClient = new Discord.WebhookClient({id: config.id, token: config['web-token']});

manager.on('shardCreate', shard => {
    console.log(`Launched shard ${shard.id}`)
    
    const embed = new Discord.MessageEmbed()
	.setTitle(`Shard ${shard.id} has launched.`)
    .setTimestamp()

    webhookClient.send({
        username: `Shard ${shard.id} Launched`,
        embeds: [embed]
    })
})

manager.spawn({ amount: config.ShardCount, delay: 5000});
```

### discord.js version

13.3.1

### Node.js version

16.11.1

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by SpaceEEC** [comment] 2021-11-19 12:18
The referenced method is called when you use [`Shard#eval`](https://discord.js.org/#/docs/main/stable/class/Shard?scrollTo=eval), [`ShardingManager#broadcastEval`](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=broadcastEval), or [`ShardClientUtil#broadcastEval`](https://discord.js.org/#/docs/main/stable/class/ShardClientUtil?scrollTo=broadcastEval).

If you are unable to find the cause with that, you can attach a listener to [`process#message`](https://nodejs.org/api/process.html#event-message) and log the received messages as those will also include (broadcast-)evals.

**Comment by waki285** [comment] 2021-11-23 09:47
some

**Comment by timcole** [comment] 2021-11-30 15:47
We are experiencing a very similar issue with our bot when upgrading from v13.1.0 to v13.3.1 as well.
The following gets thrown when using `ShardingManager#broadcastEval`.

The most basic broadcastEval even throws this error making it completely unuseable..
```js
manager.broadcastEval(
  async (client) => {
    console.log(client.uptime);
  },
  {
    context: {},
  },
);
```

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ReferenceError]: __awaiter is not defined
    at eval (eval at _eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:1:74)
    at eval (eval at _eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:61:16)
    at Client._eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12)
    at ShardClientUtil._handleMessage (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:184:82)
    at process.emit (node:events:402:35)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

if you remove the async off the eval function it does work fine, but it should work being async like before imo. If this was an intentional change it was a breaking one and should be reevaluated.

**Comment by vladfrangu** [comment] 2021-11-30 15:48
> We are experiencing a very similar issue with our bot when upgrading from v13.1.0 to v13.3.1 as well.
> The following gets thrown when using `ShardingManager#broadcastEval`.
> 
> The most basic broadcastEval even throws this error making it completely unuseable..
> ```js
> manager.broadcastEval(
>   async (client) => {
>     console.log(client.uptime);
>   },
>   {
>     context: {},
>   },
> );
> ```
> 
> ```
> node:internal/process/promises:246
>           triggerUncaughtException(err, true /* fromPromise */);
>           ^
> 
> Error [ReferenceError]: __awaiter is not defined
>     at eval (eval at _eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:1:74)
>     at eval (eval at _eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:61:16)
>     at Client._eval (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/client/Client.js:534:12)
>     at ShardClientUtil._handleMessage (/Users/(redacted)/Development/freshtok/bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:184:82)
>     at process.emit (node:events:402:35)
>     at emit (node:internal/child_process:917:12)
>     at processTicksAndRejections (node:internal/process/task_queues:84:21)
> ```
> 
> if you remove the async off the eval function it does work fine, but it should work being async like before imo. If this was an intentional change it was a breaking one and should be reevaluated.

This doesn't seem like a d.js issue but rather your transpiled code being downleveled too much 👀

**Comment by timcole** [comment] 2021-11-30 15:58
I need to go order some more coffee... Thanks for the help! Changing target to ES2020 seems to fix my issue. Was a bit confusing to me as we only updated d.js, nothing else and this worked fine in the older version. Sorry for the trouble :)

**Comment by kyranet** [comment] 2021-12-07 09:59
@Seek0999 did you have luck getting the code that results on that error? Do you have a `res` inside the callback from any of those methods? Right now we cannot reproduce, and I highly suspect it's because you're not using [BroadcastEvalOptions.context](https://discord.js.org/#/docs/main/stable/typedef/BroadcastEvalOptions) or similar (the other two methods have the same option).

**Comment by waki285** [comment] 2021-12-09 02:03
i've same priblem

```js
const a = "Some Bot Name"
const id = await client.shard.broadcastEval((cl) =>
  cl.users.cache.find((x) => x.username === a)
);
```

Error:

```js
Error [ReferenceError]: a is not defined
    at eval (eval at _eval (/home/runner/fairu-wake/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:2:53)
    at Map.find (/home/runner/fairu-wake/node_modules/@discordjs/collection/dist/index.js:1:1708)
    at eval (eval at _eval (/home/runner/fairu-wake/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:2:26)
    at eval (eval at _eval (/home/runner/fairu-wake/node_modules/discord.js/src/client/Client.js:534:12), <anonymous>:2:56)
    at Client._eval (/home/runner/fairu-wake/node_modules/discord.js/src/client/Client.js:534:12)
    at ShardClientUtil._handleMessage (/home/runner/fairu-wake/node_modules/discord.js/src/sharding/ShardClientUtil.js:184:82)
    at process.emit (node:events:402:35)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by Jiralite** [comment] 2021-12-09 02:12
You're not using the method correctly - see [here](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=broadcastEval) for documentation on the method. You need to pass a `context` to use your `a`.

**Comment by phamleduy04** [comment] 2021-12-13 20:11
I have the same problem which causes the bot won't start unless I comment out those lines. 

`manager.fetchClientValues()`

node version: 16.7.0
discord.js: 13.3.1

error log:
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
line commented out and works
```js
// it is a function 
    getGuildCount: async (manager) => {
        if (!manager) return null;
        const arr = await manager.fetchClientValues('guilds.cache.size');
        return arr.reduce((p, n) => p + n, 0);
    },
    getMembersCount: async (manager) => {
        if (!manager) return null;
        const res = await manager.broadcastEval(client => client.guilds.cache.map((guild) => guild.memberCount));
        return _.sum(res.map(_.sum));
    },
    getChannelsCount: async (manager) => {
        if (!manager) return null;
        const arr = await manager.fetchClientValues('channels.cache.size');
        return arr.reduce((p, n) => p + n, 0);
    },
```

**Comment by SpaceEEC** [comment] 2021-12-14 19:37
The error that is hinted at by that unhandled promise rejection warning is _probably_ coming from here: (`Util.fetchRecommendedShards`)
https://github.com/discordjs/discord.js/blob/5ec04e077bbbb9799f3ef135cade84b77346ef20/src/util/Util.js#L277-L280
(That is indeed not really an elegant way to go about error handling, but anyway)

This method is internally exclusively called from `ShardingManager#spawn`, which is never internally called.
It seems unlikely that `ShardingManager#fetchClientValues` would cause that error to be thrown.

---

Could you create a new issue with more info and preferably a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this?
That error is likely unrelated to this issue and I'd argue that this issue is resolved by now. 😅

**Closed** 2022-06-05 07:50 UTC
Labels: bug, need repro, sharding, packages:discord.js
