### ISSUE TITLE
Custom status doesn't exist in user

### ISSUE THREAD

**Issue by Syncinus** [discordjs/discord.js#3552] opened 2019-10-26 20:31 UTC
Discord recently added custom status and I noticed it doesn't show on any of the fields a user, and on the game name sometimes shows "Custom Status". Discord's API should be adding in this soon or might have already added it, so this feature should be here for V12.

**Comment by Androz2091** [comment] 2019-10-26 20:34
I think there is already a pr to add this (#3353)

**Comment by almostSouji** [comment] 2019-10-26 20:41
The custom status feature will very likely be reworked and the library will introduce this final version once it's documented by the API.

--- 

For now you can read the `state` property of [Presence#game](https://discord.js.org/#/docs/main/stable/class/Presence?scrollTo=game) (v11) or [Presence#activity](https://discord.js.org/#/docs/main/master/class/Presence?scrollTo=activity) (v12) to receive the custom status text, if no other activity overwrites it (think spotify, games).
Discord.js does not support multiple activities yet, so if the custom status is not the only activity it will not be displayed in these properties.

Due to the different structure of presence data there is also currently no way get the emoji used in the custom status.

--- 
Side note (since people always wonder):
According to <https://github.com/discordapp/discord-api-docs/issues/1160>there are plans to make this feature (setting a custom status) accessible for bots at a later date.

**Comment by danbulant** [comment] 2019-11-09 18:45
@almostSouji discordapp/discord-api-docs#1162 resolves discordapp/discord-api-docs#1160 , so it should be already accessible for bots. Any plans on implementing it? It would be great to set custom status instead of the normal "playing", as there is more room for text.

**Comment by SpaceEEC** [comment] 2019-11-09 19:38
While the PR is merged, the behavior still seems to be the old and unwanted one.
(`state` being the text and `name` being the literal `'Custom Status'`)

Also there is no note that bots actually can set one now. (It does not seem to work either, sending a type 4 activity, clears the current one)

**Comment by advaith1** [comment] 2019-12-06 02:04
Custom status support (reading) has been added in https://github.com/discordjs/discord.js/commit/2ca74d6b63392c09a388c58f9b04945e884646c6, but d.js only supports showing 1 activity, so if the user has both custom status and playing/spotify/something else, the activity object will only have one. D.js probably needs to be updated to show all of a user's activities.

**Comment by anandre** [comment] 2019-12-06 02:20
It's been previously stated that the library devs are waiting for custom status to be fully reworked and finalized by Discord before continuing to implement anything further in the library.  I'm not sure if this has only been said on the server or if someone has commented something to this effect on GH.

**Comment by advaith1** [comment] 2019-12-07 22:21
I assumed that was before Discord fully released custom status, have they confirmed that it will be reworked?

**Comment by almostSouji** [comment] 2019-12-07 23:37
From all I know the statement was placed __after__ custom status was released on the stable channel, when several people asked if this is the final implementation, since it introduces quite a few inconsistencies.

@jhgg, could you clarify if possible?

**Comment by advaith1** [comment] 2020-01-25 23:35
#3747 added support for multiple activities so I guess this issue has been resolved

**Closed** 2020-02-24 13:56 UTC
Labels: reason: API support, s: already fixed, s: fixed on master, t: gateway
