### ISSUE TITLE
The method playFile stops playback of audio files (mp3) about 300-600ms too early

### ISSUE THREAD

**Issue by victorleblais** [discordjs/discord.js#4358] opened 2020-06-15 01:03 UTC
**Please describe the problem you are having in as much detail as possible:**
When I use `connection.playFile()` to play short audio files, the audio seems to cut off too early. The event `end` is also sent too soon.

This is extremely similar to the issue #2820

**Reproducible code sample:**
Just put that into your client's 'message' event:
```js
message.member.voiceChannel.join().then((connection) => {
    console.log(Date.now() + ' / Joined voice channel.')
    let file = './sounds/yeee.mp3'
    console.log(`   File: '${file}'`)

    const dispatcher = connection.playFile(file)

    let start = 0;
    let end = 0;

    dispatcher.on('start', () => {
        start = Date.now()
        console.log(`${start} / Started playing`)
        connection.player.streamingData.pausedTime = 0
        dispatcher.setVolume(0.70)
    })

    dispatcher.on('debug', (info) => {
        console.log(Date.now() + ` / Debug: '${info}'`)
    });

    dispatcher.on('end', reason => {
        end = Date.now()
        console.log(`${end} / Finished playing. Reason: '${reason}'`)
        let playbackDuration = end - start
        const buffer = fs.readFileSync(file)
        let fileDuration = getMP3Duration(buffer, 'ms')
        let difference = fileDuration - playbackDuration
        console.log(`   Playtime: ${playbackDuration} ms`)
        console.log(`   Real duration: ${fileDuration} ms`) // requires dependency "get-mp3-duration"
        console.log(`   Difference: ${difference} ms`)
    })
})
```
Output: 
```
1592182551780 / Joined voice channel.
   File: './sounds/yeee.mp3'
1592182551859 / Started playing
1592182552367 / Finished playing. Reason: 'stream'
   Playtime: 508 ms
   Real duration: 1123 ms
   Difference: 615 ms
```

Regardless of the mp3 file and its duration, the difference is always between 300 and 600 milliseconds. For very short audio files (e.g. a soundboard with memes and/or sound effects) it really messes up the audio.

The "work-around" is to manually edit the files to add 600ms of silence at the end to make sure they're played in their entirety.

**Further details:**

- discord.js version: 11.5.1
- Node.js version: 12.16.3
- Operating system: Windows 10 Pro N (Build 18363)
- Priority this issue should have – please be realistic and elaborate if possible: Up to you really. I think it's pretty important that files are played for their full duration.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by danbulant** [comment] 2020-06-15 09:59
Getting same issue, but it's quite random - sometimes, it plays until the very end (like it should), but sometimes it stops too early. This isn't really noticeable when playing music (as it most of times have nearly silence at the end), but when I was using TTS (text-to-speech), it sometimes cut off too early

**Comment by iCrawl** [comment] 2020-06-19 09:58
Isn't this a duplicate of #3362

**Closed** 2020-12-12 14:17 UTC
Labels: s: unverified, t: voice, type: bug
