### ISSUE TITLE
Capturing Unintelligible Voice Recordings | VoiceConnection.On("speaking"...

### ISSUE THREAD

**Issue by Kunikita** [discordjs/discord.js#3754] opened 2020-01-31 20:38 UTC
**Our discord bot all of the sudden stopped capturing unintelligible voice recordings. This happened a few months ago, but I haven't been able to figure out what the problem is. We haven't made any changes to our code since this started working, which leaves me to believe Discord did something to the audio stream.**

**I've reach out to Discord but haven't gotten an answer back on this yet. Is anyone else experiencing this problem?**

```js

   //Code inside  voiceConnection.on('speaking', (user, speaking)...
    const voiceChannel = voiceConnection.channel;
    const guild = voiceChannel.guild;

    //Write recording to stream...
    const fileStream = new FileWriter(recordPath, {
        sampleRate: 48000,
        channels: 2,
        bitDepth: 48000,
    });

    receiver.createOpusStream(user).pipe(fileStream);

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 10.16.3
- Operating system: Windows 10, 64bit Enterprise
- Priority this issue should have – Very High: Collaboration with Discord a many other big companies in the industry.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment] 2020-01-31 21:20
Is this not just a duplicate of #3524?

**Closed** 2020-01-31 21:46 UTC
Labels: s: duplicate
