### ISSUE TITLE
Why can't Bots Join Other Servers?

### ISSUE THREAD

**Issue by ruchibuchi1** [discordjs/discord.js#2475] opened 2018-04-14 17:52 UTC
It seems possible according to this other issue:  https://github.com/discordjs/discord.js/issues/233

Also, if you say this issue belongs to the official server, could you explain more?  What is the official server?  In my opinion the question belongs here because this is an issue forum related to discord.js issues, and I am wondering about the capabilities of discord.js.

Thank you

**Comment by iCrawl** [comment] 2018-04-14 17:53
Duplicate of #2474

Please don't just open new issues and keep the conversation relevant to the thread.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Closed by iCrawl** 2018-04-14 17:53 UTC
