### ISSUE TITLE
Warn non-string Application ID and Guild IDs

### ISSUE THREAD

**Issue by StoneMoney** [discordjs/discord.js#8894] opened 2022-12-01 07:28 UTC
### Which package is the feature request for?

discord.js

### Feature

Given that discord supplies numerical Application IDs (at least at the moment) it's prone to being interpreted as an integer.

With the number of people responding to [my comment about their own bugs](https://www.reddit.com/r/Discord_Bots/comments/pmcjh3/discordapierror10002_unknown_application/hpp34zy/) over on r/Discord_Bots and #6362, it's a blunder quite a few have fallen into.

Problem scenario:
```
config.json
{
    "token": "<token>",
    "clientId": 1047768308851679252,
    "guildId": 481352312892162049
}
```
Output after running the [command deployment demo](https://discordjs.guide/creating-your-bot/command-deployment.html#where-to-deploy):
```
DiscordAPIError[10002]: Unknown Application
    at SequentialHandler.runRequest (/~/Projects/demo-discordbot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/~/Projects/demo-discordbot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/~/Projects/demo-discordbot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async /~/Projects/demo-discordbot/index.js:26:16 {
  requestBody: { files: undefined, json: [] },
  rawError: { message: 'Unknown Application', code: 10002 },
  code: 10002,
  status: 404,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/1047768308851679200/guilds/481352312892162049/commands'
}
```

### Ideal solution or implementation

If supplied a client ID/guild ID in non-string format, throw exception that the user is supplying incorrect type

### Alternative solutions or implementations

Alternatively make it clear in the guide documentation that the client and guild ids MUST be strings

### Other context

Ran on discord.js 14.7.0

**Comment by kyranet** [comment] 2022-12-01 09:12
We make it clear in the docs that snowflakes are strings, not numbers. Everything in the guide uses strings for IDs (and correctly displays them), see [here](https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands) for example.

**Comment by Colton1070** [comment] 2022-12-03 18:35
> We make it clear in the docs that snowflakes are strings, not numbers. Everything in the guide uses strings for IDs (and correctly displays them), see [here](https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands) for example.

Yet here we are debating how often someone might fall victim to this type of thing, especially when building a multi-thousand-line bot. Unknown interaction has to be the **worst** error in Discord JS as it:
Doesn't tell you what actually went wrong.
Doesn't tell you *where* it went wrong via any type of useable stack trace.

If my bot gets an error like this in one of its many files, and I'm not aware of it. I have to assume it's just Discord timing out an interaction, rather than a real issue in my code as there is no way for me to find it without searching my entire codebase for it.

**Comment by Qjuh** [comment] 2022-12-04 07:50
The error in your initial post isn’t `Unknown Interaction` though, it’s `Unknown Application`, which literally tells you you pass an ID of an application that doesn’t exist.
To get useful stacktraces for `Unknown Interaction` you need to await your reply, editReply, followUp, deferReply, … calls since that’s how you get stacktraces including where the rejection happens, as the rejection will happen outside of the callers scope otherwise. That’s how Promises work and nothing discord.js can solve for you.

**Comment by kyranet** [comment] 2022-12-05 08:46
> Yet here we are debating how often someone might fall victim to this type of thing, especially when building a multi-thousand-line bot.

People who have successfully built such large codebases should already be aware that in no moment we accept numbers, but strings. This is also enforced by the fact you can't use numeric IDs anywhere, not even for getting a member by its ID.

In fact this is not even a JavaScript limitation, take `1049241165335113738` for example, if you do `console.log(1049241165335113738);`, it won't log `1049241165335113738`, but rather `1049241165335113700`, or comparing them side by side:

```diff
+ 1049241165335113738
- 1049241165335113700
```

In order to keep the full representation, we may use either strings or bigints. However, the latter is not supported in JSON (`JSON.stringify(1049241165335113738n)` will result on a `TypeError: Do not know how to serialize a BigInt` error.

> Unknown interaction has to be the worst error in Discord JS as it:
> Doesn't tell you what actually went wrong.
> Doesn't tell you where it went wrong via any type of useable stack trace.

A few things about:

- `Unknown Application` (the error you're reporting) and `Unknown Interaction` (the one you're complaining about) are completely different errors. One is caused by trying to push commands with an application that doesn't exist, while the other is caused by trying to reply an interaction more than 3 seconds late (or edit a response after 15 minutes).
- Our errors are as helpful as Discord's errors are, blame them if the errors are useless, not us.
- Adding to what @Qjuh mentioned: JavaScript is bad at tracking, async operations can run simultaneously and may be operated many times during a sync execution, and this would potentially cause a lot of duplicated stack traces, which ultimately leads to a worse runtime performance. To solve this, the underlying engine Node.js uses has a requirement to use `await`. See https://bit.ly/v8-zero-cost-async-stack-traces for more information.

I'll be closing this issue as `wontfix` and `invalid`. I hope this answer satisfies you.

**Closed by kyranet** 2022-12-05 08:46 UTC
Labels: feature request
