### ISSUE TITLE
Permissions value incorrect

### ISSUE THREAD

**Issue by SirDeadlystrike** [discordjs/discord.js#2008] opened 2017-10-06 19:56 UTC
**This is another one of those "It happens somtimes" issues that seem to pop up at random**

I have recent noticed a large influx of users who use my bot telling me that their getting messages saying the bot doesn't have X permission when it does.

I have been able to confirm that on occasion, permissions are falling out of sync or are just plain wrong. When this happens Evaling the Permissions for the clientUsers member object will return a bitfield thats wrong. Unfortunately, Wrong is as specific as i can get, as its seemingly a random set of permissions different to each guild having the issue. Upon a restart of the shard with the issue permissions are once again reporting correctly. 

**Further details:**

- discord.js version: Master https://github.com/hydrabolt/discord.js/commit/743668a10d4cd141b2b819a1769a342523840ef3
- node.js version: 8.5
- Operating system: Ubuntu 16.x
- Priority this issue should have – please be realistic and elaborate if possible: high, reporting invalid permissions could cause huge security concerns for server owners when dealing with moderation among other things

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by retro-cat** [comment] 2017-10-08 12:55
Did you make sure you are checking channel and not guild permissions as bot could have overwritten permissions on channel than all guild

**Comment by gmedeadlystrike** [comment] 2017-10-08 12:57
Yep this issue was first noted using the commando framework which using `Permissions.missing` as
`const missing = message.channel.permissionsFor(message.author).missing(this.userPermissions);`
Later confirmed with a simple eval of `message.channel.permissionsFor(client.user)` I was able to make the bot do actions that contradict the permissions bitfield returned

**Comment by gmedeadlystrike** [comment] 2017-10-08 12:59
@retro-cat 
Yep this issue was first noted using the commando framework which uses `Permissions.missing` as
```js
const missing = message.channel.permissionsFor(message.author).missing(this.userPermissions);
```

Later confirmed with a simple eval of
```js
message.channel.permissionsFor(client.user)
``` 
I was able to make the bot do actions that contradict the permissions bitfield returned

**Comment by gmedeadlystrike** [comment] 2018-01-20 00:43
@hydrabolt I can't confirm for the latest master builds - One of my production bots runs an master commit from mid-december and it does happen occasionally on that.

**Comment by iCrawl** [comment] 2018-02-28 15:55
If you can not test this on latest master, I'll prolly close this since no one else commented on this issue so far.

**Comment by amishshah** [comment] 2018-08-09 12:17
See above

**Closed by amishshah** 2018-08-09 12:17 UTC
Labels: p: high, s: unverified, t: REST, type: bug

**Comment by Maksim990** [comment] 2021-06-06 00:29
Когда бот пытается проверить себя на наличие прав `message.guild.me.hasPermission("ADMINISTRATION")`, на сервере где стоит высокая проверка сообщений, или где включен 2fa, у меня появляется ошибка bitfield. И лиж некоторые проверки могут сработать на таких серверах
