### ISSUE TITLE
Receive interactions via HTTP POSTs

### ISSUE THREAD

**Issue by leecheeyong** [discordjs/discord.js#8846] opened 2022-11-19 10:11 UTC
### Which package is the feature request for?

discord.js

### Feature

Receving interactions via HTTP POSTs has been around for quite some time now and if we were just wanting to listen for slash commands, many extra loads are often bringing unnecessary issues to the us who uses discord.js

Discord.js comes with many features, although I can say most developers are not using everything that discord.js has to offer but we can hardly switch to any alternatives of discord.js as we are stuck with the builders, and basically how things work.

It'd be great if discord.js offers another version or maybe an option to choose whether to use HTTP POST rather than web socket which I often face issues such as rate limits.

### Ideal solution or implementation

I'm defiantly not understanding how djs works well enough but it'd make sense to have a separate package for this but, well again, maybe its possible in some way....

```js
const client = new Client({ httpMode: true });
```

### Other context

Nothing much actually, just looking for something that offers such simplicity as discordjs

I might just being dumb on this idea but I guess its possible as discord.js is currently working almost the same as receiving HTTP post request.

I'm probably focusing on these few key features like
- able to reply to an interaction as simple as `interaction.reply({ content: "MESSAGE" })`
- embed, slash, and all the builders

Yeah, people might just say "go make your own library", well, I've tried but there are too many things to change if I were to use the library I've created, btw it sucks in reality, like still wasn't able to get the feeling of writing a bot using djs. So it'd be great if the community can somehow suggest a solution or solve this issue.... Didn't have time to check what I've wrote, hopefully you all's understand.

**Comment by Jiralite** [comment] 2022-11-19 10:18
Duplicate of #7231.

**Closed by Jiralite** 2022-11-19 10:18 UTC
Labels: feature request
