### ISSUE TITLE
only 1 shard dont work

### ISSUE THREAD

**Issue by TheMonsters29** [discordjs/discord.js#3961] opened 2020-03-18 12:21 UTC
my 33. shard get this error i need help 
`method:` 'post' }
(node:7274) UnhandledPromiseRejectionWarning: Error: Shard 33's Client took too long to become ready.
    at Timeout.setTimeout [as _onTimeout] `(/home/bot/node_modules/discord.js/src/sharding/Shard.js:89:31)`
i have 80 shard

**Comment by iCrawl** [comment] 2020-03-18 12:22
You already posted in this issue #3956, so why open a new one?

Duplicate of #3956

**Comment by TheMonsters29** [comment] 2020-03-18 12:23
you all right i need fast help :/

**Closed by iCrawl** 2020-03-18 12:22 UTC
Labels: s: unverified, type: bug
