### ISSUE TITLE
HTTPError [AbortError]: The user aborted a request

### ISSUE THREAD

**Issue by Vozmak** [discordjs/discord.js#4307] opened 2020-05-20 23:16 UTC
I recently started getting an error "HTTPError [AbortError]: The user aborted a request.". Moreover, on different bots, and this has never happened before. And now appears in all bots.
Tell me what this may be related to. Thanks

**Comment by DELUUXE** [comment] 2020-05-28 10:19
Im also getting this error every now and then
```
HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/bot/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'AbortError',
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
```

it also seems that the following error seems to occur right before the one above:
```
[WS => Manager] Manager was destroyed. Called by:
Error: MANAGER_DESTROYED
    at WebSocketManager.destroy (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:335:54)
    at Client.destroy (/bot/node_modules/discord.js/src/client/Client.js:235:13)
    at Client.login (/bot/node_modules/discord.js/src/client/Client.js:224:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
````
But i don't know if they two are related to eachoter directly.

Both seem to occur before the bot can start, causing it to sit offline untill restarted.

**Comment by Vozmak** [comment] 2020-05-28 21:35
> Im also getting this error every now and then
> 
> ```
> HTTPError [AbortError]: The user aborted a request.
>     at RequestHandler.execute (/bot/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   name: 'AbortError',
>   code: 500,
>   method: 'get',
>   path: '/gateway/bot'
> }
> ```
> 
> it also seems that the following error seems to occur right before the one above:
> 
> ```
> [WS => Manager] Manager was destroyed. Called by:
> Error: MANAGER_DESTROYED
>     at WebSocketManager.destroy (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:335:54)
>     at Client.destroy (/bot/node_modules/discord.js/src/client/Client.js:235:13)
>     at Client.login (/bot/node_modules/discord.js/src/client/Client.js:224:12)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> But i don't know if they two are related to eachoter directly.
> 
> Both seem to occur before the bot can start, causing it to sit offline untill restarted.

im getting AbortError parth - message, reaction, etc

**Comment by DarkMio** [comment] 2020-06-11 11:31
I'm running into the exact same issue, the uplink and latency to the API endpoints (by connecting manually from the host machine) is low:

```js
 $ node index.js
Logging in...
HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/opt/rabscuttle/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
```

Code-snippet isn't all too exciting either:

```js
"use strict";

const Discord = require('discord.js');
const client = new Discord.Client();
const config = require("./data/config.json");

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.on('message', msg => {
    if (msg.content === '!bark') {
        msg.reply('Bork');
    }
});

console.log("Logging in...");

client.login(config.token).then(() => {
    console.log("Setting username & acitivity.");
    client.user.setUsername(config.name);
    client.user.setActivity(config.activity, {type: "WATCHING"});
}).catch(e => console.log(e));
```

I have tried to regenerate the token, create a new app, rename the app and so on - it seems like the socket times out before the API gateway can respond quick enough to it (?), however connecting manually to the websocket gives sub-second response times.

**Comment by iCrawl** [comment] 2020-06-19 09:51
Duplicate of #3471

**Closed by iCrawl** 2020-06-19 09:51 UTC
Labels: s: unverified, type: bug
