### ISSUE TITLE
Guild isn't cached.

### ISSUE THREAD

**Issue by Skiuel** [discordjs/discord.js#5349] opened 2021-02-23 18:55 UTC
on discord people says me its strange . 
`index.js
```const {Client} = require("discord.js");
const client = new Client()
const token = require("../src/config/config").token
const cmdInit = require("../src/handlers/command.handler")
const chalk = require("chalk")
const verify = require("../src/handlers/verification.handler")
const lvl = require("../src/handlers/lvl.handler")
const stats = require("../src/handlers/stats.handler")

//stats(client)
verify(client)
cmdInit(client)
lvl(client)

client.on("ready", () => {
  console.log(chalk.cyan(`Correctly logged as: ${client.user.tag}`))
})


client.login(token);```
stats.handler.js
```const { MessageEmbed } = require("discord.js")
module.exports = (client) => {
  =====>  const guild = client.guilds.cache.find(g => g.id === "812802845602480128") <========== why is undefined?

    const online = guild.members.cache.filter(member => member.presence.status !== "offline").size
    const offline = guild.members.cache.filter(member => member.presence.status == "offline").size

    const channel = guild.channels.cache.find(c => c.id === "813761877879816204")
    const msg = channel.messages.fetch("813763697729470525")

    const embed = new MessageEmbed()
    .setTitle("Statystyki")
    .addFields(
        {name: "Online", value: online}
        )
    .setColor("#33ff8b")
    .setFooter("Statystyki są odświeżane co 5min", "https://i.imgur.com/pJ5UiAv.png")
    msg.edit(embed)

}```
`
that's code

`console.log(client.guilds.cache)`
give this
`guilds: GuildManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {}
  },
  `
  But bot is online. And commands working.

**Comment by almostSouji** [comment] 2021-02-23 18:56
duplicate of https://github.com/discordjs/discord.js/issues/5348

**Closed by almostSouji** 2021-02-23 18:56 UTC
Labels: question (please use Discord instead)

**Comment by Skiuel** [comment] 2021-02-23 19:01
> duplicate of #5348

On discord says me "It's strange guilds are always cached so it shouldnt be empty"

**Comment by almostSouji** [comment] 2021-02-23 19:02
> Because you are instantiating a whole new discord client that's not even logged in. You should be accessing your already created client instance
