### ISSUE TITLE
'TypeError: Cannot read property 'has' of null' when joining voice channels.

### ISSUE THREAD

**Issue by MrAtomik** [discordjs/discord.js#2336] opened 2018-02-11 09:01 UTC
**Please describe the problem you are having in as much detail as possible:**
Basically, I am trying to play music with my bot. However, when I try and join the channel it results in the following error:
```
TypeError: Cannot read property 'has' of null
    at VoiceChannel.get joinable [as joinable] (C:\Users\--\--\--\node_modules\discord.js\src\structures\VoiceChannel.js:64:47)
    at Promise (C:\Users\--\--\--\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:51:20)
    at new Promise (<anonymous>)
    at ClientVoiceManager.joinChannel (C:\Users\--\--\--\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:50:12)
    at VoiceChannel.join (C:\Users\--\--\--\node_modules\discord.js\src\structures\VoiceChannel.js:119:30)
    at Promise (C:\Users\--\--\--\index.js:53:21)
    at new Promise (<anonymous>)
    at Object.joinChannel (C:\Users\--\--\--\index.js:50:12)
    at message.guild.members.fetch.then (C:\Users\--\--\--\commands\play.js:16:31)
    at <anonymous>
```

**Include a reproducible code sample here, if possible:**
```js
if (member.voiceChannel) {
    channel = member.voiceChannel;
    channel.join().then((connection) => {
        console.log("Joined");
    }).catch((error) => {
        console.error("Error: " + error);
    })
} else {
    console.log("Not in channel");
}
```

**Further details:**

- discord.js version: @12.0.0-dev
- node.js version: 5.2.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: I'm not too sure. It just makes voice not work at all. (could be high since it completely makes voice not work)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 66c0512de2a3bda5e3ae5f9443425a242987abd5

**Comment by k3rn31p4nic** [comment] 2018-02-11 09:15
Could be similar to #2319 as from MrAtomik's error trace the error can be pointed to: https://github.com/discordjs/discord.js/blob/master/src/structures/VoiceChannel.js#L64 which returns `null` for  `Channel.permisisonsFor(client.user)` (Similar to #2319)

**Comment by SuperOP535** [comment] 2018-02-11 16:00
you need node.js 8.x+

**Comment by SpaceEEC** [comment] 2018-02-11 17:31
Duplicate of #2252 and related to #1870.
If you have _any_ clue on how to reproduce, this feel free to let me know.

**Closed by SpaceEEC** 2018-02-11 17:31 UTC
Labels: s: duplicate, t: caching, type: bug
