### ISSUE TITLE
The provided webhook URL is not valid

### ISSUE THREAD

**Issue by kazax-inc** [discordjs/discord.js#10663] opened 2024-12-19 00:44 UTC
### Which package is this bug report for?

discord.js

### Issue description

previously webhhook url use the domain **discord.com** (https://discord.com/api/webhooks/..), but actualy new webhook créated from the app return an url with de domain **discordapp.com** (https://discordapp.com/api/webhooks/...)

the webhook client cannot be instantiated with the new url format

the old url format is still valid currently, the new format can be converted into the old one, but not directly supported by discord.js.
https://github.com/discordjs/discord.js/blob/f1bce54a287eaa431ceb8b1996db87cbc6290317/packages/discord.js/src/util/Util.js#L408

### Versions

- discord.js: 14.16.3

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment] 2024-12-19 00:46
Duplicate of https://github.com/discordjs/discord.js/issues/7189.

**Closed by Jiralite** 2024-12-19 00:46 UTC
Labels: bug, need repro, packages:discord.js
