### ISSUE TITLE
Allow readonly objects for `ClientOptions`

### ISSUE THREAD

**Issue by bbrk24** [discordjs/discord.js#7028] opened 2021-11-24 14:25 UTC
### Feature

The object I had been passing into the `Client` constructor in v12 had readonly properties. I was surprised that this does not work in v13.

### Ideal solution or implementation

The `Client` constructor should not attempt to mutate its argument.

### Alternative solutions or implementations

The workaround I'm using is something like this:

```js
import { Client } from 'discord.js';
import _ from 'lodash';

const client = new Client(_.cloneDeep(config));
```

I can't use `{ ...config }` because objects (such as `config.allowedMentions`) still have readonly properties.

**Comment by kyranet** [comment] 2021-11-24 16:45
I think this is a duplicate of #5267, which has a library-wide scope.

**Comment by kyranet** [comment] 2021-12-06 05:56
We decided internally to use an alternative approach to validate and default the different options, and I'll submit a PR within the next days. Sadly, this will be semver-major :/

**Closed** 2022-08-10 16:58 UTC
Labels: feature request, packages:discord.js
