### ISSUE TITLE
Error when trying to connect to voice channel

### ISSUE THREAD

**Issue by Terradice** [discordjs/discord.js#3074] opened 2019-02-10 18:08 UTC
**Please describe the problem you are having in as much detail as possible:**
Error when trying to connect to voice channel, authentication failed

**Include a reproducible code sample here, if possible:**
`const connection = message.member.voiceChannel.join()`
```js

(node:23368) UnhandledPromiseRejectionWarning: Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (C:\Users\terra\Desktop\DiscordBot\node_modules\discord.js\src\client\voice\VoiceConnection.js:256:27)
    at connectTimeout.client.setTimeout (C:\Users\terra\Desktop\DiscordBot\node_modules\discord.js\src\client\voice\VoiceConnection.js:285:18)
    at Timeout.setTimeout (C:\Users\terra\Desktop\DiscordBot\node_modules\discord.js\src\client\Client.js:433:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:23368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Further details:**
- discord.js version: ^11.4.2
- Node.js version: v8.11.3
- Operating system: Windows 10

- [x] I have also tested the issue on latest master, commit hash

I have FFMPEG installed, node-opus, opusscript, everything works fine but when i try to connect to voice channel it throws an error

Full code:
```js
    youTube.search(args.join(" "), 1, function(error, result) {
      let id = result.items[0].id.videoId;
      let link = "https://www.youtube.com/watch?v=" + id;
      const connection = message.member.voiceChannel.join().then(connection => {
          const stream = ytdl(link, { filter: 'audioonly' });
          const dispatcher = connection.playStream(stream, streamOptions);
          dispatcher.on('end', () => {
              dispatcher.destroy();
          });
      });
    });
```

EDIT:
Tried it on master, still get an error, but its slightly different
`UnhandledPromiseRejectionWarning: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.`

**Comment by SpaceEEC** [comment] 2019-02-10 18:20
This might be related to #3005
Can you check whether the bot has permissions to actually connect?

**Comment by Terradice** [comment] 2019-02-10 18:34
> This might be related to #3005
> Can you check whether the bot has permissions to actually connect? (Specifically has VIEW_CHANNEL)

Yeah, even after i enabled them it doesnt work
![image](https://user-images.githubusercontent.com/35463279/52537806-48f4c300-2d73-11e9-8bde-8ddaeedfde94.png)

**Comment by kyranet** [comment] 2019-02-10 18:36
Just FYI, you have stable, to install master you do `npm i discordjs/discord.js`. It has a lot of bugfixes overall, including music.

If you can't install it, make sure you have [git](https://git-scm.com/downloads) installed.

**Comment by Terradice** [comment] 2019-02-10 18:43
> Just FYI, you have stable, to install master you do `npm i discordjs/discord.js`. It has a lot of bugfixes overall, including music.
> 
> If you can't install it, make sure you have [git](https://git-scm.com/downloads) installed.

I am using master now, sorry for the irrelevent problem but i cant get the user voicechannel? `message.member.voiceChannel` returns undefined

**Comment by kyranet** [comment] 2019-02-10 18:48
Everything is in [GuildMember#voice](https://discord.js.org/#/docs/main/master/class/GuildMember?scrollTo=voice), please go to the [Discord server](https://discord.gg/bRCvFy9) for more information.

**Comment by Terradice** [comment] 2019-02-10 18:54
> Just FYI, you have stable, to install master you do `npm i discordjs/discord.js`. It has a lot of bugfixes overall, including music.
> 
> If you can't install it, make sure you have [git](https://git-scm.com/downloads) installed.

See edit

**Comment by amishshah** [comment] 2019-02-10 20:23
Could you update to the latest commit (https://github.com/discordjs/discord.js/commit/aab3523fb5b60d21d20cbf2be01c32bdf21aa8ae) and try the following to produce some more debug information:

```js
client.on('debug', console.log);
```

You should see output something like this:
![image](https://user-images.githubusercontent.com/10330923/52539029-83f5f700-2d71-11e9-8381-939bf812de35.png)

If you could try this again and send me the full output from this log -- this will contain sensitive information so I'd recommend messaging me on Discord at hydrabolt#0001. However, you should still be ok to post the details here on GitHub if you remove your IP address from the logs and partially redact any IDs.

**Comment by amishshah** [comment] 2019-02-10 20:28
Actually, this issue is a duplicate of #2979 so I'm going to close this, if you have any more information -- especially debug information as described as above -- please message me on Discord or on the other issue.

**Closed by amishshah** 2019-02-10 20:28 UTC

**Comment by Whirl21** [comment] 2021-06-16 09:56
This is also a issue with mainly replit 
try making a new repl or changing host
