### ISSUE TITLE
Mock/ Dummy data for discordjs

### ISSUE THREAD

**Issue by Naxey** [discordjs/discord.js#7027] opened 2021-11-24 14:23 UTC
### Feature

Any way to get dummy data to not always rely on the discord API, which would enable offline work

### Ideal solution or implementation

Dummy data to be easily replaced with the real discord API for switching between the dummy data and the real API link.

**Comment by almostSouji** [comment] 2021-11-24 14:36
Duplicate of https://github.com/discordjs/discord.js/issues/727 / https://github.com/discordjs/discord.js/discussions/6179

**Closed by almostSouji** 2021-11-24 14:36 UTC
Labels: duplicate, feature request
