### ISSUE TITLE
Expired invites does not emit InviteDelete event !!

### ISSUE THREAD

**Issue by SENPAY98K** [discordjs/discord.js#10589] opened 2024-11-02 21:54 UTC
### Which package is this bug report for?

discord.js

### Issue Description
As title says, the invites that expires after specified time, bots does not trigger any InviteDelete event.
### Steps to Reproduce
Create an invite with an expiration time (30 minutes), and wait for it to expire.

### Versions

Node.js 20.18.0
Discord.js 14.16.3
Windows 11
Linux64 Ubuntu

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution, GuildMessagePolls, DirectMessagePolls

**Comment by Jiralite** [comment] 2024-11-02 21:58
Duplicate of https://github.com/discord/discord-api-docs/issues/7249.

**Closed by Jiralite** 2024-11-02 21:58 UTC
Labels: bug, need repro, packages:discord.js
