### ISSUE TITLE
presenceUpdate event return newmember and new member

### ISSUE THREAD

**Issue by midora41** [discordjs/discord.js#2390] opened 2018-03-12 05:53 UTC
`client.on('presenceUpdate', function(newm,oldm){console.log(newm.user.presence);console.log(oldm.user.presence)});`

Presence { status: 'idle', game: null }
Presence { status: 'idle', game: null }

**Comment by SpaceEEC** [comment] 2018-03-12 06:39
Duplicate of #1067 and #2025.

**Closed by SpaceEEC** 2018-03-12 06:39 UTC
