### ISSUE TITLE
The method resume of the class StreamDispatcher is not Working

### ISSUE THREAD

**Issue by Datzu712** [discordjs/discord.js#5773] opened 2021-06-06 19:45 UTC
Hello, I have problems with the resume method of the StreamDispatcher class in the node version v14.17.0, I tried it in the version v14.15.5 and it works

```js
// (Node v14.17.0) Music doesn't resume
connection.dispatcher.resume()

//  (Node v14.15.5) Music resumes
connection.dispatcher.resume()
```

**Further details:**

- discord.js version: v12.5.3
- Node.js version: v14.17.0
- Operating system: Ubuntu
- Priority this issue should have: low

**Comment by iCrawl** [comment] 2021-06-07 07:14
Duplicate of #5300

**Closed by iCrawl** 2021-06-07 07:14 UTC
Labels: s: unverified, t: voice, type: bug
