### ISSUE TITLE
Channel Types

### ISSUE THREAD

**Issue by phaalonso** [discordjs/discord.js#5363] opened 2021-03-01 05:03 UTC
When getting a channel using the channel manager, TS don't expect that the type can be a TextChannel. Requiring the user to verify and make a type cast in the channel so he can send messages.

![image](https://user-images.githubusercontent.com/26033899/109454336-c5c66880-7a32-11eb-9d3f-454f547b35ab.png)

```ts
const canalCompras = guild.channels.cache.find(ch => ch.name === 'compras');

console.log('isText', canalCompras.isText());

if (canalCompras) {
    canalCompras.send('Hello');
}
```

Working code:
```ts
const canalCompras = guild.channels.cache.find(ch => ch.name === 'compras');

console.log('isText', canalCompras.isText());

if (canalCompras && canalCompras.isText()) {
    (<TextChannel> canalCompras).send('Hello');
}
```

Is possible adding the other possible returns types for the channels.(resolve|cache.get)?

**Further details:**

- discord.js version: ^12.1.1
- Node.js version: v14.16.0
- Operating system: PopOS 20.04

**Comment by Fyko** [comment] 2021-03-01 05:12
This is a duplicate of https://github.com/discordjs/discord.js/issues/4893

You need to explicitly type-cast the variable:
```ts
import type { TextChannel } from 'discord.js';

const channel = guild.channels.cache.find(ch => ch.name === 'compras');
(channel as TextChannel).send('Hello');
```

**Closed** 2021-03-01 09:38 UTC
Labels: s: duplicate
