### ISSUE TITLE
Event stuff

### ISSUE THREAD

**Issue by KadePcGames** [discordjs/discord.js#2994] opened 2018-12-20 00:38 UTC
**Please describe the problem you are having in as much detail as possible:**
My bot is crashing for no reason

**Include a reproducible code sample here, if possible:**
```js


events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (/root/robo/E/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/root/robo/E/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at _receiver.cleanup (/root/robo/E/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/root/robo/E/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/root/robo/E/node_modules/ws/lib/websocket.js:206:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)


```

**Further details:**
- discord.js version: latest
- Node.js version: latest build
- Operating system: ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: High

**Comment by LewisLector** [comment] 2018-12-20 04:05
This is the same as #2555 you should handle your error event.

**Comment by kyranet** [comment] 2018-12-20 19:06
Duplicate of #2555

**Closed** 2018-12-21 20:53 UTC
Labels: s: duplicate
