### ISSUE TITLE
rate limit per user doesnt seem to work

### ISSUE THREAD

**Issue by SkyBlockDev** [discordjs/discord.js#5354] opened 2021-02-26 11:17 UTC
**Please describe the problem you are having in as much detail as possible:**
Im trying to set the rate limit per user in a channel using message.channel.setRateLimitPerUser(500)

**Include a reproducible code sample here, if possible:**

```js
message.channel.setRateLimitPerUser(500)
```

**Further details:**
![image](https://user-images.githubusercontent.com/72335827/109293704-731b5f80-782c-11eb-83a8-033fb792cc1a.png)

- discord.js version: main branch
- Node.js version: v14.x
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: ['GUILDS', 'GUILD_MESSAGES', 'GUILD_WEBHOOKS', 'GUILD_INTEGRATIONS']
- other: none

- I have also tested the issue on latest master, commit hash: `d744e51`

**Comment by almostSouji** [comment] 2021-02-26 11:19
fixed in<https://github.com/discordjs/discord.js/pull/5251> 
duplicate of #5273

**Closed by almostSouji** 2021-02-26 11:19 UTC
Labels: s: duplicate, type: bug
