### ISSUE TITLE
guildMemberAdd and guildMemberRemove not working.

### ISSUE THREAD

**Issue by PineAppleGrits** [discordjs/discord.js#4950] opened 2020-10-28 18:48 UTC
**Please describe the problem you are having in as much detail as possible:**
My discord bot isn't detecting events. I dont have any warning or error, it just doesnt detect the events, even guildCreate.
**Include a reproducible code sample here, if possible:**

```js
example: client.on('guildMemberAdd', console.log);
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:
npm 6.14.8
node 12.19.0
discordjs v12
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by anandre** [comment] 2020-10-28 18:50
Duplicate of issue #4949

**Comment by almostSouji** [comment] 2020-10-28 18:51
> :gear:  **Events for privileged intents are not sent if not enabled:**
• Discords FAQ on this change: <https://dis.gd/gwupdate>
• your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
• your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
• you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: **update to v12**, we no longer support v11.
>
> **Symptoms you might be experiencing with discord.js**:
• member caches are empty     *(or only have very few entries)*
• user cache is empty      *(or has only very few entries)*
• fetching members times out
• login times out if you try to fetch all members on startup
• The client events `"guildMemberAdd"`, `"guildMemberRemove"`, `"guildMemberUpdate"` do not emit
• `Guild#memberCount` returns count as of ready

**Closed by almostSouji** 2020-10-28 18:51 UTC
Labels: question (please use Discord instead), s: duplicate

**Comment by PineAppleGrits** [comment] 2020-10-28 19:06
<3 thank u!!! my Discord bot is currently in process to be verified, since my bot is in, i can't emit those events, thank u!!

**Comment by M0rizu** [comment] 2021-01-28 16:49
go to https://discord.com/developers/applications/ then open the application, go to "Bot", and enable Server Members Intent.
![image](https://user-images.githubusercontent.com/67523169/106170524-50cfec80-616f-11eb-8732-e8333be9f7dc.png)
