### ISSUE TITLE
Builders - Shlashs commands

### ISSUE THREAD

**Issue by Gekki-beep** [discordjs/discord.js#8227] opened 2022-07-04 09:59 UTC
### Which package is this bug report for?

builders

### Issue description

When it comes to making subcommands, we have an error that states that the subcommand needs a type : 

`DiscordAPIError: Invalid Form Body
20.options[0].type: This field is required
20.options[1].type: This field is required
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ApplicationCommandManager.set (/home/container/node_modules/discord.js/src/managers/ApplicationCommandManager.js:156:18) {
  method: 'put',
  path: '/applications/APPLICATION/guilds/GUILDS/commands',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ],
    files: []
  }
}`

### Code sample

```typescript
Documentation code :

const { SlashCommandBuilder } = require('@discordjs/builders');

const data = new SlashCommandBuilder()
	.setName('info')
	.setDescription('Get info about a user or a server!')
	.addSubcommand(subcommand =>
		subcommand
			.setName('user')
			.setDescription('Info about a user')
			.addUserOption(option => option.setName('target').setDescription('The user')))
	.addSubcommand(subcommand =>
		subcommand
			.setName('server')
			.setDescription('Info about the server'));
```

### Package version

0.15.0

### Node.js version

16.9

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment] 2022-07-04 10:22
Duplicate of #8208.

**Closed by Jiralite** 2022-07-04 10:22 UTC
Labels: bug, need repro
