### ISSUE TITLE
Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by xcjs** [discordjs/discord.js#10377] opened 2024-07-03 00:15 UTC
### Which package is this bug report for?

discord.js

### Issue description

1. Provide a bot with buttons.
2. Click one of the buttons.

### Code sample

```typescript
const self = this;

this.#client.on(Events.InteractionCreate, async (interaction) => await this.#onInteraction.call(self, interaction));

async #onInteraction(interaction: ButtonInteraction): Promise<void> {

}
```

### Versions

```
"discord.js": "^14.14.1"
```

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

MessageContent

**Comment by xcjs** [comment] 2024-07-03 00:16
Stacktrace here: 

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'reduce')
    at BaseInteraction (node_modules\discord.js\src\structures\BaseInteraction.js:106:43)
    at MessageComponentInteraction (node_modules\discord.js\src\structures\MessageComponentInteraction.js:17:5)
    at ButtonInteraction (node_modules\discord.js\src\structures\ButtonInteraction.js:9:1)
    at handle (node_modules\discord.js\src\client\actions\InteractionCreate.js:90:25)
    at module.exports (node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at handlePacket (node_modules\discord.js\src\client\websocket\WebSocketManager.js:355:31)
    at <anonymous> (node_modules\discord.js\src\client\websocket\WebSocketManager.js:239:12)
    at emit (node_modules\@vladfrangu\async_event_emitter\dist\index.cjs:282:31)
    at <anonymous> (node_modules\@discordjs\ws\dist\index.js:1190:51)
    at emit (node_modules\@vladfrangu\async_event_emitter\dist\index.cjs:282:31)
    at onMessage (node_modules\@discordjs\ws\dist\index.js:1005:14)
    at processTicksAndRejections (internal/process/task_queues:95:5)
```

**Comment by santiherzfeld** [comment] 2024-07-03 00:17
Got same issue in all my bots suddenly

**Comment by J4Wx** [comment] 2024-07-03 00:18
Yeah - seemingly for any interaction type too, not just for buttons. I suspect this is a Discord API issue or change?

```
TypeError: Cannot read properties of undefined (reading 'reduce')
application-1  |     at new BaseInteraction (node_modules/discord.js/src/structures/BaseInteraction.js:106:43)
application-1  |     at new CommandInteraction (node_modules/discord.js/src/structures/CommandInteraction.js:16:5)
application-1  |     at new ChatInputCommandInteraction (node_modules/discord.js/src/structures/ChatInputCommandInteraction.js:13:5)
application-1  |     at InteractionCreateAction.handle (node_modules/discord.js/src/client/actions/InteractionCreate.js:90:25)
application-1  |     at module.exports [as INTERACTION_CREATE] (node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
application-1  |     at WebSocketManager.handlePacket (node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
application-1  |     at WebSocketManager.<anonymous> (node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
application-1  |     at WebSocketManager.emit (node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:282:31)
application-1  |     at WebSocketShard.<anonymous> (node_modules/@discordjs/ws/dist/index.js:1190:51)
application-1  |     at WebSocketShard.emit (node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:282:31)
```

**Comment by falcao-g** [comment] 2024-07-03 00:18
My bot that was running fine for 21 days has shown this also, it seems to be in all types of interactions

**Comment by xcjs** [comment] 2024-07-03 00:19
@J4Wx I'm suspecting this is some kind of infrastructure issue. I noticed a few other large service web sites acting odd recently.

**Comment by J4Wx** [comment] 2024-07-03 00:20
Yeah - this bot has been running (unmodified) for months without issue. I don't believe that this is a Discord JS issue.

**Comment by TAEMBO** [comment] 2024-07-03 00:20
This is a known issue due to unexpected API behavior changes. The current solution for now is to downgrade to discord.js v14.14.1.

**Comment by zastlx** [comment] 2024-07-03 00:26
same issue

**Comment by xcjs** [comment] 2024-07-03 00:27
@TAEMBO I'm seeing a completely different issue now - unknown interactions. My interactions are keyed to an enum, so that shouldn't be a problem.

**Comment by falcao-g** [comment] 2024-07-03 00:28
downgrading, (in my case, upgrading), fixed the issue for me in my bot, the funny thing is that both my bots were in ˆ14.9.0 version of discord.js and only one of them was affected, the bigger one

**Comment by xcjs** [comment] 2024-07-03 00:29
@falcao-g What version did you upgrade to?

**Comment by falcao-g** [comment] 2024-07-03 00:30
14.14.1

**Comment by xLittleJ** [comment] 2024-07-03 00:31
So, to fix it, change `this.entitlements = data.entitlements.reduce` to `this.entitlements = data.entitlements?.reduce`

**Comment by Jaynarol** [comment] 2024-07-03 00:33
14.15.3 

same issue just happen today after stable for long time and do not touch anything.

**Comment by CrusherNotDrip** [comment] 2024-07-03 00:33
Same thing happened to me
just downgraded to 14.15.1 for now (works for me)

**Comment by pfgtater** [comment] 2024-07-03 00:33
14.15.3

Downgraded to 14.14.1 and issue fixed. No idea what caused it

**Comment by falcao-g** [comment] 2024-07-03 00:35
this is an issue caused by Discord, from what i have seem, they are already aware of it, for us, we have two options, either changing the line of code to something like this: `this.entitlements = (data.entitlements ?? []).reduce` or changing the discord.js version to 14.14.1

**Comment by SENPAY98K** [comment] 2024-07-03 00:38
Same problem for latest version as well `v14.15.3`

**Comment by TundraShark** [comment] 2024-07-03 00:46
> This is a known issue due to unexpected API behavior changes. The current solution for now is to downgrade to discord.js v14.14.1.

Thank you so much, I thought I was going absolutely crazy since my code has not changed at all and suddenly everything just broke. After banging my head against the wall for two hours and seeing your post, setting the version to `14.14.1` fixed it for me.

**Comment by Romijoxx** [comment] 2024-07-03 00:58
Downgrading to 14.14.1 did not solve this issue for me. 
Which version are you using for discord-api-types, @discordjs/builders, @discordjs/rest?

**Comment by ImmaUgc** [comment] 2024-07-03 00:58
Same issue!

**Comment by Issuko-Adam** [comment] 2024-07-03 00:59
> this is an issue caused by Discord, from what i have seem, they are already aware of it, for us, we have two options, either changing the line of code to something like this: `this.entitlements = (data.entitlements ?? []).reduce` or changing the discord.js version to 14.14.1

saved my life

**Comment by TheFalloutOf76** [comment] 2024-07-03 01:00
downgrading to 14.14.1 worked for me 👍

**Comment by Rollphes** [comment] 2024-07-03 01:02
A similar error occurred in 14.14.1.
Perhaps it is not a continuous occurrence, but rather a rare case of data.entitlements being undefined.。

**Comment by hamidmirza1** [comment] 2024-07-03 01:16
any ideas on when it will be fixed?

**Comment by DJj123dj** [comment] 2024-07-03 06:08
I have the same issue on v14.15.3

**Comment by Jiralite** [comment] 2024-07-03 06:59
This was a Discord issue that is now resolved.

**Closed by Jiralite** 2024-07-03 06:59 UTC
Labels: bug, need repro, packages:discord.js
