### ISSUE TITLE
Client#channelUpdate still logs the same permission overwrite bits for old and new channel.

### ISSUE THREAD

**Issue by ZEUSGMJ** [discordjs/discord.js#6093] opened 2021-07-10 19:06 UTC
**Please describe the problem you are having in as much detail as possible:**
Updated Discord.js from `13.0.0-dev.5b6be0c.1625789033` to `13.0.0-dev.d6c43a5.1625918569` after noticing that [`#6082`](https://github.com/discordjs/discord.js/issues/6082) was fixed in [**`f72ce7c`**](https://github.com/discordjs/discord.js/commit/f72ce7c136cf2dfe31a67b190c00e30ba7d70bfa). Yet, while listening to the `channelUpdate` event, The Permissions overwrites for both old and new channel are still the same.
**Include a reproducible code sample here, if possible:**

```js
client.on('channelUpdate', (old, new) => {

console.log(old.permissionOverwrites.cache.array())
console.log(new.permissionOverwrites.cache.array())
})
```
**Steps to reproduce:**
- Create a new text channel.
- Add permission overwrite for a user/role.
- Same permission bits in allow and deny field for the old and new channel.

**Further details:**

- discord.js version: `13.0.0-dev.d6c43a5.1625918569`
- Node.js version: v16.3.0
- Operating system: Windows 10 21H1
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: `GUILDS`
- other: none

**Comment by DTrombett** [comment] 2021-07-10 19:07
Duplicate of #6082 and #6091
There's a PR to fix this already opened.

**Comment by ZEUSGMJ** [comment] 2021-07-10 19:11
> Duplicate of #6082 and #6091
> 
> ~~There's a PR to fix this already opened. #6093~~
> 
> Edit: It should be already fixed with this commit: https://github.com/discordjs/discord.js/commit/f72ce7c136cf2dfe31a67b190c00e30ba7d70bfa

Nope. Still logs the same bits.

**Comment by MattIPv4** [comment] 2021-07-10 19:12
Unable to reproduce as of f72ce7c136cf2dfe31a67b190c00e30ba7d70bfa, I can detect overwrites being added, removed and updated just fine.

**Comment by MattIPv4** [comment] 2021-07-10 19:14
@ZEUSGMJ You are reporting here that you updated to d6c43a5, which is before f72ce7c which was when the fix was merged...

**Comment by DTrombett** [comment] 2021-07-10 19:17
> Nope. Still logs the same bits.

The commit you provided is related to a pr merged 1 day ago. Try to update djs to get a newer commit.

**Comment by ZEUSGMJ** [comment] 2021-07-10 19:19
Oh, my bad. 😅
I'll update it right now and check it.

**Comment by ZEUSGMJ** [comment] 2021-07-10 19:33
Shouldn't `npm update discord.js@dev` update it to the latest one? Running the command would just say that it's up to date `(13.0.0-dev.d6c43a5.1625918569)`. Not sure what I'm missing/doing wrong.

**Comment by iCrawl** [comment] 2021-07-10 19:35
Dev releases are only cut every 12h.

**Comment by DTrombett** [comment] 2021-07-10 21:03
> Shouldn't `npm update discord.js@dev` update it to the latest one? Running the command would just say that it's up to date `(13.0.0-dev.d6c43a5.1625918569)`. Not sure what I'm missing/doing wrong.

The command is actually `npm i discord.js@dev`
Using the npm update doesn't always work.

**Comment by ZEUSGMJ** [comment] 2021-07-11 03:53
> > Shouldn't `npm update discord.js@dev` update it to the latest one? Running the command would just say that it's up to date `(13.0.0-dev.d6c43a5.1625918569)`. Not sure what I'm missing/doing wrong.
> 
> The command is actually `npm i discord.js@dev`
> Using the npm update doesn't always work.

Yeah, I also re-installed the package when trying to update it. But now it finally updated and it's working properly as expected.

**Closed** 2021-07-11 03:54 UTC
Labels: s: unverified, type: bug
