### ISSUE TITLE
TypeError on MESSAGE_REACTION_ADD

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#4840] opened 2020-09-22 18:25 UTC
**Please describe the problem you are having in as much detail as possible:**
Got few times a TypeError when receiving a MESSAGE_REACTION_ADD event.

![2020-09-22_2789](https://user-images.githubusercontent.com/19957779/93921970-99831f00-fd11-11ea-9c1e-2531807fba5b.png)

![2020-09-22_2790](https://user-images.githubusercontent.com/19957779/93922015-a7d13b00-fd11-11ea-8f9d-5ae6678c30d3.png)

**Further details:**

- discord.js version: latest master
- Node.js version: v12.18.3
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible: normal

**Relevant client options:**

- partials: ['REACTION','MESSAGE']
- gateway intents: 13999
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by monbrey** [comment] 2020-09-22 19:05
Have you tested this with partials enabled for `USER` and `GUILD_MEMBER` also?

**Comment by Koyamie** [comment] 2020-09-22 19:08
> Have you tested this with partials enabled for `USER` and `GUILD_MEMBER` also?

Nope, I don't even know in what particular case this does happen.
I only want the REACTION and MESSAGE partials enabled so testing with others doesn't make sense, goal is to fix in this particual case!

**Comment by wasdennnoch** [comment] 2020-09-22 19:10
Partials shouldn't make a difference here as the crash occurs before anything with partials was done. It crashes in a code path that's a straight line from the raw gateway event, without any partials branching. That comes after the crash.

**Comment by kyranet** [comment] 2020-09-22 20:30
Duplicate of #4821, which has been fixed by #4822.

**Comment by Koyamie** [comment] 2020-09-22 20:33
> Duplicate of #4821, which has been fixed by #4822.

I am using the very latest version of d.js, this merge inclued.
This means it is not fixed.

**Comment by kyranet** [comment] 2020-09-22 20:38
The patch was landed after 12.3.1 landed, if you're using master, can you please provide the commit hash? "Latest master" is ambiguous and may not be actually the latest.

**Comment by Koyamie** [comment] 2020-09-22 20:40
Sorry by latest master I mean latest commit, I'm up to date with this commit : 1e63f3756e814d6b1a2a9c17af9c2b28ce37e472

**Comment by kyranet** [comment] 2020-09-22 20:49
My bad, I have just confirmed the issue here, I approved the linked PR, sorry for not verifying properly 😅.

**Comment by Koyamie** [comment] 2020-09-22 20:52
No problem, will precise the commit next time!

**Closed** 2020-09-25 21:42 UTC
Labels: type: bug
