### ISSUE TITLE
Builders typescript error: Type does not satisfy the constraint 'unknown[]'.

### ISSUE THREAD

**Issue by Paultje52** [discordjs/discord.js#8249] opened 2022-07-08 10:01 UTC
### Which package is this bug report for?

builders

### Issue description

1. Install the latest `@discordjs/builders` package: `npm i -s @discordjs/builders`
2. Open `index.d.ts` file in `node_modules/@discordjs/builders/dist` and see the error.

This also causes the builds of typescript bots to fail.

```typescript
node_modules/@discordjs/builders/dist/index.d.ts:14:78 - error TS2344: Type '{ name: string; value: string; inline: boolean | undefined; }' does not satisfy the constraint 'unknown[]'.
  Type '{ name: string; value: string; inline: boolean | undefined; }' is missing the following properties from type 'unknown[]': length, pop, push, concat, and 29 more.

 14 declare const embedFieldsArrayPredicate: _sapphire_shapeshift.ArrayValidator<{
                                                                                 ~
 15     name: string;
    ~~~~~~~~~~~~~~~~~
... 
 17     inline: boolean | undefined;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 18 }>;
    ~


Found 1 error in node_modules/@discordjs/builders/dist/index.d.ts:14
```

### Package version

@discordjs/builders 0.15.0

### Node.js version

v16.13.0

### Operating system

Ubuntu 20.04 LTS

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by imranbarbhuiya** [comment] 2022-07-08 10:08
Duplicate of #8244

**Closed** 2022-07-08 10:18 UTC
Labels: duplicate, packages:builders
